// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

// MeResponseBody - `UserResource`
type MeResponseBody struct {
	Data components.UserResource `json:"data"`
}

func (m *MeResponseBody) GetData() components.UserResource {
	if m == nil {
		return components.UserResource{}
	}
	return m.Data
}

type MeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// `UserResource`
	Object *MeResponseBody
}

func (m MeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MeResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MeResponse) GetObject() *MeResponseBody {
	if m == nil {
		return nil
	}
	return m.Object
}
