// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
)

type OrganizationsTeamsMembersDestroyRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The team ID
	Team int64 `pathParam:"style=simple,explode=false,name=team"`
	// The user ID
	User int64 `pathParam:"style=simple,explode=false,name=user"`
}

func (o *OrganizationsTeamsMembersDestroyRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsTeamsMembersDestroyRequest) GetTeam() int64 {
	if o == nil {
		return 0
	}
	return o.Team
}

func (o *OrganizationsTeamsMembersDestroyRequest) GetUser() int64 {
	if o == nil {
		return 0
	}
	return o.User
}

type OrganizationsTeamsMembersDestroyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *OrganizationsTeamsMembersDestroyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
