// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersSSHKeysIndexRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The number of results that will be returned per page.
	PageSize *int64 `default:"30" queryParam:"style=form,explode=true,name=page[size]"`
	// The cursor to start the pagination from.
	PageCursor *string `queryParam:"style=form,explode=true,name=page[cursor]"`
	FilterName *string `queryParam:"style=form,explode=true,name=filter[name]"`
	FilterUser *string `queryParam:"style=form,explode=true,name=filter[user]"`
}

func (o OrganizationsServersSSHKeysIndexRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersSSHKeysIndexRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersSSHKeysIndexRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersSSHKeysIndexRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersSSHKeysIndexRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *OrganizationsServersSSHKeysIndexRequest) GetPageCursor() *string {
	if o == nil {
		return nil
	}
	return o.PageCursor
}

func (o *OrganizationsServersSSHKeysIndexRequest) GetFilterName() *string {
	if o == nil {
		return nil
	}
	return o.FilterName
}

func (o *OrganizationsServersSSHKeysIndexRequest) GetFilterUser() *string {
	if o == nil {
		return nil
	}
	return o.FilterUser
}

type OrganizationsServersSSHKeysIndexLinks struct {
	First *string `json:"first,omitzero"`
	Last  *string `json:"last,omitzero"`
	Prev  *string `json:"prev,omitzero"`
	Next  *string `json:"next,omitzero"`
}

func (o *OrganizationsServersSSHKeysIndexLinks) GetFirst() *string {
	if o == nil {
		return nil
	}
	return o.First
}

func (o *OrganizationsServersSSHKeysIndexLinks) GetLast() *string {
	if o == nil {
		return nil
	}
	return o.Last
}

func (o *OrganizationsServersSSHKeysIndexLinks) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}

func (o *OrganizationsServersSSHKeysIndexLinks) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

type OrganizationsServersSSHKeysIndexMeta struct {
	// Base path for paginator generated URLs.
	Path *string `json:"path"`
	// Number of items shown per page.
	PerPage int64 `json:"per_page"`
	// The "cursor" that points to the next set of items.
	NextCursor *string `json:"next_cursor"`
	// The "cursor" that points to the previous set of items.
	PrevCursor *string `json:"prev_cursor"`
}

func (o *OrganizationsServersSSHKeysIndexMeta) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *OrganizationsServersSSHKeysIndexMeta) GetPerPage() int64 {
	if o == nil {
		return 0
	}
	return o.PerPage
}

func (o *OrganizationsServersSSHKeysIndexMeta) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *OrganizationsServersSSHKeysIndexMeta) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

// OrganizationsServersSSHKeysIndexResponseBody - Paginated set of `KeyResource`
type OrganizationsServersSSHKeysIndexResponseBody struct {
	Data  []components.KeyResource              `json:"data"`
	Links OrganizationsServersSSHKeysIndexLinks `json:"links"`
	Meta  OrganizationsServersSSHKeysIndexMeta  `json:"meta"`
}

func (o *OrganizationsServersSSHKeysIndexResponseBody) GetData() []components.KeyResource {
	if o == nil {
		return []components.KeyResource{}
	}
	return o.Data
}

func (o *OrganizationsServersSSHKeysIndexResponseBody) GetLinks() OrganizationsServersSSHKeysIndexLinks {
	if o == nil {
		return OrganizationsServersSSHKeysIndexLinks{}
	}
	return o.Links
}

func (o *OrganizationsServersSSHKeysIndexResponseBody) GetMeta() OrganizationsServersSSHKeysIndexMeta {
	if o == nil {
		return OrganizationsServersSSHKeysIndexMeta{}
	}
	return o.Meta
}

type OrganizationsServersSSHKeysIndexResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated set of `KeyResource`
	Object *OrganizationsServersSSHKeysIndexResponseBody
}

func (o OrganizationsServersSSHKeysIndexResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersSSHKeysIndexResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersSSHKeysIndexResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersSSHKeysIndexResponse) GetObject() *OrganizationsServersSSHKeysIndexResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
