// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersBackgroundProcessesShowRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The background process ID
	BackgroundProcess int64 `pathParam:"style=simple,explode=false,name=backgroundProcess"`
}

func (o *OrganizationsServersBackgroundProcessesShowRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersBackgroundProcessesShowRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersBackgroundProcessesShowRequest) GetBackgroundProcess() int64 {
	if o == nil {
		return 0
	}
	return o.BackgroundProcess
}

// OrganizationsServersBackgroundProcessesShowResponseBody - `BackgroundProcessResource`
type OrganizationsServersBackgroundProcessesShowResponseBody struct {
	Data components.BackgroundProcessResource `json:"data"`
}

func (o *OrganizationsServersBackgroundProcessesShowResponseBody) GetData() components.BackgroundProcessResource {
	if o == nil {
		return components.BackgroundProcessResource{}
	}
	return o.Data
}

type OrganizationsServersBackgroundProcessesShowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// `BackgroundProcessResource`
	Object *OrganizationsServersBackgroundProcessesShowResponseBody
}

func (o OrganizationsServersBackgroundProcessesShowResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersBackgroundProcessesShowResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersBackgroundProcessesShowResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersBackgroundProcessesShowResponse) GetObject() *OrganizationsServersBackgroundProcessesShowResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
