// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersDatabaseBackupsInstancesShowRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The backup configuration ID
	BackupConfiguration int64 `pathParam:"style=simple,explode=false,name=backupConfiguration"`
	// The backup ID
	Backup int64 `pathParam:"style=simple,explode=false,name=backup"`
}

func (o *OrganizationsServersDatabaseBackupsInstancesShowRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersDatabaseBackupsInstancesShowRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersDatabaseBackupsInstancesShowRequest) GetBackupConfiguration() int64 {
	if o == nil {
		return 0
	}
	return o.BackupConfiguration
}

func (o *OrganizationsServersDatabaseBackupsInstancesShowRequest) GetBackup() int64 {
	if o == nil {
		return 0
	}
	return o.Backup
}

// OrganizationsServersDatabaseBackupsInstancesShowResponseBody - `BackupResource`
type OrganizationsServersDatabaseBackupsInstancesShowResponseBody struct {
	Data components.BackupResource `json:"data"`
}

func (o *OrganizationsServersDatabaseBackupsInstancesShowResponseBody) GetData() components.BackupResource {
	if o == nil {
		return components.BackupResource{}
	}
	return o.Data
}

type OrganizationsServersDatabaseBackupsInstancesShowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// `BackupResource`
	Object *OrganizationsServersDatabaseBackupsInstancesShowResponseBody
}

func (o OrganizationsServersDatabaseBackupsInstancesShowResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersDatabaseBackupsInstancesShowResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersDatabaseBackupsInstancesShowResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersDatabaseBackupsInstancesShowResponse) GetObject() *OrganizationsServersDatabaseBackupsInstancesShowResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
