// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
)

type OrganizationsStorageProvidersDestroyRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The storage configuration ID
	StorageConfiguration int64 `pathParam:"style=simple,explode=false,name=storageConfiguration"`
}

func (o *OrganizationsStorageProvidersDestroyRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsStorageProvidersDestroyRequest) GetStorageConfiguration() int64 {
	if o == nil {
		return 0
	}
	return o.StorageConfiguration
}

type OrganizationsStorageProvidersDestroyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *OrganizationsStorageProvidersDestroyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
