// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersEventsIndexRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// Available sorts are `created_at`, `updated_at`. You can sort by multiple options by separating them with a comma. To sort in descending order, use `-` sign in front of the sort, for example: `-created_at`.
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// Available includes are `initiator`, `initiatorCount`, `initiatorExists`. You can include multiple options by separating them with a comma.
	Include *string `queryParam:"style=form,explode=true,name=include"`
	// The number of results that will be returned per page.
	PageSize *int64 `default:"30" queryParam:"style=form,explode=true,name=page[size]"`
	// The cursor to start the pagination from.
	PageCursor *string `queryParam:"style=form,explode=true,name=page[cursor]"`
	// The user ID of the event initiator.
	FilterInitiatedBy *string `queryParam:"style=form,explode=true,name=filter[initiated_by]"`
	// The server user that the event was run as.
	FilterRanAs *string `queryParam:"style=form,explode=true,name=filter[ran_as]"`
}

func (o OrganizationsServersEventsIndexRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersEventsIndexRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersEventsIndexRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersEventsIndexRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersEventsIndexRequest) GetSort() *string {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *OrganizationsServersEventsIndexRequest) GetInclude() *string {
	if o == nil {
		return nil
	}
	return o.Include
}

func (o *OrganizationsServersEventsIndexRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *OrganizationsServersEventsIndexRequest) GetPageCursor() *string {
	if o == nil {
		return nil
	}
	return o.PageCursor
}

func (o *OrganizationsServersEventsIndexRequest) GetFilterInitiatedBy() *string {
	if o == nil {
		return nil
	}
	return o.FilterInitiatedBy
}

func (o *OrganizationsServersEventsIndexRequest) GetFilterRanAs() *string {
	if o == nil {
		return nil
	}
	return o.FilterRanAs
}

type OrganizationsServersEventsIndexLinks struct {
	First *string `json:"first,omitzero"`
	Last  *string `json:"last,omitzero"`
	Prev  *string `json:"prev,omitzero"`
	Next  *string `json:"next,omitzero"`
}

func (o *OrganizationsServersEventsIndexLinks) GetFirst() *string {
	if o == nil {
		return nil
	}
	return o.First
}

func (o *OrganizationsServersEventsIndexLinks) GetLast() *string {
	if o == nil {
		return nil
	}
	return o.Last
}

func (o *OrganizationsServersEventsIndexLinks) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}

func (o *OrganizationsServersEventsIndexLinks) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

type OrganizationsServersEventsIndexMeta struct {
	// Base path for paginator generated URLs.
	Path *string `json:"path"`
	// Number of items shown per page.
	PerPage int64 `json:"per_page"`
	// The "cursor" that points to the next set of items.
	NextCursor *string `json:"next_cursor"`
	// The "cursor" that points to the previous set of items.
	PrevCursor *string `json:"prev_cursor"`
}

func (o *OrganizationsServersEventsIndexMeta) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *OrganizationsServersEventsIndexMeta) GetPerPage() int64 {
	if o == nil {
		return 0
	}
	return o.PerPage
}

func (o *OrganizationsServersEventsIndexMeta) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *OrganizationsServersEventsIndexMeta) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

// OrganizationsServersEventsIndexResponseBody - Paginated set of `EventResource`
type OrganizationsServersEventsIndexResponseBody struct {
	Data     []components.EventResource           `json:"data"`
	Links    OrganizationsServersEventsIndexLinks `json:"links"`
	Meta     OrganizationsServersEventsIndexMeta  `json:"meta"`
	Included []components.UserResource            `json:"included,omitzero"`
}

func (o OrganizationsServersEventsIndexResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersEventsIndexResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersEventsIndexResponseBody) GetData() []components.EventResource {
	if o == nil {
		return []components.EventResource{}
	}
	return o.Data
}

func (o *OrganizationsServersEventsIndexResponseBody) GetLinks() OrganizationsServersEventsIndexLinks {
	if o == nil {
		return OrganizationsServersEventsIndexLinks{}
	}
	return o.Links
}

func (o *OrganizationsServersEventsIndexResponseBody) GetMeta() OrganizationsServersEventsIndexMeta {
	if o == nil {
		return OrganizationsServersEventsIndexMeta{}
	}
	return o.Meta
}

func (o *OrganizationsServersEventsIndexResponseBody) GetIncluded() []components.UserResource {
	if o == nil {
		return nil
	}
	return o.Included
}

type OrganizationsServersEventsIndexResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated set of `EventResource`
	Object *OrganizationsServersEventsIndexResponseBody
}

func (o OrganizationsServersEventsIndexResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersEventsIndexResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersEventsIndexResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersEventsIndexResponse) GetObject() *OrganizationsServersEventsIndexResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
