// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServerCredentialsVpcsStoreRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The credential ID
	Credential int64                                         `pathParam:"style=simple,explode=false,name=credential"`
	Region     string                                        `pathParam:"style=simple,explode=false,name=region"`
	Body       components.CreateServerProviderNetworkRequest `request:"mediaType=application/json"`
}

func (o *OrganizationsServerCredentialsVpcsStoreRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServerCredentialsVpcsStoreRequest) GetCredential() int64 {
	if o == nil {
		return 0
	}
	return o.Credential
}

func (o *OrganizationsServerCredentialsVpcsStoreRequest) GetRegion() string {
	if o == nil {
		return ""
	}
	return o.Region
}

func (o *OrganizationsServerCredentialsVpcsStoreRequest) GetBody() components.CreateServerProviderNetworkRequest {
	if o == nil {
		return components.CreateServerProviderNetworkRequest{}
	}
	return o.Body
}

// OrganizationsServerCredentialsVpcsStoreResponseBody2 - `VpcResource`
type OrganizationsServerCredentialsVpcsStoreResponseBody2 struct {
	Data components.VpcResource `json:"data"`
}

func (o *OrganizationsServerCredentialsVpcsStoreResponseBody2) GetData() components.VpcResource {
	if o == nil {
		return components.VpcResource{}
	}
	return o.Data
}

// #region class-body-organizationsservercredentialsvpcsstoreresponsebody2
// #endregion class-body-organizationsservercredentialsvpcsstoreresponsebody2

type OrganizationsServerCredentialsVpcsStoreResponseBody1 struct {
}

// #region class-body-organizationsservercredentialsvpcsstoreresponsebody1
// #endregion class-body-organizationsservercredentialsvpcsstoreresponsebody1

type OrganizationsServerCredentialsVpcsStoreResponse struct {
	HTTPMeta                        components.HTTPMetadata `json:"-"`
	TwoHundredApplicationJSONObject *OrganizationsServerCredentialsVpcsStoreResponseBody1
	// `VpcResource`
	TwoHundredAndOneApplicationVndAPIPlusJSONObject *OrganizationsServerCredentialsVpcsStoreResponseBody2
}

func (o OrganizationsServerCredentialsVpcsStoreResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServerCredentialsVpcsStoreResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServerCredentialsVpcsStoreResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServerCredentialsVpcsStoreResponse) GetTwoHundredApplicationJSONObject() *OrganizationsServerCredentialsVpcsStoreResponseBody1 {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *OrganizationsServerCredentialsVpcsStoreResponse) GetTwoHundredAndOneApplicationVndAPIPlusJSONObject() *OrganizationsServerCredentialsVpcsStoreResponseBody2 {
	if o == nil {
		return nil
	}
	return o.TwoHundredAndOneApplicationVndAPIPlusJSONObject
}
