// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsSitesIndexRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// Available includes are `server`, `serverCount`, `serverExists`, `tags`, `tagsCount`, `tagsExists`, `latestDeployment`, `latestDeploymentCount`, `latestDeploymentExists`, `securityRules`, `securityRulesCount`, `securityRulesExists`, `redirectRules`, `redirectRulesCount`, `redirectRulesExists`. You can include multiple options by separating them with a comma.
	Include *string `queryParam:"style=form,explode=true,name=include"`
	// The number of results that will be returned per page.
	PageSize *int64 `default:"30" queryParam:"style=form,explode=true,name=page[size]"`
	// The cursor to start the pagination from.
	PageCursor *string `queryParam:"style=form,explode=true,name=page[cursor]"`
	FilterName *string `queryParam:"style=form,explode=true,name=filter[name]"`
}

func (o OrganizationsSitesIndexRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsSitesIndexRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsSitesIndexRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsSitesIndexRequest) GetInclude() *string {
	if o == nil {
		return nil
	}
	return o.Include
}

func (o *OrganizationsSitesIndexRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *OrganizationsSitesIndexRequest) GetPageCursor() *string {
	if o == nil {
		return nil
	}
	return o.PageCursor
}

func (o *OrganizationsSitesIndexRequest) GetFilterName() *string {
	if o == nil {
		return nil
	}
	return o.FilterName
}

type OrganizationsSitesIndexLinks struct {
	First *string `json:"first,omitzero"`
	Last  *string `json:"last,omitzero"`
	Prev  *string `json:"prev,omitzero"`
	Next  *string `json:"next,omitzero"`
}

func (o *OrganizationsSitesIndexLinks) GetFirst() *string {
	if o == nil {
		return nil
	}
	return o.First
}

func (o *OrganizationsSitesIndexLinks) GetLast() *string {
	if o == nil {
		return nil
	}
	return o.Last
}

func (o *OrganizationsSitesIndexLinks) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}

func (o *OrganizationsSitesIndexLinks) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

type OrganizationsSitesIndexMeta struct {
	// Base path for paginator generated URLs.
	Path *string `json:"path"`
	// Number of items shown per page.
	PerPage int64 `json:"per_page"`
	// The "cursor" that points to the next set of items.
	NextCursor *string `json:"next_cursor"`
	// The "cursor" that points to the previous set of items.
	PrevCursor *string `json:"prev_cursor"`
}

func (o *OrganizationsSitesIndexMeta) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *OrganizationsSitesIndexMeta) GetPerPage() int64 {
	if o == nil {
		return 0
	}
	return o.PerPage
}

func (o *OrganizationsSitesIndexMeta) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *OrganizationsSitesIndexMeta) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

type OrganizationsSitesIndexIncludedType string

const (
	OrganizationsSitesIndexIncludedTypeServers       OrganizationsSitesIndexIncludedType = "servers"
	OrganizationsSitesIndexIncludedTypeTags          OrganizationsSitesIndexIncludedType = "tags"
	OrganizationsSitesIndexIncludedTypeDeployments   OrganizationsSitesIndexIncludedType = "deployments"
	OrganizationsSitesIndexIncludedTypeSecurityRules OrganizationsSitesIndexIncludedType = "securityRules"
	OrganizationsSitesIndexIncludedTypeRedirectRules OrganizationsSitesIndexIncludedType = "redirect-rules"
	OrganizationsSitesIndexIncludedTypeUnknown       OrganizationsSitesIndexIncludedType = "UNKNOWN"
)

type OrganizationsSitesIndexIncluded struct {
	ServerResource       *components.ServerResource       `queryParam:"inline" union:"member"`
	TagResource          *components.TagResource          `queryParam:"inline" union:"member"`
	DeploymentResource   *components.DeploymentResource   `queryParam:"inline" union:"member"`
	SecurityRuleResource *components.SecurityRuleResource `queryParam:"inline" union:"member"`
	RedirectRuleResource *components.RedirectRuleResource `queryParam:"inline" union:"member"`
	UnknownRaw           json.RawMessage                  `json:"-" union:"unknown"`

	Type OrganizationsSitesIndexIncludedType
}

func CreateOrganizationsSitesIndexIncludedServers(servers components.ServerResource) OrganizationsSitesIndexIncluded {
	typ := OrganizationsSitesIndexIncludedTypeServers

	typStr := components.ServerResourceType(typ)
	servers.Type = typStr

	return OrganizationsSitesIndexIncluded{
		ServerResource: &servers,
		Type:           typ,
	}
}

func CreateOrganizationsSitesIndexIncludedTags(tags components.TagResource) OrganizationsSitesIndexIncluded {
	typ := OrganizationsSitesIndexIncludedTypeTags

	typStr := components.TagResourceType(typ)
	tags.Type = typStr

	return OrganizationsSitesIndexIncluded{
		TagResource: &tags,
		Type:        typ,
	}
}

func CreateOrganizationsSitesIndexIncludedDeployments(deployments components.DeploymentResource) OrganizationsSitesIndexIncluded {
	typ := OrganizationsSitesIndexIncludedTypeDeployments

	typStr := components.DeploymentResourceType(typ)
	deployments.Type = typStr

	return OrganizationsSitesIndexIncluded{
		DeploymentResource: &deployments,
		Type:               typ,
	}
}

func CreateOrganizationsSitesIndexIncludedSecurityRules(securityRules components.SecurityRuleResource) OrganizationsSitesIndexIncluded {
	typ := OrganizationsSitesIndexIncludedTypeSecurityRules

	typStr := components.SecurityRuleResourceType(typ)
	securityRules.Type = typStr

	return OrganizationsSitesIndexIncluded{
		SecurityRuleResource: &securityRules,
		Type:                 typ,
	}
}

func CreateOrganizationsSitesIndexIncludedRedirectRules(redirectRules components.RedirectRuleResource) OrganizationsSitesIndexIncluded {
	typ := OrganizationsSitesIndexIncludedTypeRedirectRules

	typStr := components.RedirectRuleResourceType(typ)
	redirectRules.Type = typStr

	return OrganizationsSitesIndexIncluded{
		RedirectRuleResource: &redirectRules,
		Type:                 typ,
	}
}

func CreateOrganizationsSitesIndexIncludedUnknown(raw json.RawMessage) OrganizationsSitesIndexIncluded {
	return OrganizationsSitesIndexIncluded{
		UnknownRaw: raw,
		Type:       OrganizationsSitesIndexIncludedTypeUnknown,
	}
}

func (u OrganizationsSitesIndexIncluded) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u OrganizationsSitesIndexIncluded) IsUnknown() bool {
	return u.Type == OrganizationsSitesIndexIncludedTypeUnknown
}

func (u *OrganizationsSitesIndexIncluded) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OrganizationsSitesIndexIncludedTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OrganizationsSitesIndexIncludedTypeUnknown
		return nil
	}

	switch dis.Type {
	case "servers":
		serverResource := new(components.ServerResource)
		if err := utils.UnmarshalJSON(data, &serverResource, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == servers) type components.ServerResource within OrganizationsSitesIndexIncluded: %w", string(data), err)
		}

		u.ServerResource = serverResource
		u.Type = OrganizationsSitesIndexIncludedTypeServers
		return nil
	case "tags":
		tagResource := new(components.TagResource)
		if err := utils.UnmarshalJSON(data, &tagResource, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == tags) type components.TagResource within OrganizationsSitesIndexIncluded: %w", string(data), err)
		}

		u.TagResource = tagResource
		u.Type = OrganizationsSitesIndexIncludedTypeTags
		return nil
	case "deployments":
		deploymentResource := new(components.DeploymentResource)
		if err := utils.UnmarshalJSON(data, &deploymentResource, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == deployments) type components.DeploymentResource within OrganizationsSitesIndexIncluded: %w", string(data), err)
		}

		u.DeploymentResource = deploymentResource
		u.Type = OrganizationsSitesIndexIncludedTypeDeployments
		return nil
	case "securityRules":
		securityRuleResource := new(components.SecurityRuleResource)
		if err := utils.UnmarshalJSON(data, &securityRuleResource, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == securityRules) type components.SecurityRuleResource within OrganizationsSitesIndexIncluded: %w", string(data), err)
		}

		u.SecurityRuleResource = securityRuleResource
		u.Type = OrganizationsSitesIndexIncludedTypeSecurityRules
		return nil
	case "redirect-rules":
		redirectRuleResource := new(components.RedirectRuleResource)
		if err := utils.UnmarshalJSON(data, &redirectRuleResource, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == redirect-rules) type components.RedirectRuleResource within OrganizationsSitesIndexIncluded: %w", string(data), err)
		}

		u.RedirectRuleResource = redirectRuleResource
		u.Type = OrganizationsSitesIndexIncludedTypeRedirectRules
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OrganizationsSitesIndexIncludedTypeUnknown
		return nil
	}

}

func (u OrganizationsSitesIndexIncluded) MarshalJSON() ([]byte, error) {
	if u.ServerResource != nil {
		return utils.MarshalJSON(u.ServerResource, "", true)
	}

	if u.TagResource != nil {
		return utils.MarshalJSON(u.TagResource, "", true)
	}

	if u.DeploymentResource != nil {
		return utils.MarshalJSON(u.DeploymentResource, "", true)
	}

	if u.SecurityRuleResource != nil {
		return utils.MarshalJSON(u.SecurityRuleResource, "", true)
	}

	if u.RedirectRuleResource != nil {
		return utils.MarshalJSON(u.RedirectRuleResource, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type OrganizationsSitesIndexIncluded: all fields are null")
}

// OrganizationsSitesIndexResponseBody - Paginated set of `SiteResource`
type OrganizationsSitesIndexResponseBody struct {
	Data     []components.SiteResource         `json:"data"`
	Links    OrganizationsSitesIndexLinks      `json:"links"`
	Meta     OrganizationsSitesIndexMeta       `json:"meta"`
	Included []OrganizationsSitesIndexIncluded `json:"included,omitzero"`
}

func (o OrganizationsSitesIndexResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsSitesIndexResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsSitesIndexResponseBody) GetData() []components.SiteResource {
	if o == nil {
		return []components.SiteResource{}
	}
	return o.Data
}

func (o *OrganizationsSitesIndexResponseBody) GetLinks() OrganizationsSitesIndexLinks {
	if o == nil {
		return OrganizationsSitesIndexLinks{}
	}
	return o.Links
}

func (o *OrganizationsSitesIndexResponseBody) GetMeta() OrganizationsSitesIndexMeta {
	if o == nil {
		return OrganizationsSitesIndexMeta{}
	}
	return o.Meta
}

func (o *OrganizationsSitesIndexResponseBody) GetIncluded() []OrganizationsSitesIndexIncluded {
	if o == nil {
		return nil
	}
	return o.Included
}

type OrganizationsSitesIndexResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated set of `SiteResource`
	Object *OrganizationsSitesIndexResponseBody
}

func (o OrganizationsSitesIndexResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsSitesIndexResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsSitesIndexResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsSitesIndexResponse) GetObject() *OrganizationsSitesIndexResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
