// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsTeamsServersIndexRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The team ID
	Team int64 `pathParam:"style=simple,explode=false,name=team"`
	// The number of results that will be returned per page.
	PageSize *int64 `default:"30" queryParam:"style=form,explode=true,name=page[size]"`
	// The cursor to start the pagination from.
	PageCursor *string `queryParam:"style=form,explode=true,name=page[cursor]"`
}

func (o OrganizationsTeamsServersIndexRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsTeamsServersIndexRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsTeamsServersIndexRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsTeamsServersIndexRequest) GetTeam() int64 {
	if o == nil {
		return 0
	}
	return o.Team
}

func (o *OrganizationsTeamsServersIndexRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *OrganizationsTeamsServersIndexRequest) GetPageCursor() *string {
	if o == nil {
		return nil
	}
	return o.PageCursor
}

type OrganizationsTeamsServersIndexLinks struct {
	First *string `json:"first,omitzero"`
	Last  *string `json:"last,omitzero"`
	Prev  *string `json:"prev,omitzero"`
	Next  *string `json:"next,omitzero"`
}

func (o *OrganizationsTeamsServersIndexLinks) GetFirst() *string {
	if o == nil {
		return nil
	}
	return o.First
}

func (o *OrganizationsTeamsServersIndexLinks) GetLast() *string {
	if o == nil {
		return nil
	}
	return o.Last
}

func (o *OrganizationsTeamsServersIndexLinks) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}

func (o *OrganizationsTeamsServersIndexLinks) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

type OrganizationsTeamsServersIndexMeta struct {
	// Base path for paginator generated URLs.
	Path *string `json:"path"`
	// Number of items shown per page.
	PerPage int64 `json:"per_page"`
	// The "cursor" that points to the next set of items.
	NextCursor *string `json:"next_cursor"`
	// The "cursor" that points to the previous set of items.
	PrevCursor *string `json:"prev_cursor"`
}

func (o *OrganizationsTeamsServersIndexMeta) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *OrganizationsTeamsServersIndexMeta) GetPerPage() int64 {
	if o == nil {
		return 0
	}
	return o.PerPage
}

func (o *OrganizationsTeamsServersIndexMeta) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *OrganizationsTeamsServersIndexMeta) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

// OrganizationsTeamsServersIndexResponseBody - Paginated set of `ServerResource`
type OrganizationsTeamsServersIndexResponseBody struct {
	Data     []components.ServerResource         `json:"data"`
	Links    OrganizationsTeamsServersIndexLinks `json:"links"`
	Meta     OrganizationsTeamsServersIndexMeta  `json:"meta"`
	Included []components.TagResource            `json:"included,omitzero"`
}

func (o OrganizationsTeamsServersIndexResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsTeamsServersIndexResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsTeamsServersIndexResponseBody) GetData() []components.ServerResource {
	if o == nil {
		return []components.ServerResource{}
	}
	return o.Data
}

func (o *OrganizationsTeamsServersIndexResponseBody) GetLinks() OrganizationsTeamsServersIndexLinks {
	if o == nil {
		return OrganizationsTeamsServersIndexLinks{}
	}
	return o.Links
}

func (o *OrganizationsTeamsServersIndexResponseBody) GetMeta() OrganizationsTeamsServersIndexMeta {
	if o == nil {
		return OrganizationsTeamsServersIndexMeta{}
	}
	return o.Meta
}

func (o *OrganizationsTeamsServersIndexResponseBody) GetIncluded() []components.TagResource {
	if o == nil {
		return nil
	}
	return o.Included
}

type OrganizationsTeamsServersIndexResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated set of `ServerResource`
	Object *OrganizationsTeamsServersIndexResponseBody
}

func (o OrganizationsTeamsServersIndexResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsTeamsServersIndexResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsTeamsServersIndexResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsTeamsServersIndexResponse) GetObject() *OrganizationsTeamsServersIndexResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
