// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/optionalnullable"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type UbuntuVersion string

const (
	UbuntuVersionTwentyTwoDot04  UbuntuVersion = "22.04"
	UbuntuVersionTwentyFourDot04 UbuntuVersion = "24.04"
)

func (e UbuntuVersion) ToPointer() *UbuntuVersion {
	return &e
}
func (e *UbuntuVersion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "22.04":
		fallthrough
	case "24.04":
		*e = UbuntuVersion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UbuntuVersion: %v", v)
	}
}

type Aws struct {
	RegionID   *string `json:"region_id,omitzero"`
	SizeID     *string `json:"size_id,omitzero"`
	VpcUUID    *string `json:"vpc_uuid,omitzero"`
	SubnetUUID *string `json:"subnet_uuid,omitzero"`
	DiskSize   *int64  `json:"disk_size,omitzero"`
}

func (a *Aws) GetRegionID() *string {
	if a == nil {
		return nil
	}
	return a.RegionID
}

func (a *Aws) GetSizeID() *string {
	if a == nil {
		return nil
	}
	return a.SizeID
}

func (a *Aws) GetVpcUUID() *string {
	if a == nil {
		return nil
	}
	return a.VpcUUID
}

func (a *Aws) GetSubnetUUID() *string {
	if a == nil {
		return nil
	}
	return a.SubnetUUID
}

func (a *Aws) GetDiskSize() *int64 {
	if a == nil {
		return nil
	}
	return a.DiskSize
}

type Ocean2 struct {
	RegionID            *string `json:"region_id,omitzero"`
	SizeID              *string `json:"size_id,omitzero"`
	VpcUUID             *string `json:"vpc_uuid,omitzero"`
	EnableWeeklyBackups *bool   `json:"enable_weekly_backups,omitzero"`
}

func (o *Ocean2) GetRegionID() *string {
	if o == nil {
		return nil
	}
	return o.RegionID
}

func (o *Ocean2) GetSizeID() *string {
	if o == nil {
		return nil
	}
	return o.SizeID
}

func (o *Ocean2) GetVpcUUID() *string {
	if o == nil {
		return nil
	}
	return o.VpcUUID
}

func (o *Ocean2) GetEnableWeeklyBackups() *bool {
	if o == nil {
		return nil
	}
	return o.EnableWeeklyBackups
}

// #region class-body-ocean2
// #endregion class-body-ocean2

type Hetzner struct {
	EnableWeeklyBackups *bool `default:"false" json:"enable_weekly_backups"`
}

func (h Hetzner) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *Hetzner) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *Hetzner) GetEnableWeeklyBackups() *bool {
	if h == nil {
		return nil
	}
	return h.EnableWeeklyBackups
}

type Vultr struct {
	RegionID  *string `json:"region_id,omitzero"`
	SizeID    *string `json:"size_id,omitzero"`
	NetworkID *string `json:"network_id,omitzero"`
}

func (v *Vultr) GetRegionID() *string {
	if v == nil {
		return nil
	}
	return v.RegionID
}

func (v *Vultr) GetSizeID() *string {
	if v == nil {
		return nil
	}
	return v.SizeID
}

func (v *Vultr) GetNetworkID() *string {
	if v == nil {
		return nil
	}
	return v.NetworkID
}

type Akamai struct {
	RegionID *string `json:"region_id,omitzero"`
	SizeID   *string `json:"size_id,omitzero"`
}

func (a *Akamai) GetRegionID() *string {
	if a == nil {
		return nil
	}
	return a.RegionID
}

func (a *Akamai) GetSizeID() *string {
	if a == nil {
		return nil
	}
	return a.SizeID
}

type Laravel struct {
	VpcUUID *string `json:"vpc_uuid,omitzero"`
}

func (l *Laravel) GetVpcUUID() *string {
	if l == nil {
		return nil
	}
	return l.VpcUUID
}

type Custom struct {
	IPAddress        *string                                   `json:"ip_address,omitzero"`
	PrivateIPAddress optionalnullable.OptionalNullable[string] `json:"private_ip_address,omitzero"`
	SSHPort          *int64                                    `json:"ssh_port,omitzero"`
	BehindNat        *bool                                     `json:"behind_nat,omitzero"`
	NatSSHPort       optionalnullable.OptionalNullable[int64]  `json:"nat_ssh_port,omitzero"`
}

func (c *Custom) GetIPAddress() *string {
	if c == nil {
		return nil
	}
	return c.IPAddress
}

func (c *Custom) GetPrivateIPAddress() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.PrivateIPAddress
}

func (c *Custom) GetSSHPort() *int64 {
	if c == nil {
		return nil
	}
	return c.SSHPort
}

func (c *Custom) GetBehindNat() *bool {
	if c == nil {
		return nil
	}
	return c.BehindNat
}

func (c *Custom) GetNatSSHPort() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.NatSSHPort
}

type CreateServerRequest struct {
	Name                  string                                      `json:"name"`
	Provider              string                                      `json:"provider"`
	CredentialID          *int64                                      `json:"credential_id,omitzero"`
	TeamID                optionalnullable.OptionalNullable[int64]    `json:"team_id,omitzero"`
	Type                  components.ServerType                       `json:"type"`
	UbuntuVersion         UbuntuVersion                               `json:"ubuntu_version"`
	PhpVersion            *components.PhpVersion                      `json:"php_version,omitzero"`
	DatabaseType          *components.DatabaseType                    `json:"database_type,omitzero"`
	RecipeID              optionalnullable.OptionalNullable[int64]    `json:"recipe_id,omitzero"`
	Tags                  optionalnullable.OptionalNullable[[]string] `json:"tags,omitzero"`
	Aws                   *Aws                                        `json:"aws,omitzero"`
	Ocean2                *Ocean2                                     `json:"ocean2,omitzero"`
	Hetzner               *Hetzner                                    `json:"hetzner,omitzero"`
	Vultr                 *Vultr                                      `json:"vultr,omitzero"`
	Akamai                *Akamai                                     `json:"akamai,omitzero"`
	Laravel               *Laravel                                    `json:"laravel,omitzero"`
	Custom                *Custom                                     `json:"custom,omitzero"`
	AddKeyToSourceControl *bool                                       `default:"true" json:"add_key_to_source_control"`
	Database              *string                                     `json:"database,omitzero"`
}

func (c CreateServerRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateServerRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateServerRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateServerRequest) GetProvider() string {
	if c == nil {
		return ""
	}
	return c.Provider
}

func (c *CreateServerRequest) GetCredentialID() *int64 {
	if c == nil {
		return nil
	}
	return c.CredentialID
}

func (c *CreateServerRequest) GetTeamID() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.TeamID
}

func (c *CreateServerRequest) GetType() components.ServerType {
	if c == nil {
		return components.ServerType("")
	}
	return c.Type
}

func (c *CreateServerRequest) GetUbuntuVersion() UbuntuVersion {
	if c == nil {
		return UbuntuVersion("")
	}
	return c.UbuntuVersion
}

func (c *CreateServerRequest) GetPhpVersion() *components.PhpVersion {
	if c == nil {
		return nil
	}
	return c.PhpVersion
}

func (c *CreateServerRequest) GetDatabaseType() *components.DatabaseType {
	if c == nil {
		return nil
	}
	return c.DatabaseType
}

func (c *CreateServerRequest) GetRecipeID() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.RecipeID
}

func (c *CreateServerRequest) GetTags() optionalnullable.OptionalNullable[[]string] {
	if c == nil {
		return nil
	}
	return c.Tags
}

func (c *CreateServerRequest) GetAws() *Aws {
	if c == nil {
		return nil
	}
	return c.Aws
}

func (c *CreateServerRequest) GetOcean2() *Ocean2 {
	if c == nil {
		return nil
	}
	return c.Ocean2
}

func (c *CreateServerRequest) GetHetzner() *Hetzner {
	if c == nil {
		return nil
	}
	return c.Hetzner
}

func (c *CreateServerRequest) GetVultr() *Vultr {
	if c == nil {
		return nil
	}
	return c.Vultr
}

func (c *CreateServerRequest) GetAkamai() *Akamai {
	if c == nil {
		return nil
	}
	return c.Akamai
}

func (c *CreateServerRequest) GetLaravel() *Laravel {
	if c == nil {
		return nil
	}
	return c.Laravel
}

func (c *CreateServerRequest) GetCustom() *Custom {
	if c == nil {
		return nil
	}
	return c.Custom
}

func (c *CreateServerRequest) GetAddKeyToSourceControl() *bool {
	if c == nil {
		return nil
	}
	return c.AddKeyToSourceControl
}

func (c *CreateServerRequest) GetDatabase() *string {
	if c == nil {
		return nil
	}
	return c.Database
}

type OrganizationsServersStoreRequest struct {
	// The organization slug
	Organization string               `pathParam:"style=simple,explode=false,name=organization"`
	Body         *CreateServerRequest `request:"mediaType=application/json"`
}

func (o OrganizationsServersStoreRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersStoreRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersStoreRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersStoreRequest) GetBody() *CreateServerRequest {
	if o == nil {
		return nil
	}
	return o.Body
}

// OrganizationsServersStoreResponseBody - `ServerResource`
type OrganizationsServersStoreResponseBody struct {
	Data     components.ServerResource `json:"data"`
	Included []components.TagResource  `json:"included,omitzero"`
}

func (o OrganizationsServersStoreResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersStoreResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersStoreResponseBody) GetData() components.ServerResource {
	if o == nil {
		return components.ServerResource{}
	}
	return o.Data
}

func (o *OrganizationsServersStoreResponseBody) GetIncluded() []components.TagResource {
	if o == nil {
		return nil
	}
	return o.Included
}

type OrganizationsServersStoreResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// `ServerResource`
	Object *OrganizationsServersStoreResponseBody
}

func (o OrganizationsServersStoreResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersStoreResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersStoreResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersStoreResponse) GetObject() *OrganizationsServersStoreResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
