// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersSitesRedirectRulesShowRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The site ID
	Site int64 `pathParam:"style=simple,explode=false,name=site"`
	// The redirect rule ID
	RedirectRule int64 `pathParam:"style=simple,explode=false,name=redirectRule"`
}

func (o *OrganizationsServersSitesRedirectRulesShowRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersSitesRedirectRulesShowRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersSitesRedirectRulesShowRequest) GetSite() int64 {
	if o == nil {
		return 0
	}
	return o.Site
}

func (o *OrganizationsServersSitesRedirectRulesShowRequest) GetRedirectRule() int64 {
	if o == nil {
		return 0
	}
	return o.RedirectRule
}

// OrganizationsServersSitesRedirectRulesShowResponseBody - `RedirectRuleResource`
type OrganizationsServersSitesRedirectRulesShowResponseBody struct {
	Data components.RedirectRuleResource `json:"data"`
}

func (o *OrganizationsServersSitesRedirectRulesShowResponseBody) GetData() components.RedirectRuleResource {
	if o == nil {
		return components.RedirectRuleResource{}
	}
	return o.Data
}

type OrganizationsServersSitesRedirectRulesShowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// `RedirectRuleResource`
	Object *OrganizationsServersSitesRedirectRulesShowResponseBody
}

func (o OrganizationsServersSitesRedirectRulesShowResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersSitesRedirectRulesShowResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersSitesRedirectRulesShowResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersSitesRedirectRulesShowResponse) GetObject() *OrganizationsServersSitesRedirectRulesShowResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
