// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersPhpMaxExecutionTimeShowRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
}

func (o *OrganizationsServersPhpMaxExecutionTimeShowRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersPhpMaxExecutionTimeShowRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

// OrganizationsServersPhpMaxExecutionTimeShowResponseBody - `PhpMaxExecutionTimeResource`
type OrganizationsServersPhpMaxExecutionTimeShowResponseBody struct {
	Data components.PhpMaxExecutionTimeResource `json:"data"`
}

func (o *OrganizationsServersPhpMaxExecutionTimeShowResponseBody) GetData() components.PhpMaxExecutionTimeResource {
	if o == nil {
		return components.PhpMaxExecutionTimeResource{}
	}
	return o.Data
}

type OrganizationsServersPhpMaxExecutionTimeShowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// `PhpMaxExecutionTimeResource`
	Object *OrganizationsServersPhpMaxExecutionTimeShowResponseBody
}

func (o OrganizationsServersPhpMaxExecutionTimeShowResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersPhpMaxExecutionTimeShowResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersPhpMaxExecutionTimeShowResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersPhpMaxExecutionTimeShowResponse) GetObject() *OrganizationsServersPhpMaxExecutionTimeShowResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
