// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
)

type OrganizationsServersSitesDomainsDestroyRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The site ID
	Site int64 `pathParam:"style=simple,explode=false,name=site"`
	// The domain record ID
	DomainRecord int64 `pathParam:"style=simple,explode=false,name=domainRecord"`
}

func (o *OrganizationsServersSitesDomainsDestroyRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersSitesDomainsDestroyRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersSitesDomainsDestroyRequest) GetSite() int64 {
	if o == nil {
		return 0
	}
	return o.Site
}

func (o *OrganizationsServersSitesDomainsDestroyRequest) GetDomainRecord() int64 {
	if o == nil {
		return 0
	}
	return o.DomainRecord
}

type OrganizationsServersSitesDomainsDestroyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *OrganizationsServersSitesDomainsDestroyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
