// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
)

type OrganizationsServersBackgroundProcessesUpdateRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The background process ID
	BackgroundProcess int64                                     `pathParam:"style=simple,explode=false,name=backgroundProcess"`
	Body              components.UpdateBackgroundProcessRequest `request:"mediaType=application/json"`
}

func (o *OrganizationsServersBackgroundProcessesUpdateRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersBackgroundProcessesUpdateRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersBackgroundProcessesUpdateRequest) GetBackgroundProcess() int64 {
	if o == nil {
		return 0
	}
	return o.BackgroundProcess
}

func (o *OrganizationsServersBackgroundProcessesUpdateRequest) GetBody() components.UpdateBackgroundProcessRequest {
	if o == nil {
		return components.UpdateBackgroundProcessRequest{}
	}
	return o.Body
}

type OrganizationsServersBackgroundProcessesUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *OrganizationsServersBackgroundProcessesUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
