// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersSitesHealthcheckUpdateRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The site ID
	Site int64                                        `pathParam:"style=simple,explode=false,name=site"`
	Body *components.UpdateHealthcheckEndpointRequest `request:"mediaType=application/json"`
}

func (o OrganizationsServersSitesHealthcheckUpdateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersSitesHealthcheckUpdateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersSitesHealthcheckUpdateRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersSitesHealthcheckUpdateRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersSitesHealthcheckUpdateRequest) GetSite() int64 {
	if o == nil {
		return 0
	}
	return o.Site
}

func (o *OrganizationsServersSitesHealthcheckUpdateRequest) GetBody() *components.UpdateHealthcheckEndpointRequest {
	if o == nil {
		return nil
	}
	return o.Body
}

type OrganizationsServersSitesHealthcheckUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *OrganizationsServersSitesHealthcheckUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
