// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersScheduledJobsShowRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The job ID
	Job int64 `pathParam:"style=simple,explode=false,name=job"`
}

func (o *OrganizationsServersScheduledJobsShowRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersScheduledJobsShowRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersScheduledJobsShowRequest) GetJob() int64 {
	if o == nil {
		return 0
	}
	return o.Job
}

// OrganizationsServersScheduledJobsShowResponseBody - `JobResource`
type OrganizationsServersScheduledJobsShowResponseBody struct {
	Data components.JobResource `json:"data"`
}

func (o *OrganizationsServersScheduledJobsShowResponseBody) GetData() components.JobResource {
	if o == nil {
		return components.JobResource{}
	}
	return o.Data
}

type OrganizationsServersScheduledJobsShowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// `JobResource`
	Object *OrganizationsServersScheduledJobsShowResponseBody
}

func (o OrganizationsServersScheduledJobsShowResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersScheduledJobsShowResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersScheduledJobsShowResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersScheduledJobsShowResponse) GetObject() *OrganizationsServersScheduledJobsShowResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
