// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersPhpCliVersionShowRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
}

func (o *OrganizationsServersPhpCliVersionShowRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersPhpCliVersionShowRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

// OrganizationsServersPhpCliVersionShowResponseBody - `PhpVersionResource`
type OrganizationsServersPhpCliVersionShowResponseBody struct {
	Data components.PhpVersionResource `json:"data"`
}

func (o *OrganizationsServersPhpCliVersionShowResponseBody) GetData() components.PhpVersionResource {
	if o == nil {
		return components.PhpVersionResource{}
	}
	return o.Data
}

type OrganizationsServersPhpCliVersionShowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// `PhpVersionResource`
	Object *OrganizationsServersPhpCliVersionShowResponseBody
}

func (o OrganizationsServersPhpCliVersionShowResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersPhpCliVersionShowResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersPhpCliVersionShowResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersPhpCliVersionShowResponse) GetObject() *OrganizationsServersPhpCliVersionShowResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
