// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
)

type OrganizationsServersServicesMysqlActionsStoreRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64                                `pathParam:"style=simple,explode=false,name=server"`
	Body   components.MysqlServiceActionRequest `request:"mediaType=application/json"`
}

func (o *OrganizationsServersServicesMysqlActionsStoreRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersServicesMysqlActionsStoreRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersServicesMysqlActionsStoreRequest) GetBody() components.MysqlServiceActionRequest {
	if o == nil {
		return components.MysqlServiceActionRequest{}
	}
	return o.Body
}

type OrganizationsServersServicesMysqlActionsStoreResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *OrganizationsServersServicesMysqlActionsStoreResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
