// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersFirewallRulesShowRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The rule ID
	Rule int64 `pathParam:"style=simple,explode=false,name=rule"`
}

func (o *OrganizationsServersFirewallRulesShowRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersFirewallRulesShowRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersFirewallRulesShowRequest) GetRule() int64 {
	if o == nil {
		return 0
	}
	return o.Rule
}

// OrganizationsServersFirewallRulesShowResponseBody - `RuleResource`
type OrganizationsServersFirewallRulesShowResponseBody struct {
	Data components.RuleResource `json:"data"`
}

func (o *OrganizationsServersFirewallRulesShowResponseBody) GetData() components.RuleResource {
	if o == nil {
		return components.RuleResource{}
	}
	return o.Data
}

type OrganizationsServersFirewallRulesShowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// `RuleResource`
	Object *OrganizationsServersFirewallRulesShowResponseBody
}

func (o OrganizationsServersFirewallRulesShowResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersFirewallRulesShowResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersFirewallRulesShowResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersFirewallRulesShowResponse) GetObject() *OrganizationsServersFirewallRulesShowResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
