// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersSitesIndexRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// Available sorts are `name`, `created_at`, `updated_at`. You can sort by multiple options by separating them with a comma. To sort in descending order, use `-` sign in front of the sort, for example: `-name`.
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// Available includes are `server`, `serverCount`, `serverExists`, `tags`, `tagsCount`, `tagsExists`, `latestDeployment`, `latestDeploymentCount`, `latestDeploymentExists`, `securityRules`, `securityRulesCount`, `securityRulesExists`, `redirectRules`, `redirectRulesCount`, `redirectRulesExists`. You can include multiple options by separating them with a comma.
	Include *string `queryParam:"style=form,explode=true,name=include"`
	// The number of results that will be returned per page.
	PageSize *int64 `default:"30" queryParam:"style=form,explode=true,name=page[size]"`
	// The cursor to start the pagination from.
	PageCursor *string `queryParam:"style=form,explode=true,name=page[cursor]"`
	// The name of the site.
	FilterName *string `queryParam:"style=form,explode=true,name=filter[name]"`
}

func (o OrganizationsServersSitesIndexRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersSitesIndexRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersSitesIndexRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersSitesIndexRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersSitesIndexRequest) GetSort() *string {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *OrganizationsServersSitesIndexRequest) GetInclude() *string {
	if o == nil {
		return nil
	}
	return o.Include
}

func (o *OrganizationsServersSitesIndexRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *OrganizationsServersSitesIndexRequest) GetPageCursor() *string {
	if o == nil {
		return nil
	}
	return o.PageCursor
}

func (o *OrganizationsServersSitesIndexRequest) GetFilterName() *string {
	if o == nil {
		return nil
	}
	return o.FilterName
}

type OrganizationsServersSitesIndexLinks struct {
	First *string `json:"first,omitzero"`
	Last  *string `json:"last,omitzero"`
	Prev  *string `json:"prev,omitzero"`
	Next  *string `json:"next,omitzero"`
}

func (o *OrganizationsServersSitesIndexLinks) GetFirst() *string {
	if o == nil {
		return nil
	}
	return o.First
}

func (o *OrganizationsServersSitesIndexLinks) GetLast() *string {
	if o == nil {
		return nil
	}
	return o.Last
}

func (o *OrganizationsServersSitesIndexLinks) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}

func (o *OrganizationsServersSitesIndexLinks) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

type OrganizationsServersSitesIndexMeta struct {
	// Base path for paginator generated URLs.
	Path *string `json:"path"`
	// Number of items shown per page.
	PerPage int64 `json:"per_page"`
	// The "cursor" that points to the next set of items.
	NextCursor *string `json:"next_cursor"`
	// The "cursor" that points to the previous set of items.
	PrevCursor *string `json:"prev_cursor"`
}

func (o *OrganizationsServersSitesIndexMeta) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *OrganizationsServersSitesIndexMeta) GetPerPage() int64 {
	if o == nil {
		return 0
	}
	return o.PerPage
}

func (o *OrganizationsServersSitesIndexMeta) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *OrganizationsServersSitesIndexMeta) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

type OrganizationsServersSitesIndexIncludedType string

const (
	OrganizationsServersSitesIndexIncludedTypeServers       OrganizationsServersSitesIndexIncludedType = "servers"
	OrganizationsServersSitesIndexIncludedTypeTags          OrganizationsServersSitesIndexIncludedType = "tags"
	OrganizationsServersSitesIndexIncludedTypeDeployments   OrganizationsServersSitesIndexIncludedType = "deployments"
	OrganizationsServersSitesIndexIncludedTypeSecurityRules OrganizationsServersSitesIndexIncludedType = "securityRules"
	OrganizationsServersSitesIndexIncludedTypeRedirectRules OrganizationsServersSitesIndexIncludedType = "redirect-rules"
	OrganizationsServersSitesIndexIncludedTypeUnknown       OrganizationsServersSitesIndexIncludedType = "UNKNOWN"
)

type OrganizationsServersSitesIndexIncluded struct {
	ServerResource       *components.ServerResource       `queryParam:"inline" union:"member"`
	TagResource          *components.TagResource          `queryParam:"inline" union:"member"`
	DeploymentResource   *components.DeploymentResource   `queryParam:"inline" union:"member"`
	SecurityRuleResource *components.SecurityRuleResource `queryParam:"inline" union:"member"`
	RedirectRuleResource *components.RedirectRuleResource `queryParam:"inline" union:"member"`
	UnknownRaw           json.RawMessage                  `json:"-" union:"unknown"`

	Type OrganizationsServersSitesIndexIncludedType
}

func CreateOrganizationsServersSitesIndexIncludedServers(servers components.ServerResource) OrganizationsServersSitesIndexIncluded {
	typ := OrganizationsServersSitesIndexIncludedTypeServers

	typStr := components.ServerResourceType(typ)
	servers.Type = typStr

	return OrganizationsServersSitesIndexIncluded{
		ServerResource: &servers,
		Type:           typ,
	}
}

func CreateOrganizationsServersSitesIndexIncludedTags(tags components.TagResource) OrganizationsServersSitesIndexIncluded {
	typ := OrganizationsServersSitesIndexIncludedTypeTags

	typStr := components.TagResourceType(typ)
	tags.Type = typStr

	return OrganizationsServersSitesIndexIncluded{
		TagResource: &tags,
		Type:        typ,
	}
}

func CreateOrganizationsServersSitesIndexIncludedDeployments(deployments components.DeploymentResource) OrganizationsServersSitesIndexIncluded {
	typ := OrganizationsServersSitesIndexIncludedTypeDeployments

	typStr := components.DeploymentResourceType(typ)
	deployments.Type = typStr

	return OrganizationsServersSitesIndexIncluded{
		DeploymentResource: &deployments,
		Type:               typ,
	}
}

func CreateOrganizationsServersSitesIndexIncludedSecurityRules(securityRules components.SecurityRuleResource) OrganizationsServersSitesIndexIncluded {
	typ := OrganizationsServersSitesIndexIncludedTypeSecurityRules

	typStr := components.SecurityRuleResourceType(typ)
	securityRules.Type = typStr

	return OrganizationsServersSitesIndexIncluded{
		SecurityRuleResource: &securityRules,
		Type:                 typ,
	}
}

func CreateOrganizationsServersSitesIndexIncludedRedirectRules(redirectRules components.RedirectRuleResource) OrganizationsServersSitesIndexIncluded {
	typ := OrganizationsServersSitesIndexIncludedTypeRedirectRules

	typStr := components.RedirectRuleResourceType(typ)
	redirectRules.Type = typStr

	return OrganizationsServersSitesIndexIncluded{
		RedirectRuleResource: &redirectRules,
		Type:                 typ,
	}
}

func CreateOrganizationsServersSitesIndexIncludedUnknown(raw json.RawMessage) OrganizationsServersSitesIndexIncluded {
	return OrganizationsServersSitesIndexIncluded{
		UnknownRaw: raw,
		Type:       OrganizationsServersSitesIndexIncludedTypeUnknown,
	}
}

func (u OrganizationsServersSitesIndexIncluded) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u OrganizationsServersSitesIndexIncluded) IsUnknown() bool {
	return u.Type == OrganizationsServersSitesIndexIncludedTypeUnknown
}

func (u *OrganizationsServersSitesIndexIncluded) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = OrganizationsServersSitesIndexIncluded{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OrganizationsServersSitesIndexIncludedTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OrganizationsServersSitesIndexIncludedTypeUnknown
		return nil
	}

	switch dis.Type {
	case "servers":
		serverResource := new(components.ServerResource)
		if err := utils.UnmarshalJSON(data, &serverResource, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == servers) type components.ServerResource within OrganizationsServersSitesIndexIncluded: %w", string(data), err)
		}

		u.ServerResource = serverResource
		u.Type = OrganizationsServersSitesIndexIncludedTypeServers
		return nil
	case "tags":
		tagResource := new(components.TagResource)
		if err := utils.UnmarshalJSON(data, &tagResource, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == tags) type components.TagResource within OrganizationsServersSitesIndexIncluded: %w", string(data), err)
		}

		u.TagResource = tagResource
		u.Type = OrganizationsServersSitesIndexIncludedTypeTags
		return nil
	case "deployments":
		deploymentResource := new(components.DeploymentResource)
		if err := utils.UnmarshalJSON(data, &deploymentResource, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == deployments) type components.DeploymentResource within OrganizationsServersSitesIndexIncluded: %w", string(data), err)
		}

		u.DeploymentResource = deploymentResource
		u.Type = OrganizationsServersSitesIndexIncludedTypeDeployments
		return nil
	case "securityRules":
		securityRuleResource := new(components.SecurityRuleResource)
		if err := utils.UnmarshalJSON(data, &securityRuleResource, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == securityRules) type components.SecurityRuleResource within OrganizationsServersSitesIndexIncluded: %w", string(data), err)
		}

		u.SecurityRuleResource = securityRuleResource
		u.Type = OrganizationsServersSitesIndexIncludedTypeSecurityRules
		return nil
	case "redirect-rules":
		redirectRuleResource := new(components.RedirectRuleResource)
		if err := utils.UnmarshalJSON(data, &redirectRuleResource, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == redirect-rules) type components.RedirectRuleResource within OrganizationsServersSitesIndexIncluded: %w", string(data), err)
		}

		u.RedirectRuleResource = redirectRuleResource
		u.Type = OrganizationsServersSitesIndexIncludedTypeRedirectRules
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OrganizationsServersSitesIndexIncludedTypeUnknown
		return nil
	}

}

func (u OrganizationsServersSitesIndexIncluded) MarshalJSON() ([]byte, error) {
	if u.ServerResource != nil {
		return utils.MarshalJSON(u.ServerResource, "", true)
	}

	if u.TagResource != nil {
		return utils.MarshalJSON(u.TagResource, "", true)
	}

	if u.DeploymentResource != nil {
		return utils.MarshalJSON(u.DeploymentResource, "", true)
	}

	if u.SecurityRuleResource != nil {
		return utils.MarshalJSON(u.SecurityRuleResource, "", true)
	}

	if u.RedirectRuleResource != nil {
		return utils.MarshalJSON(u.RedirectRuleResource, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type OrganizationsServersSitesIndexIncluded: all fields are null")
}

// OrganizationsServersSitesIndexResponseBody - Paginated set of `SiteResource`
type OrganizationsServersSitesIndexResponseBody struct {
	Data     []components.SiteResource                `json:"data"`
	Links    OrganizationsServersSitesIndexLinks      `json:"links"`
	Meta     OrganizationsServersSitesIndexMeta       `json:"meta"`
	Included []OrganizationsServersSitesIndexIncluded `json:"included,omitzero"`
}

func (o OrganizationsServersSitesIndexResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersSitesIndexResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersSitesIndexResponseBody) GetData() []components.SiteResource {
	if o == nil {
		return []components.SiteResource{}
	}
	return o.Data
}

func (o *OrganizationsServersSitesIndexResponseBody) GetLinks() OrganizationsServersSitesIndexLinks {
	if o == nil {
		return OrganizationsServersSitesIndexLinks{}
	}
	return o.Links
}

func (o *OrganizationsServersSitesIndexResponseBody) GetMeta() OrganizationsServersSitesIndexMeta {
	if o == nil {
		return OrganizationsServersSitesIndexMeta{}
	}
	return o.Meta
}

func (o *OrganizationsServersSitesIndexResponseBody) GetIncluded() []OrganizationsServersSitesIndexIncluded {
	if o == nil {
		return nil
	}
	return o.Included
}

type OrganizationsServersSitesIndexResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated set of `SiteResource`
	Object *OrganizationsServersSitesIndexResponseBody
}

func (o OrganizationsServersSitesIndexResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersSitesIndexResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersSitesIndexResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersSitesIndexResponse) GetObject() *OrganizationsServersSitesIndexResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
