// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
)

type OrganizationsServersFirewallRulesDestroyRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The rule ID
	Rule int64 `pathParam:"style=simple,explode=false,name=rule"`
}

func (o *OrganizationsServersFirewallRulesDestroyRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersFirewallRulesDestroyRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersFirewallRulesDestroyRequest) GetRule() int64 {
	if o == nil {
		return 0
	}
	return o.Rule
}

type OrganizationsServersFirewallRulesDestroyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *OrganizationsServersFirewallRulesDestroyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
