// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
)

type OrganizationsServersSitesIntegrationsLaravelMaintenanceDestroyRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The site ID
	Site int64 `pathParam:"style=simple,explode=false,name=site"`
}

func (o *OrganizationsServersSitesIntegrationsLaravelMaintenanceDestroyRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersSitesIntegrationsLaravelMaintenanceDestroyRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersSitesIntegrationsLaravelMaintenanceDestroyRequest) GetSite() int64 {
	if o == nil {
		return 0
	}
	return o.Site
}

type OrganizationsServersSitesIntegrationsLaravelMaintenanceDestroyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *OrganizationsServersSitesIntegrationsLaravelMaintenanceDestroyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
