// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersScheduledJobsIndexRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// Available sorts are `created_at`, `updated_at`, `status`. You can sort by multiple options by separating them with a comma. To sort in descending order, use `-` sign in front of the sort, for example: `-created_at`.
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// The number of results that will be returned per page.
	PageSize *int64 `default:"30" queryParam:"style=form,explode=true,name=page[size]"`
	// The cursor to start the pagination from.
	PageCursor   *string `queryParam:"style=form,explode=true,name=page[cursor]"`
	FilterStatus *string `queryParam:"style=form,explode=true,name=filter[status]"`
	FilterUser   *string `queryParam:"style=form,explode=true,name=filter[user]"`
}

func (o OrganizationsServersScheduledJobsIndexRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersScheduledJobsIndexRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersScheduledJobsIndexRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersScheduledJobsIndexRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersScheduledJobsIndexRequest) GetSort() *string {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *OrganizationsServersScheduledJobsIndexRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *OrganizationsServersScheduledJobsIndexRequest) GetPageCursor() *string {
	if o == nil {
		return nil
	}
	return o.PageCursor
}

func (o *OrganizationsServersScheduledJobsIndexRequest) GetFilterStatus() *string {
	if o == nil {
		return nil
	}
	return o.FilterStatus
}

func (o *OrganizationsServersScheduledJobsIndexRequest) GetFilterUser() *string {
	if o == nil {
		return nil
	}
	return o.FilterUser
}

type OrganizationsServersScheduledJobsIndexLinks struct {
	First *string `json:"first,omitzero"`
	Last  *string `json:"last,omitzero"`
	Prev  *string `json:"prev,omitzero"`
	Next  *string `json:"next,omitzero"`
}

func (o *OrganizationsServersScheduledJobsIndexLinks) GetFirst() *string {
	if o == nil {
		return nil
	}
	return o.First
}

func (o *OrganizationsServersScheduledJobsIndexLinks) GetLast() *string {
	if o == nil {
		return nil
	}
	return o.Last
}

func (o *OrganizationsServersScheduledJobsIndexLinks) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}

func (o *OrganizationsServersScheduledJobsIndexLinks) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

type OrganizationsServersScheduledJobsIndexMeta struct {
	// Base path for paginator generated URLs.
	Path *string `json:"path"`
	// Number of items shown per page.
	PerPage int64 `json:"per_page"`
	// The "cursor" that points to the next set of items.
	NextCursor *string `json:"next_cursor"`
	// The "cursor" that points to the previous set of items.
	PrevCursor *string `json:"prev_cursor"`
}

func (o *OrganizationsServersScheduledJobsIndexMeta) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *OrganizationsServersScheduledJobsIndexMeta) GetPerPage() int64 {
	if o == nil {
		return 0
	}
	return o.PerPage
}

func (o *OrganizationsServersScheduledJobsIndexMeta) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *OrganizationsServersScheduledJobsIndexMeta) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}

// OrganizationsServersScheduledJobsIndexResponseBody - Paginated set of `JobResource`
type OrganizationsServersScheduledJobsIndexResponseBody struct {
	Data  []components.JobResource                    `json:"data"`
	Links OrganizationsServersScheduledJobsIndexLinks `json:"links"`
	Meta  OrganizationsServersScheduledJobsIndexMeta  `json:"meta"`
}

func (o *OrganizationsServersScheduledJobsIndexResponseBody) GetData() []components.JobResource {
	if o == nil {
		return []components.JobResource{}
	}
	return o.Data
}

func (o *OrganizationsServersScheduledJobsIndexResponseBody) GetLinks() OrganizationsServersScheduledJobsIndexLinks {
	if o == nil {
		return OrganizationsServersScheduledJobsIndexLinks{}
	}
	return o.Links
}

func (o *OrganizationsServersScheduledJobsIndexResponseBody) GetMeta() OrganizationsServersScheduledJobsIndexMeta {
	if o == nil {
		return OrganizationsServersScheduledJobsIndexMeta{}
	}
	return o.Meta
}

type OrganizationsServersScheduledJobsIndexResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated set of `JobResource`
	Object *OrganizationsServersScheduledJobsIndexResponseBody
}

func (o OrganizationsServersScheduledJobsIndexResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersScheduledJobsIndexResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersScheduledJobsIndexResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersScheduledJobsIndexResponse) GetObject() *OrganizationsServersScheduledJobsIndexResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
