// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersSitesCertificatesIndexRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The site ID
	Site int64 `pathParam:"style=simple,explode=false,name=site"`
}

func (o *OrganizationsServersSitesCertificatesIndexRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersSitesCertificatesIndexRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersSitesCertificatesIndexRequest) GetSite() int64 {
	if o == nil {
		return 0
	}
	return o.Site
}

// OrganizationsServersSitesCertificatesIndexResponseBody - Array of `CertificateResource`
type OrganizationsServersSitesCertificatesIndexResponseBody struct {
	Data []components.CertificateResource `json:"data"`
}

func (o *OrganizationsServersSitesCertificatesIndexResponseBody) GetData() []components.CertificateResource {
	if o == nil {
		return []components.CertificateResource{}
	}
	return o.Data
}

type OrganizationsServersSitesCertificatesIndexResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Array of `CertificateResource`
	Object *OrganizationsServersSitesCertificatesIndexResponseBody
}

func (o OrganizationsServersSitesCertificatesIndexResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersSitesCertificatesIndexResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersSitesCertificatesIndexResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersSitesCertificatesIndexResponse) GetObject() *OrganizationsServersSitesCertificatesIndexResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
