// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersSitesComposerCredentialsIndexRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The site ID
	Site int64 `pathParam:"style=simple,explode=false,name=site"`
}

func (o *OrganizationsServersSitesComposerCredentialsIndexRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersSitesComposerCredentialsIndexRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersSitesComposerCredentialsIndexRequest) GetSite() int64 {
	if o == nil {
		return 0
	}
	return o.Site
}

type OrganizationsServersSitesComposerCredentialsIndexLinks struct {
	First *string `json:"first,omitzero"`
	Last  *string `json:"last,omitzero"`
	Prev  *string `json:"prev,omitzero"`
	Next  *string `json:"next,omitzero"`
}

func (o *OrganizationsServersSitesComposerCredentialsIndexLinks) GetFirst() *string {
	if o == nil {
		return nil
	}
	return o.First
}

func (o *OrganizationsServersSitesComposerCredentialsIndexLinks) GetLast() *string {
	if o == nil {
		return nil
	}
	return o.Last
}

func (o *OrganizationsServersSitesComposerCredentialsIndexLinks) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}

func (o *OrganizationsServersSitesComposerCredentialsIndexLinks) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

type OrganizationsServersSitesComposerCredentialsIndexMeta struct {
	CurrentPage int64  `json:"current_page"`
	From        *int64 `json:"from"`
	// Base path for paginator generated URLs.
	Path *string `json:"path"`
	// Number of items shown per page.
	PerPage int64 `json:"per_page"`
	// Number of the last item in the slice.
	To *int64 `json:"to"`
}

func (o *OrganizationsServersSitesComposerCredentialsIndexMeta) GetCurrentPage() int64 {
	if o == nil {
		return 0
	}
	return o.CurrentPage
}

func (o *OrganizationsServersSitesComposerCredentialsIndexMeta) GetFrom() *int64 {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *OrganizationsServersSitesComposerCredentialsIndexMeta) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *OrganizationsServersSitesComposerCredentialsIndexMeta) GetPerPage() int64 {
	if o == nil {
		return 0
	}
	return o.PerPage
}

func (o *OrganizationsServersSitesComposerCredentialsIndexMeta) GetTo() *int64 {
	if o == nil {
		return nil
	}
	return o.To
}

// OrganizationsServersSitesComposerCredentialsIndexResponseBody - Paginated set of `ComposerCredentialResource`
type OrganizationsServersSitesComposerCredentialsIndexResponseBody struct {
	Data  []components.ComposerCredentialResource                `json:"data"`
	Links OrganizationsServersSitesComposerCredentialsIndexLinks `json:"links"`
	Meta  OrganizationsServersSitesComposerCredentialsIndexMeta  `json:"meta"`
}

func (o *OrganizationsServersSitesComposerCredentialsIndexResponseBody) GetData() []components.ComposerCredentialResource {
	if o == nil {
		return []components.ComposerCredentialResource{}
	}
	return o.Data
}

func (o *OrganizationsServersSitesComposerCredentialsIndexResponseBody) GetLinks() OrganizationsServersSitesComposerCredentialsIndexLinks {
	if o == nil {
		return OrganizationsServersSitesComposerCredentialsIndexLinks{}
	}
	return o.Links
}

func (o *OrganizationsServersSitesComposerCredentialsIndexResponseBody) GetMeta() OrganizationsServersSitesComposerCredentialsIndexMeta {
	if o == nil {
		return OrganizationsServersSitesComposerCredentialsIndexMeta{}
	}
	return o.Meta
}

type OrganizationsServersSitesComposerCredentialsIndexResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated set of `ComposerCredentialResource`
	Object *OrganizationsServersSitesComposerCredentialsIndexResponseBody
}

func (o OrganizationsServersSitesComposerCredentialsIndexResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersSitesComposerCredentialsIndexResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersSitesComposerCredentialsIndexResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersSitesComposerCredentialsIndexResponse) GetObject() *OrganizationsServersSitesComposerCredentialsIndexResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
