// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersSitesIntegrationsLaravelSchedulerStoreRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The site ID
	Site int64 `pathParam:"style=simple,explode=false,name=site"`
}

func (o *OrganizationsServersSitesIntegrationsLaravelSchedulerStoreRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersSitesIntegrationsLaravelSchedulerStoreRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersSitesIntegrationsLaravelSchedulerStoreRequest) GetSite() int64 {
	if o == nil {
		return 0
	}
	return o.Site
}

type OrganizationsServersSitesIntegrationsLaravelSchedulerStoreResponseBody struct {
}

type OrganizationsServersSitesIntegrationsLaravelSchedulerStoreResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *OrganizationsServersSitesIntegrationsLaravelSchedulerStoreResponseBody
}

func (o OrganizationsServersSitesIntegrationsLaravelSchedulerStoreResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersSitesIntegrationsLaravelSchedulerStoreResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersSitesIntegrationsLaravelSchedulerStoreResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersSitesIntegrationsLaravelSchedulerStoreResponse) GetObject() *OrganizationsServersSitesIntegrationsLaravelSchedulerStoreResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
