// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
)

type OrganizationsServersDatabaseBackupsStoreRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64                                       `pathParam:"style=simple,explode=false,name=server"`
	Body   components.CreateBackupConfigurationRequest `request:"mediaType=application/json"`
}

func (o *OrganizationsServersDatabaseBackupsStoreRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersDatabaseBackupsStoreRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersDatabaseBackupsStoreRequest) GetBody() components.CreateBackupConfigurationRequest {
	if o == nil {
		return components.CreateBackupConfigurationRequest{}
	}
	return o.Body
}

type OrganizationsServersDatabaseBackupsStoreResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *OrganizationsServersDatabaseBackupsStoreResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
