// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
)

type OrganizationsServersSitesIntegrationsLaravelMaintenanceStoreRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The site ID
	Site int64                                   `pathParam:"style=simple,explode=false,name=site"`
	Body components.EnableMaintenanceModeRequest `request:"mediaType=application/json"`
}

func (o *OrganizationsServersSitesIntegrationsLaravelMaintenanceStoreRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersSitesIntegrationsLaravelMaintenanceStoreRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersSitesIntegrationsLaravelMaintenanceStoreRequest) GetSite() int64 {
	if o == nil {
		return 0
	}
	return o.Site
}

func (o *OrganizationsServersSitesIntegrationsLaravelMaintenanceStoreRequest) GetBody() components.EnableMaintenanceModeRequest {
	if o == nil {
		return components.EnableMaintenanceModeRequest{}
	}
	return o.Body
}

type OrganizationsServersSitesIntegrationsLaravelMaintenanceStoreResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *OrganizationsServersSitesIntegrationsLaravelMaintenanceStoreResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
