// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersSitesCommandsShowRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The site ID
	Site int64 `pathParam:"style=simple,explode=false,name=site"`
	// The command ID
	Command int64 `pathParam:"style=simple,explode=false,name=command"`
}

func (o *OrganizationsServersSitesCommandsShowRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersSitesCommandsShowRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersSitesCommandsShowRequest) GetSite() int64 {
	if o == nil {
		return 0
	}
	return o.Site
}

func (o *OrganizationsServersSitesCommandsShowRequest) GetCommand() int64 {
	if o == nil {
		return 0
	}
	return o.Command
}

// OrganizationsServersSitesCommandsShowResponseBody - `CommandResource`
type OrganizationsServersSitesCommandsShowResponseBody struct {
	Data     components.CommandResource `json:"data"`
	Included []components.UserResource  `json:"included,omitzero"`
}

func (o OrganizationsServersSitesCommandsShowResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersSitesCommandsShowResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersSitesCommandsShowResponseBody) GetData() components.CommandResource {
	if o == nil {
		return components.CommandResource{}
	}
	return o.Data
}

func (o *OrganizationsServersSitesCommandsShowResponseBody) GetIncluded() []components.UserResource {
	if o == nil {
		return nil
	}
	return o.Included
}

type OrganizationsServersSitesCommandsShowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// `CommandResource`
	Object *OrganizationsServersSitesCommandsShowResponseBody
}

func (o OrganizationsServersSitesCommandsShowResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersSitesCommandsShowResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersSitesCommandsShowResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersSitesCommandsShowResponse) GetObject() *OrganizationsServersSitesCommandsShowResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
