// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsTeamsInvitesShowRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The team ID
	Team int64 `pathParam:"style=simple,explode=false,name=team"`
	// The invitation ID
	Invitation int64 `pathParam:"style=simple,explode=false,name=invitation"`
}

func (o *OrganizationsTeamsInvitesShowRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsTeamsInvitesShowRequest) GetTeam() int64 {
	if o == nil {
		return 0
	}
	return o.Team
}

func (o *OrganizationsTeamsInvitesShowRequest) GetInvitation() int64 {
	if o == nil {
		return 0
	}
	return o.Invitation
}

type OrganizationsTeamsInvitesShowIncludedType string

const (
	OrganizationsTeamsInvitesShowIncludedTypePredefinedRoles OrganizationsTeamsInvitesShowIncludedType = "predefinedRoles"
	OrganizationsTeamsInvitesShowIncludedTypeTeams           OrganizationsTeamsInvitesShowIncludedType = "teams"
	OrganizationsTeamsInvitesShowIncludedTypeOrganizations   OrganizationsTeamsInvitesShowIncludedType = "organizations"
	OrganizationsTeamsInvitesShowIncludedTypeUnknown         OrganizationsTeamsInvitesShowIncludedType = "UNKNOWN"
)

type OrganizationsTeamsInvitesShowIncluded struct {
	RoleResource         *components.RoleResource         `queryParam:"inline" union:"member"`
	TeamResource         *components.TeamResource         `queryParam:"inline" union:"member"`
	OrganizationResource *components.OrganizationResource `queryParam:"inline" union:"member"`
	UnknownRaw           json.RawMessage                  `json:"-" union:"unknown"`

	Type OrganizationsTeamsInvitesShowIncludedType
}

func CreateOrganizationsTeamsInvitesShowIncludedPredefinedRoles(predefinedRoles components.RoleResource) OrganizationsTeamsInvitesShowIncluded {
	typ := OrganizationsTeamsInvitesShowIncludedTypePredefinedRoles

	typStr := components.RoleResourceType(typ)
	predefinedRoles.Type = typStr

	return OrganizationsTeamsInvitesShowIncluded{
		RoleResource: &predefinedRoles,
		Type:         typ,
	}
}

func CreateOrganizationsTeamsInvitesShowIncludedTeams(teams components.TeamResource) OrganizationsTeamsInvitesShowIncluded {
	typ := OrganizationsTeamsInvitesShowIncludedTypeTeams

	typStr := components.TeamResourceType(typ)
	teams.Type = typStr

	return OrganizationsTeamsInvitesShowIncluded{
		TeamResource: &teams,
		Type:         typ,
	}
}

func CreateOrganizationsTeamsInvitesShowIncludedOrganizations(organizations components.OrganizationResource) OrganizationsTeamsInvitesShowIncluded {
	typ := OrganizationsTeamsInvitesShowIncludedTypeOrganizations

	typStr := components.OrganizationResourceType(typ)
	organizations.Type = typStr

	return OrganizationsTeamsInvitesShowIncluded{
		OrganizationResource: &organizations,
		Type:                 typ,
	}
}

func CreateOrganizationsTeamsInvitesShowIncludedUnknown(raw json.RawMessage) OrganizationsTeamsInvitesShowIncluded {
	return OrganizationsTeamsInvitesShowIncluded{
		UnknownRaw: raw,
		Type:       OrganizationsTeamsInvitesShowIncludedTypeUnknown,
	}
}

func (u OrganizationsTeamsInvitesShowIncluded) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u OrganizationsTeamsInvitesShowIncluded) IsUnknown() bool {
	return u.Type == OrganizationsTeamsInvitesShowIncludedTypeUnknown
}

func (u *OrganizationsTeamsInvitesShowIncluded) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OrganizationsTeamsInvitesShowIncludedTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OrganizationsTeamsInvitesShowIncludedTypeUnknown
		return nil
	}

	switch dis.Type {
	case "predefinedRoles":
		roleResource := new(components.RoleResource)
		if err := utils.UnmarshalJSON(data, &roleResource, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == predefinedRoles) type components.RoleResource within OrganizationsTeamsInvitesShowIncluded: %w", string(data), err)
		}

		u.RoleResource = roleResource
		u.Type = OrganizationsTeamsInvitesShowIncludedTypePredefinedRoles
		return nil
	case "teams":
		teamResource := new(components.TeamResource)
		if err := utils.UnmarshalJSON(data, &teamResource, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == teams) type components.TeamResource within OrganizationsTeamsInvitesShowIncluded: %w", string(data), err)
		}

		u.TeamResource = teamResource
		u.Type = OrganizationsTeamsInvitesShowIncludedTypeTeams
		return nil
	case "organizations":
		organizationResource := new(components.OrganizationResource)
		if err := utils.UnmarshalJSON(data, &organizationResource, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == organizations) type components.OrganizationResource within OrganizationsTeamsInvitesShowIncluded: %w", string(data), err)
		}

		u.OrganizationResource = organizationResource
		u.Type = OrganizationsTeamsInvitesShowIncludedTypeOrganizations
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OrganizationsTeamsInvitesShowIncludedTypeUnknown
		return nil
	}

}

func (u OrganizationsTeamsInvitesShowIncluded) MarshalJSON() ([]byte, error) {
	if u.RoleResource != nil {
		return utils.MarshalJSON(u.RoleResource, "", true)
	}

	if u.TeamResource != nil {
		return utils.MarshalJSON(u.TeamResource, "", true)
	}

	if u.OrganizationResource != nil {
		return utils.MarshalJSON(u.OrganizationResource, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type OrganizationsTeamsInvitesShowIncluded: all fields are null")
}

// OrganizationsTeamsInvitesShowResponseBody - `TeamInvitationResource`
type OrganizationsTeamsInvitesShowResponseBody struct {
	Data     components.TeamInvitationResource       `json:"data"`
	Included []OrganizationsTeamsInvitesShowIncluded `json:"included,omitzero"`
}

func (o OrganizationsTeamsInvitesShowResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsTeamsInvitesShowResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsTeamsInvitesShowResponseBody) GetData() components.TeamInvitationResource {
	if o == nil {
		return components.TeamInvitationResource{}
	}
	return o.Data
}

func (o *OrganizationsTeamsInvitesShowResponseBody) GetIncluded() []OrganizationsTeamsInvitesShowIncluded {
	if o == nil {
		return nil
	}
	return o.Included
}

type OrganizationsTeamsInvitesShowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// `TeamInvitationResource`
	Object *OrganizationsTeamsInvitesShowResponseBody
}

func (o OrganizationsTeamsInvitesShowResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsTeamsInvitesShowResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsTeamsInvitesShowResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsTeamsInvitesShowResponse) GetObject() *OrganizationsTeamsInvitesShowResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
