// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersDatabaseBackupsShowRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The backup configuration ID
	BackupConfiguration int64 `pathParam:"style=simple,explode=false,name=backupConfiguration"`
}

func (o *OrganizationsServersDatabaseBackupsShowRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersDatabaseBackupsShowRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersDatabaseBackupsShowRequest) GetBackupConfiguration() int64 {
	if o == nil {
		return 0
	}
	return o.BackupConfiguration
}

// OrganizationsServersDatabaseBackupsShowResponseBody - `BackupConfigurationResource`
type OrganizationsServersDatabaseBackupsShowResponseBody struct {
	Data components.BackupConfigurationResource `json:"data"`
}

func (o *OrganizationsServersDatabaseBackupsShowResponseBody) GetData() components.BackupConfigurationResource {
	if o == nil {
		return components.BackupConfigurationResource{}
	}
	return o.Data
}

type OrganizationsServersDatabaseBackupsShowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// `BackupConfigurationResource`
	Object *OrganizationsServersDatabaseBackupsShowResponseBody
}

func (o OrganizationsServersDatabaseBackupsShowResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersDatabaseBackupsShowResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersDatabaseBackupsShowResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersDatabaseBackupsShowResponse) GetObject() *OrganizationsServersDatabaseBackupsShowResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
