// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
)

type OrganizationsServersSitesCommandsStoreRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The site ID
	Site int64                            `pathParam:"style=simple,explode=false,name=site"`
	Body components.RunSiteCommandRequest `request:"mediaType=application/json"`
}

func (o *OrganizationsServersSitesCommandsStoreRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersSitesCommandsStoreRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersSitesCommandsStoreRequest) GetSite() int64 {
	if o == nil {
		return 0
	}
	return o.Site
}

func (o *OrganizationsServersSitesCommandsStoreRequest) GetBody() components.RunSiteCommandRequest {
	if o == nil {
		return components.RunSiteCommandRequest{}
	}
	return o.Body
}

type OrganizationsServersSitesCommandsStoreResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *OrganizationsServersSitesCommandsStoreResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
