// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type OrganizationsServersSitesDomainsCertificatesActiveRequest struct {
	// The organization slug
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The server ID
	Server int64 `pathParam:"style=simple,explode=false,name=server"`
	// The site ID
	Site int64 `pathParam:"style=simple,explode=false,name=site"`
	// The domain record ID
	DomainRecord int64 `pathParam:"style=simple,explode=false,name=domainRecord"`
}

func (o *OrganizationsServersSitesDomainsCertificatesActiveRequest) GetOrganization() string {
	if o == nil {
		return ""
	}
	return o.Organization
}

func (o *OrganizationsServersSitesDomainsCertificatesActiveRequest) GetServer() int64 {
	if o == nil {
		return 0
	}
	return o.Server
}

func (o *OrganizationsServersSitesDomainsCertificatesActiveRequest) GetSite() int64 {
	if o == nil {
		return 0
	}
	return o.Site
}

func (o *OrganizationsServersSitesDomainsCertificatesActiveRequest) GetDomainRecord() int64 {
	if o == nil {
		return 0
	}
	return o.DomainRecord
}

// OrganizationsServersSitesDomainsCertificatesActiveResponseBody - `CertificateResource`
type OrganizationsServersSitesDomainsCertificatesActiveResponseBody struct {
	Data components.CertificateResource `json:"data"`
}

func (o *OrganizationsServersSitesDomainsCertificatesActiveResponseBody) GetData() components.CertificateResource {
	if o == nil {
		return components.CertificateResource{}
	}
	return o.Data
}

type OrganizationsServersSitesDomainsCertificatesActiveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// `CertificateResource`
	Object *OrganizationsServersSitesDomainsCertificatesActiveResponseBody
}

func (o OrganizationsServersSitesDomainsCertificatesActiveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationsServersSitesDomainsCertificatesActiveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationsServersSitesDomainsCertificatesActiveResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationsServersSitesDomainsCertificatesActiveResponse) GetObject() *OrganizationsServersSitesDomainsCertificatesActiveResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
