// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package databases

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersDatabaseSchemasDestroyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server-param", Shorthand: "s", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "database", FieldPath: "Database", Kind: flagutil.FlagKindInt64, Required: true, Description: "The database ID [required]"},
}

// initOrganizationsServersDatabaseSchemasDestroyCmd initializes the organizations-servers-database-schemas-destroy command.
func initOrganizationsServersDatabaseSchemasDestroyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-database-schemas-destroy",
		Short:   "Delete database schema",
		Long:    "Remove a database schema from the server.\n\nProcessing mode: <small><code>async</code></small>",
		Example: "  forge databases organizations-servers-database-schemas-destroy --organization <value> --server-param 299051 --database 838304",
		Args:    cobra.NoArgs,
		RunE:    runOrganizationsServersDatabaseSchemasDestroyCmd,
		Aliases: []string{"osdsd"},
		Annotations: map[string]string{
			"speakeasy_operation": "organizations.servers.database.schemas.destroy",
		},
	}
	flagutil.RegisterFlags(cmd, organizationsServersDatabaseSchemasDestroyCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersDatabaseSchemasDestroyRequest](organizationsServersDatabaseSchemasDestroyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-database-schemas-destroy: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersDatabaseSchemasDestroyCmd executes the organizations-servers-database-schemas-destroy command.
func runOrganizationsServersDatabaseSchemasDestroyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersDatabaseSchemasDestroyRequest](cmd, organizationsServersDatabaseSchemasDestroyCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd, "Oauth2")
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Databases.OrganizationsServersDatabaseSchemasDestroy(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
