// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package databases

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersDatabaseUsersShowCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server-param", Shorthand: "s", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "database-user", FieldPath: "DatabaseUser", Kind: flagutil.FlagKindInt64, Required: true, Description: "The database user ID [required]"},
}

// initOrganizationsServersDatabaseUsersShowCmd initializes the organizations-servers-database-users-show command.
func initOrganizationsServersDatabaseUsersShowCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-database-users-show",
		Short:   "Get database user",
		Long:    "Get a specific database user associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge databases organizations-servers-database-users-show --organization <value> --server-param 501442 --database-user 400928",
		Args:    cobra.NoArgs,
		RunE:    runOrganizationsServersDatabaseUsersShowCmd,
		Aliases: []string{"osdus"},
		Annotations: map[string]string{
			"speakeasy_operation": "organizations.servers.database.users.show",
		},
	}
	flagutil.RegisterFlags(cmd, organizationsServersDatabaseUsersShowCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersDatabaseUsersShowRequest](organizationsServersDatabaseUsersShowCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-database-users-show: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersDatabaseUsersShowCmd executes the organizations-servers-database-users-show command.
func runOrganizationsServersDatabaseUsersShowCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersDatabaseUsersShowRequest](cmd, organizationsServersDatabaseUsersShowCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd, "Oauth2")
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Databases.OrganizationsServersDatabaseUsersShow(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
