// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package databases

import (
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitDatabasesRoot(parent *cobra.Command) error {
	var DatabasesCmd = &cobra.Command{
		Use:   "databases",
		Short: "Operations for databases",
		Long:  "Operations for databases",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initOrganizationsServersDatabaseSchemasIndexCmd(DatabasesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseSchemasStoreCmd(DatabasesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseSchemasShowCmd(DatabasesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseSchemasDestroyCmd(DatabasesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseSchemasSynchronizationsStoreCmd(DatabasesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseUsersIndexCmd(DatabasesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseUsersStoreCmd(DatabasesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseUsersShowCmd(DatabasesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseUsersUpdateCmd(DatabasesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseUsersDestroyCmd(DatabasesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabasePasswordUpdateCmd(DatabasesCmd); err != nil {
		return err
	}

	parent.AddCommand(DatabasesCmd)
	return nil
}
