// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package recipes

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsRecipesUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "recipe", Shorthand: "r", FieldPath: "Recipe", Kind: flagutil.FlagKindInt64, Required: true, Description: "The recipe ID [required]"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "user", Shorthand: "u", FieldPath: "Body.User", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"root", "forge"}, Description: "options: root, forge"},
	{FlagName: "script", Shorthand: "s", FieldPath: "Body.Script", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
}

// initOrganizationsRecipesUpdateCmd initializes the organizations-recipes-update command.
func initOrganizationsRecipesUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-recipes-update",
		Short:   "Update recipe",
		Long:    "Update a recipe in the organization.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge recipes organizations-recipes-update --organization <value> --recipe 650833",
		RunE:    runOrganizationsRecipesUpdateCmd,
		Aliases: []string{"oru"},
	}
	flagutil.RegisterFlags(cmd, organizationsRecipesUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsRecipesUpdateRequest](organizationsRecipesUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-recipes-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsRecipesUpdateCmd executes the organizations-recipes-update command.
func runOrganizationsRecipesUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsRecipesUpdateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsRecipesUpdateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsRecipesUpdateRequest](cmd, organizationsRecipesUpdateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Recipes.OrganizationsRecipesUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
