// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package recipes

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsTeamsRecipesDestroyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "team", Shorthand: "t", FieldPath: "Team", Kind: flagutil.FlagKindInt64, Required: true, Description: "The team ID [required]"},
	{FlagName: "recipe", Shorthand: "r", FieldPath: "Recipe", Kind: flagutil.FlagKindInt64, Required: true, Description: "The recipe ID [required]"},
}

// initOrganizationsTeamsRecipesDestroyCmd initializes the organizations-teams-recipes-destroy command.
func initOrganizationsTeamsRecipesDestroyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-teams-recipes-destroy",
		Short:   "Delete a recipe share",
		Long:    "Unshare a recipe with a team.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge recipes organizations-teams-recipes-destroy --organization <value> --team 244831 --recipe 104618",
		RunE:    runOrganizationsTeamsRecipesDestroyCmd,
		Aliases: []string{"otrd"},
	}
	flagutil.RegisterFlags(cmd, organizationsTeamsRecipesDestroyCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsTeamsRecipesDestroyRequest](organizationsTeamsRecipesDestroyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-teams-recipes-destroy: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsTeamsRecipesDestroyCmd executes the organizations-teams-recipes-destroy command.
func runOrganizationsTeamsRecipesDestroyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsTeamsRecipesDestroyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsTeamsRecipesDestroyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsTeamsRecipesDestroyRequest](cmd, organizationsTeamsRecipesDestroyCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Recipes.OrganizationsTeamsRecipesDestroy(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
