// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package servers

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersServicesNginxActionsStoreCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", Shorthand: "s", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "action", Shorthand: "a", FieldPath: "Body.Action", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"reboot", "stop"}, Description: "| |\n|---|\n| `reboot` <br/> Reboot the Nginx service |\n| `stop` <br/> Stop the Nginx service | (options: reboot, stop) [required]"},
}

// initOrganizationsServersServicesNginxActionsStoreCmd initializes the organizations-servers-services-nginx-actions-store command.
func initOrganizationsServersServicesNginxActionsStoreCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-services-nginx-actions-store",
		Short:   "Perform Nginx action",
		Long:    "Run an action on the Nginx service.\n\nProcessing mode: <small><code>async</code></small>",
		Example: "  forge servers organizations-servers-services-nginx-actions-store --organization <value> --server 622394 --action stop",
		RunE:    runOrganizationsServersServicesNginxActionsStoreCmd,
		Aliases: []string{"ossnas"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersServicesNginxActionsStoreCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersServicesNginxActionsStoreRequest](organizationsServersServicesNginxActionsStoreCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-services-nginx-actions-store: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersServicesNginxActionsStoreCmd executes the organizations-servers-services-nginx-actions-store command.
func runOrganizationsServersServicesNginxActionsStoreCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersServicesNginxActionsStoreCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersServicesNginxActionsStoreCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersServicesNginxActionsStoreRequest](cmd, organizationsServersServicesNginxActionsStoreCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Servers.OrganizationsServersServicesNginxActionsStore(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
