// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package servers

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsTeamsServersDestroyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "team", Shorthand: "t", FieldPath: "Team", Kind: flagutil.FlagKindInt64, Required: true, Description: "The team ID [required]"},
	{FlagName: "server", Shorthand: "s", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
}

// initOrganizationsTeamsServersDestroyCmd initializes the organizations-teams-servers-destroy command.
func initOrganizationsTeamsServersDestroyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-teams-servers-destroy",
		Short:   "Delete a server share",
		Long:    "Unshare a server with a team.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge servers organizations-teams-servers-destroy --organization <value> --team 765744 --server 850006",
		RunE:    runOrganizationsTeamsServersDestroyCmd,
		Aliases: []string{"otsd"},
	}
	flagutil.RegisterFlags(cmd, organizationsTeamsServersDestroyCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsTeamsServersDestroyRequest](organizationsTeamsServersDestroyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-teams-servers-destroy: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsTeamsServersDestroyCmd executes the organizations-teams-servers-destroy command.
func runOrganizationsTeamsServersDestroyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsTeamsServersDestroyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsTeamsServersDestroyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsTeamsServersDestroyRequest](cmd, organizationsTeamsServersDestroyCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Servers.OrganizationsTeamsServersDestroy(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
