// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package servers

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersPhpOpcacheDestroyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", Shorthand: "s", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
}

// initOrganizationsServersPhpOpcacheDestroyCmd initializes the organizations-servers-php-opcache-destroy command.
func initOrganizationsServersPhpOpcacheDestroyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-php-opcache-destroy",
		Short:   "Delete PHP OPcache config",
		Long:    "Disable PHP OPcache for the server.\n\nProcessing mode: <small><code>async</code></small>",
		Example: "  forge servers organizations-servers-php-opcache-destroy --organization <value> --server 994940",
		RunE:    runOrganizationsServersPhpOpcacheDestroyCmd,
		Aliases: []string{"ospod"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersPhpOpcacheDestroyCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersPhpOpcacheDestroyRequest](organizationsServersPhpOpcacheDestroyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-php-opcache-destroy: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersPhpOpcacheDestroyCmd executes the organizations-servers-php-opcache-destroy command.
func runOrganizationsServersPhpOpcacheDestroyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersPhpOpcacheDestroyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersPhpOpcacheDestroyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersPhpOpcacheDestroyRequest](cmd, organizationsServersPhpOpcacheDestroyCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Servers.OrganizationsServersPhpOpcacheDestroy(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
