// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package servers

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersPhpVersionsUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", Shorthand: "s", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "php-version", Shorthand: "p", FieldPath: "PhpVersion", Kind: flagutil.FlagKindInt64, Required: true, Description: "The php version ID [required]"},
}

// initOrganizationsServersPhpVersionsUpdateCmd initializes the organizations-servers-php-versions-update command.
func initOrganizationsServersPhpVersionsUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-php-versions-update",
		Short:   "Update installed PHP version",
		Long:    "Update PHP version to the latest patch release\n\nProcessing mode: <small><code>async</code></small>",
		Example: "  forge servers organizations-servers-php-versions-update --organization <value> --server 52671 --php-version 524678",
		RunE:    runOrganizationsServersPhpVersionsUpdateCmd,
		Aliases: []string{"ospvu"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersPhpVersionsUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersPhpVersionsUpdateRequest](organizationsServersPhpVersionsUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-php-versions-update: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersPhpVersionsUpdateCmd executes the organizations-servers-php-versions-update command.
func runOrganizationsServersPhpVersionsUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersPhpVersionsUpdateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersPhpVersionsUpdateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersPhpVersionsUpdateRequest](cmd, organizationsServersPhpVersionsUpdateCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Servers.OrganizationsServersPhpVersionsUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
