// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package deployments

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesDeployKeyShowCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server-param", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
}

// initOrganizationsServersSitesDeployKeyShowCmd initializes the organizations-servers-sites-deploy-key-show command.
func initOrganizationsServersSitesDeployKeyShowCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-deploy-key-show",
		Short:   "Get deploy key",
		Long:    "Get the deploy key for the site.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge deployments organizations-servers-sites-deploy-key-show --organization <value> --server-param 195039 --site 780340",
		Args:    cobra.NoArgs,
		RunE:    runOrganizationsServersSitesDeployKeyShowCmd,
		Aliases: []string{"ossdks"},
		Annotations: map[string]string{
			"speakeasy_operation": "organizations.servers.sites.deploy-key.show",
		},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesDeployKeyShowCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesDeployKeyShowRequest](organizationsServersSitesDeployKeyShowCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-deploy-key-show: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesDeployKeyShowCmd executes the organizations-servers-sites-deploy-key-show command.
func runOrganizationsServersSitesDeployKeyShowCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesDeployKeyShowRequest](cmd, organizationsServersSitesDeployKeyShowCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd, "Oauth2")
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Deployments.OrganizationsServersSitesDeployKeyShow(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
