// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package deployments

import (
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitDeploymentsRoot(parent *cobra.Command) error {
	var DeploymentsCmd = &cobra.Command{
		Use:   "deployments",
		Short: "Operations for deployments",
		Long:  "Operations for deployments",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initOrganizationsServersSitesWebhooksIndexCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesWebhooksStoreCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesWebhooksShowCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesWebhooksDestroyCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeploymentsIndexCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeploymentsStoreCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeploymentsStatusShowCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeploymentsStatusDestroyCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeploymentsScriptShowCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeploymentsScriptUpdateCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeploymentsDeployHookShowCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeploymentsDeployHookUpdateCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeploymentsPushToDeployStoreCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeploymentsPushToDeployDestroyCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeploymentsShowCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeploymentsLogShowCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeployKeyShowCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeployKeyStoreCmd(DeploymentsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesDeployKeyDestroyCmd(DeploymentsCmd); err != nil {
		return err
	}

	parent.AddCommand(DeploymentsCmd)
	return nil
}
