// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package commands

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesCommandsShowCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
	{FlagName: "command", Shorthand: "c", FieldPath: "Command", Kind: flagutil.FlagKindInt64, Required: true, Description: "The command ID [required]"},
}

// initOrganizationsServersSitesCommandsShowCmd initializes the organizations-servers-sites-commands-show command.
func initOrganizationsServersSitesCommandsShowCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-commands-show",
		Short:   "Get command",
		Long:    "Get a specific command run.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge commands organizations-servers-sites-commands-show --organization <value> --server 847807 --site 473827 --command 838200",
		RunE:    runOrganizationsServersSitesCommandsShowCmd,
		Aliases: []string{"osscs"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesCommandsShowCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesCommandsShowRequest](organizationsServersSitesCommandsShowCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-commands-show: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesCommandsShowCmd executes the organizations-servers-sites-commands-show command.
func runOrganizationsServersSitesCommandsShowCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersSitesCommandsShowCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersSitesCommandsShowCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesCommandsShowRequest](cmd, organizationsServersSitesCommandsShowCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Commands.OrganizationsServersSitesCommandsShow(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
