// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package roles

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsRolesShowCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "role", Shorthand: "r", FieldPath: "Role", Kind: flagutil.FlagKindInt64, Required: true, Description: "The role ID [required]"},
}

// initOrganizationsRolesShowCmd initializes the organizations-roles-show command.
func initOrganizationsRolesShowCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-roles-show",
		Short:   "Get role",
		Long:    "Show a specific role for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge roles organizations-roles-show --organization <value> --role 651219",
		RunE:    runOrganizationsRolesShowCmd,
		Aliases: []string{"ors"},
	}
	flagutil.RegisterFlags(cmd, organizationsRolesShowCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsRolesShowRequest](organizationsRolesShowCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-roles-show: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsRolesShowCmd executes the organizations-roles-show command.
func runOrganizationsRolesShowCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsRolesShowCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsRolesShowCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsRolesShowRequest](cmd, organizationsRolesShowCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Roles.OrganizationsRolesShow(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
