// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package roles

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var permissionsShowCmdMeta = []flagutil.FlagMeta{
	{FlagName: "permission", Shorthand: "p", FieldPath: "Permission", Kind: flagutil.FlagKindInt64, Required: true, Description: "The permission ID [required]"},
}

// initPermissionsShowCmd initializes the permissions-show command.
func initPermissionsShowCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "permissions-show",
		Short:   "Get permission",
		Long:    "Show a specific permission.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge roles permissions-show --permission 234972",
		RunE:    runPermissionsShowCmd,
		Aliases: []string{"ps"},
	}
	flagutil.RegisterFlags(cmd, permissionsShowCmdMeta)
	if err := flagutil.ValidateMeta[operations.PermissionsShowRequest](permissionsShowCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for permissions-show: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runPermissionsShowCmd executes the permissions-show command.
func runPermissionsShowCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, permissionsShowCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, permissionsShowCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PermissionsShowRequest](cmd, permissionsShowCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Roles.PermissionsShow(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
