// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/components"
)

// ValidationException - Validation error
type ValidationException struct {
	// Errors overview.
	Message string `json:"message"`
	// A detailed description of each field that failed validation.
	Errors   map[string][]string     `json:"errors"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ValidationException{}

func (e *ValidationException) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
