// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package redirectrules

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesRedirectRulesIndexCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
	{FlagName: "sort", FieldPath: "Sort", Kind: flagutil.FlagKindString, Optional: true, Description: "Available sorts are `created_at`, `updated_at`. You can sort by multiple options by separating them with a comma. To sort in descending order, use `-` sign in front of the sort, for example: `-created_at`."},
	{FlagName: "page-size", FieldPath: "PageSize", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 30, Description: "The number of results that will be returned per page."},
	{FlagName: "page-cursor", FieldPath: "PageCursor", Kind: flagutil.FlagKindString, Optional: true, Description: "The cursor to start the pagination from."},
	{FlagName: "filter-from", FieldPath: "FilterFrom", Kind: flagutil.FlagKindString, Optional: true, Description: "The source URL path for the redirect rule."},
	{FlagName: "filter-to", FieldPath: "FilterTo", Kind: flagutil.FlagKindString, Optional: true, Description: "The destination URL path for the redirect rule."},
	{FlagName: "filter-type", FieldPath: "FilterType", Kind: flagutil.FlagKindString, Optional: true, Description: "The type of the redirect rule."},
	{FlagName: "filter-status", FieldPath: "FilterStatus", Kind: flagutil.FlagKindString, Optional: true, Description: "The status of the redirect rule."},
}

// initOrganizationsServersSitesRedirectRulesIndexCmd initializes the organizations-servers-sites-redirect-rules-index command.
func initOrganizationsServersSitesRedirectRulesIndexCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-redirect-rules-index",
		Short:   "List site redirect rules",
		Long:    "List all redirect rules associated with the site.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge redirect-rules organizations-servers-sites-redirect-rules-index --organization <value> --server 910445 --site 739152",
		RunE:    runOrganizationsServersSitesRedirectRulesIndexCmd,
		Aliases: []string{"ossrri"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesRedirectRulesIndexCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesRedirectRulesIndexRequest](organizationsServersSitesRedirectRulesIndexCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-redirect-rules-index: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesRedirectRulesIndexCmd executes the organizations-servers-sites-redirect-rules-index command.
func runOrganizationsServersSitesRedirectRulesIndexCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersSitesRedirectRulesIndexCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersSitesRedirectRulesIndexCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesRedirectRulesIndexRequest](cmd, organizationsServersSitesRedirectRulesIndexCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.RedirectRules.OrganizationsServersSitesRedirectRulesIndex(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
