// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package backups

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersDatabaseBackupsInstancesIndexCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "backup-configuration", Shorthand: "b", FieldPath: "BackupConfiguration", Kind: flagutil.FlagKindInt64, Required: true, Description: "The backup configuration ID [required]"},
	{FlagName: "sort", FieldPath: "Sort", Kind: flagutil.FlagKindString, Optional: true, Description: "Available sorts are `created_at`, `updated_at`. You can sort by multiple options by separating them with a comma. To sort in descending order, use `-` sign in front of the sort, for example: `-created_at`."},
	{FlagName: "page-size", FieldPath: "PageSize", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 30, Description: "The number of results that will be returned per page."},
	{FlagName: "page-cursor", FieldPath: "PageCursor", Kind: flagutil.FlagKindString, Optional: true, Description: "The cursor to start the pagination from."},
	{FlagName: "filter-status", Shorthand: "f", FieldPath: "FilterStatus", Kind: flagutil.FlagKindString, Optional: true, Description: "The status of the backup."},
}

// initOrganizationsServersDatabaseBackupsInstancesIndexCmd initializes the organizations-servers-database-backups-instances-index command.
func initOrganizationsServersDatabaseBackupsInstancesIndexCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-database-backups-instances-index",
		Short:   "List backups",
		Long:    "List all backup instances for the backup configuration.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge backups organizations-servers-database-backups-instances-index --organization <value> --server 953308 --backup-configuration 109127",
		RunE:    runOrganizationsServersDatabaseBackupsInstancesIndexCmd,
		Aliases: []string{"osdbii"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersDatabaseBackupsInstancesIndexCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersDatabaseBackupsInstancesIndexRequest](organizationsServersDatabaseBackupsInstancesIndexCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-database-backups-instances-index: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersDatabaseBackupsInstancesIndexCmd executes the organizations-servers-database-backups-instances-index command.
func runOrganizationsServersDatabaseBackupsInstancesIndexCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersDatabaseBackupsInstancesIndexCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersDatabaseBackupsInstancesIndexCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersDatabaseBackupsInstancesIndexRequest](cmd, organizationsServersDatabaseBackupsInstancesIndexCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Backups.OrganizationsServersDatabaseBackupsInstancesIndex(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
