// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package backups

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersDatabaseBackupsInstancesRestoresStoreCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server-param", Shorthand: "s", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "backup-configuration", FieldPath: "BackupConfiguration", Kind: flagutil.FlagKindInt64, Required: true, Description: "The backup configuration ID [required]"},
	{FlagName: "backup", FieldPath: "Backup", Kind: flagutil.FlagKindInt64, Required: true, Description: "The backup ID [required]"},
	{FlagName: "database-id", FieldPath: "Body.DatabaseID", Kind: flagutil.FlagKindInt64, Required: true, Description: "[required]"},
}

// initOrganizationsServersDatabaseBackupsInstancesRestoresStoreCmd initializes the organizations-servers-database-backups-instances-restores-store command.
func initOrganizationsServersDatabaseBackupsInstancesRestoresStoreCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-database-backups-instances-restores-store",
		Short:   "Create a database restore from backup",
		Long:    "Restore the given database from the backup.\n\nProcessing mode: <small><code>async</code></small>",
		Example: "  forge backups organizations-servers-database-backups-instances-restores-store --organization <value> --server-param 309141 --backup-configuration 680142 --backup 860527 --database-id 662663",
		Args:    cobra.NoArgs,
		RunE:    runOrganizationsServersDatabaseBackupsInstancesRestoresStoreCmd,
		Aliases: []string{"osdbirs"},
		Annotations: map[string]string{
			"speakeasy_operation": "organizations.servers.database.backups.instances.restores.store",
		},
	}
	flagutil.RegisterFlags(cmd, organizationsServersDatabaseBackupsInstancesRestoresStoreCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersDatabaseBackupsInstancesRestoresStoreRequest](organizationsServersDatabaseBackupsInstancesRestoresStoreCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-database-backups-instances-restores-store: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, organizationsServersDatabaseBackupsInstancesRestoresStoreCmdMeta, "Body", "body"); err != nil {
		return fmt.Errorf("annotate body fields for organizations-servers-database-backups-instances-restores-store: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersDatabaseBackupsInstancesRestoresStoreCmd executes the organizations-servers-database-backups-instances-restores-store command.
func runOrganizationsServersDatabaseBackupsInstancesRestoresStoreCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "organizations.servers.database.backups.instances.restores.store")
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersDatabaseBackupsInstancesRestoresStoreRequest](cmd, organizationsServersDatabaseBackupsInstancesRestoresStoreCmdMeta, "Body", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd, "Oauth2")
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Backups.OrganizationsServersDatabaseBackupsInstancesRestoresStore(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
