// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package backups

import (
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitBackupsRoot(parent *cobra.Command) error {
	var BackupsCmd = &cobra.Command{
		Use:   "backups",
		Short: "Operations for backups",
		Long:  "Operations for backups",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initOrganizationsServersDatabaseBackupsIndexCmd(BackupsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseBackupsStoreCmd(BackupsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseBackupsShowCmd(BackupsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseBackupsUpdateCmd(BackupsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseBackupsDestroyCmd(BackupsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseBackupsInstancesIndexCmd(BackupsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseBackupsInstancesStoreCmd(BackupsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseBackupsInstancesShowCmd(BackupsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseBackupsInstancesDestroyCmd(BackupsCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersDatabaseBackupsInstancesRestoresStoreCmd(BackupsCmd); err != nil {
		return err
	}

	parent.AddCommand(BackupsCmd)
	return nil
}
