// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sites

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesComposerCredentialsIndexCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server-param", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
}

// initOrganizationsServersSitesComposerCredentialsIndexCmd initializes the organizations-servers-sites-composer-credentials-index command.
func initOrganizationsServersSitesComposerCredentialsIndexCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-composer-credentials-index",
		Short:   "Get composer credentials for the site",
		Long:    "Processing mode: <small><code>sync</code></small>",
		Example: "  forge sites organizations-servers-sites-composer-credentials-index --organization <value> --server-param 103955 --site 105911",
		Args:    cobra.NoArgs,
		RunE:    runOrganizationsServersSitesComposerCredentialsIndexCmd,
		Aliases: []string{"osscci"},
		Annotations: map[string]string{
			"speakeasy_operation": "organizations.servers.sites.composer.credentials.index",
		},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesComposerCredentialsIndexCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesComposerCredentialsIndexRequest](organizationsServersSitesComposerCredentialsIndexCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-composer-credentials-index: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesComposerCredentialsIndexCmd executes the organizations-servers-sites-composer-credentials-index command.
func runOrganizationsServersSitesComposerCredentialsIndexCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesComposerCredentialsIndexRequest](cmd, organizationsServersSitesComposerCredentialsIndexCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd, "Oauth2")
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sites.OrganizationsServersSitesComposerCredentialsIndex(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
