// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sites

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesDomainsCertificatesDestroyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server-param", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
	{FlagName: "domain-record", FieldPath: "DomainRecord", Kind: flagutil.FlagKindInt64, Required: true, Description: "The domain record ID [required]"},
	{FlagName: "certificate", Shorthand: "c", FieldPath: "Certificate", Kind: flagutil.FlagKindInt64, Required: true, Description: "The certificate ID [required]"},
}

// initOrganizationsServersSitesDomainsCertificatesDestroyCmd initializes the organizations-servers-sites-domains-certificates-destroy command.
func initOrganizationsServersSitesDomainsCertificatesDestroyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-domains-certificates-destroy",
		Short:   "Delete domain certificate",
		Long:    "Delete a specific certificate for a given domain.\n\nProcessing mode: <small><code>async</code></small>",
		Example: "  forge sites organizations-servers-sites-domains-certificates-destroy --organization <value> --server-param 555092 --site 811902 --domain-record 664430 --certificate 108812",
		Args:    cobra.NoArgs,
		RunE:    runOrganizationsServersSitesDomainsCertificatesDestroyCmd,
		Aliases: []string{"ossdcd"},
		Annotations: map[string]string{
			"speakeasy_operation": "organizations.servers.sites.domains.certificates.destroy",
		},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesDomainsCertificatesDestroyCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesDomainsCertificatesDestroyRequest](organizationsServersSitesDomainsCertificatesDestroyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-domains-certificates-destroy: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesDomainsCertificatesDestroyCmd executes the organizations-servers-sites-domains-certificates-destroy command.
func runOrganizationsServersSitesDomainsCertificatesDestroyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesDomainsCertificatesDestroyRequest](cmd, organizationsServersSitesDomainsCertificatesDestroyCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd, "Oauth2")
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sites.OrganizationsServersSitesDomainsCertificatesDestroy(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
