// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sites

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesHeartbeatsUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
	{FlagName: "heartbeat", FieldPath: "Heartbeat", Kind: flagutil.FlagKindInt64, Required: true, Description: "The heartbeat ID [required]"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Required: true, Description: "The name of the heartbeat. [required]"},
	{FlagName: "grace-period", Shorthand: "g", FieldPath: "Body.GracePeriod", Kind: flagutil.FlagKindIntEnum, Required: true, EnumValues: []string{"1", "2", "5", "10", "30", "60"}, Description: "options: 1, 2, 5, 10, 30, 60 [required]"},
	{FlagName: "frequency", Shorthand: "f", FieldPath: "Body.Frequency", Kind: flagutil.FlagKindIntEnum, Required: true, EnumValues: []string{"1", "5", "10", "30", "60", "1440", "10080", "312480", "-1"}, Description: "options: 1, 5, 10, 30, 60, 1440, 10080, 312480, -1 [required]"},
	{FlagName: "custom-frequency", Shorthand: "c", FieldPath: "Body.CustomFrequency", Kind: flagutil.FlagKindString, Optional: true, Description: "A cron expression representing the custom frequency at which the client is expected to send a ping, if the frequency is set to -1."},
}

// initOrganizationsServersSitesHeartbeatsUpdateCmd initializes the organizations-servers-sites-heartbeats-update command.
func initOrganizationsServersSitesHeartbeatsUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-heartbeats-update",
		Short:   "Update heartbeat",
		Long:    "Update a specific heartbeat for the site.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge sites organizations-servers-sites-heartbeats-update --organization <value> --server 12665 --site 354926 --heartbeat 178389 --name My Heartbeat",
		RunE:    runOrganizationsServersSitesHeartbeatsUpdateCmd,
		Aliases: []string{"osshup"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesHeartbeatsUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesHeartbeatsUpdateRequest](organizationsServersSitesHeartbeatsUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-heartbeats-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesHeartbeatsUpdateCmd executes the organizations-servers-sites-heartbeats-update command.
func runOrganizationsServersSitesHeartbeatsUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersSitesHeartbeatsUpdateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersSitesHeartbeatsUpdateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesHeartbeatsUpdateRequest](cmd, organizationsServersSitesHeartbeatsUpdateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sites.OrganizationsServersSitesHeartbeatsUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
