// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sites

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesLogsNginxErrorShowCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
}

// initOrganizationsServersSitesLogsNginxErrorShowCmd initializes the organizations-servers-sites-logs-nginx-error-show command.
func initOrganizationsServersSitesLogsNginxErrorShowCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-logs-nginx-error-show",
		Short:   "Get Nginx error log content",
		Long:    "Processing mode: <small><code>sync</code></small>",
		Example: "  forge sites organizations-servers-sites-logs-nginx-error-show --organization <value> --server 492438 --site 474113",
		RunE:    runOrganizationsServersSitesLogsNginxErrorShowCmd,
		Aliases: []string{"osslnes"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesLogsNginxErrorShowCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesLogsNginxErrorShowRequest](organizationsServersSitesLogsNginxErrorShowCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-logs-nginx-error-show: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesLogsNginxErrorShowCmd executes the organizations-servers-sites-logs-nginx-error-show command.
func runOrganizationsServersSitesLogsNginxErrorShowCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersSitesLogsNginxErrorShowCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersSitesLogsNginxErrorShowCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesLogsNginxErrorShowRequest](cmd, organizationsServersSitesLogsNginxErrorShowCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sites.OrganizationsServersSitesLogsNginxErrorShow(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
