// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sites

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesLogsNginxErrorDestroyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server-param", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
}

// initOrganizationsServersSitesLogsNginxErrorDestroyCmd initializes the organizations-servers-sites-logs-nginx-error-destroy command.
func initOrganizationsServersSitesLogsNginxErrorDestroyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-logs-nginx-error-destroy",
		Short:   "Delete Nginx error log content",
		Long:    "Processing mode: <small><code>async</code></small>",
		Example: "  forge sites organizations-servers-sites-logs-nginx-error-destroy --organization <value> --server-param 14784 --site 620322",
		Args:    cobra.NoArgs,
		RunE:    runOrganizationsServersSitesLogsNginxErrorDestroyCmd,
		Aliases: []string{"osslned"},
		Annotations: map[string]string{
			"speakeasy_operation": "organizations.servers.sites.logs.nginx-error.destroy",
		},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesLogsNginxErrorDestroyCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesLogsNginxErrorDestroyRequest](organizationsServersSitesLogsNginxErrorDestroyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-logs-nginx-error-destroy: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesLogsNginxErrorDestroyCmd executes the organizations-servers-sites-logs-nginx-error-destroy command.
func runOrganizationsServersSitesLogsNginxErrorDestroyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesLogsNginxErrorDestroyRequest](cmd, organizationsServersSitesLogsNginxErrorDestroyCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd, "Oauth2")
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sites.OrganizationsServersSitesLogsNginxErrorDestroy(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
