// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sites

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesDomainsNginxUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
	{FlagName: "domain-record", FieldPath: "DomainRecord", Kind: flagutil.FlagKindInt64, Required: true, Description: "The domain record ID [required]"},
	{FlagName: "config-param", Shorthand: "c", FieldPath: "Body.Config", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initOrganizationsServersSitesDomainsNginxUpdateCmd initializes the organizations-servers-sites-domains-nginx-update command.
func initOrganizationsServersSitesDomainsNginxUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-domains-nginx-update",
		Short:   "Update domain Nginx configuration",
		Long:    "Processing mode: <small><code>async</code></small>",
		Example: "  forge sites organizations-servers-sites-domains-nginx-update --organization <value> --server 671030 --site 267210 --domain-record 207404 --config-param <value>",
		RunE:    runOrganizationsServersSitesDomainsNginxUpdateCmd,
		Aliases: []string{"ossdnu"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesDomainsNginxUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesDomainsNginxUpdateRequest](organizationsServersSitesDomainsNginxUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-domains-nginx-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesDomainsNginxUpdateCmd executes the organizations-servers-sites-domains-nginx-update command.
func runOrganizationsServersSitesDomainsNginxUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersSitesDomainsNginxUpdateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersSitesDomainsNginxUpdateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesDomainsNginxUpdateRequest](cmd, organizationsServersSitesDomainsNginxUpdateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sites.OrganizationsServersSitesDomainsNginxUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
