// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sites

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesLogsNginxErrorDestroyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
}

// initOrganizationsServersSitesLogsNginxErrorDestroyCmd initializes the organizations-servers-sites-logs-nginx-error-destroy command.
func initOrganizationsServersSitesLogsNginxErrorDestroyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-logs-nginx-error-destroy",
		Short:   "Delete Nginx error log content",
		Long:    "Processing mode: <small><code>async</code></small>",
		Example: "  forge sites organizations-servers-sites-logs-nginx-error-destroy --organization <value> --server 14784 --site 620322",
		RunE:    runOrganizationsServersSitesLogsNginxErrorDestroyCmd,
		Aliases: []string{"osslned"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesLogsNginxErrorDestroyCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesLogsNginxErrorDestroyRequest](organizationsServersSitesLogsNginxErrorDestroyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-logs-nginx-error-destroy: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesLogsNginxErrorDestroyCmd executes the organizations-servers-sites-logs-nginx-error-destroy command.
func runOrganizationsServersSitesLogsNginxErrorDestroyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersSitesLogsNginxErrorDestroyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersSitesLogsNginxErrorDestroyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesLogsNginxErrorDestroyRequest](cmd, organizationsServersSitesLogsNginxErrorDestroyCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sites.OrganizationsServersSitesLogsNginxErrorDestroy(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
