// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sites

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesDomainsCertificatesActionsStoreCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
	{FlagName: "domain-record", FieldPath: "DomainRecord", Kind: flagutil.FlagKindInt64, Required: true, Description: "The domain record ID [required]"},
	{FlagName: "certificate", Shorthand: "c", FieldPath: "Certificate", Kind: flagutil.FlagKindInt64, Required: true, Description: "The certificate ID [required]"},
	{FlagName: "action", Shorthand: "a", FieldPath: "Body.Action", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"enable", "disable"}, Description: "options: enable, disable [required]"},
}

// initOrganizationsServersSitesDomainsCertificatesActionsStoreCmd initializes the organizations-servers-sites-domains-certificates-actions-store command.
func initOrganizationsServersSitesDomainsCertificatesActionsStoreCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-domains-certificates-actions-store",
		Short:   "Create domain certificate action",
		Long:    "Run an action on a domain certificate, defined by the action type parameter.\n\nProcessing mode: <small><code>async</code></small>",
		Example: "  forge sites organizations-servers-sites-domains-certificates-actions-store --organization <value> --server 140818 --site 167010 --domain-record 669630 --certificate 698737",
		RunE:    runOrganizationsServersSitesDomainsCertificatesActionsStoreCmd,
		Aliases: []string{"ossdcas"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesDomainsCertificatesActionsStoreCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesDomainsCertificatesActionsStoreRequest](organizationsServersSitesDomainsCertificatesActionsStoreCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-domains-certificates-actions-store: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesDomainsCertificatesActionsStoreCmd executes the organizations-servers-sites-domains-certificates-actions-store command.
func runOrganizationsServersSitesDomainsCertificatesActionsStoreCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersSitesDomainsCertificatesActionsStoreCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersSitesDomainsCertificatesActionsStoreCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesDomainsCertificatesActionsStoreRequest](cmd, organizationsServersSitesDomainsCertificatesActionsStoreCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sites.OrganizationsServersSitesDomainsCertificatesActionsStore(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
