// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sites

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesEnvironmentUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server-param", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
	{FlagName: "environment", FieldPath: "Body.Environment", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "cache", Shorthand: "c", FieldPath: "Body.Cache", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "queues", FieldPath: "Body.Queues", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "encryption-key", FieldPath: "Body.EncryptionKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"encryption_key,omitempty"`, Description: "string value"},
}

// initOrganizationsServersSitesEnvironmentUpdateCmd initializes the organizations-servers-sites-environment-update command.
func initOrganizationsServersSitesEnvironmentUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-environment-update",
		Short:   "Update .env content",
		Long:    "Processing mode: <small><code>async</code></small>",
		Example: "  forge sites organizations-servers-sites-environment-update --organization <value> --server-param 971088 --site 188376 --environment <value>",
		Args:    cobra.NoArgs,
		RunE:    runOrganizationsServersSitesEnvironmentUpdateCmd,
		Aliases: []string{"osseu"},
		Annotations: map[string]string{
			"speakeasy_operation": "organizations.servers.sites.environment.update",
		},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesEnvironmentUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesEnvironmentUpdateRequest](organizationsServersSitesEnvironmentUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-environment-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, organizationsServersSitesEnvironmentUpdateCmdMeta, "Body", "body"); err != nil {
		return fmt.Errorf("annotate body fields for organizations-servers-sites-environment-update: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesEnvironmentUpdateCmd executes the organizations-servers-sites-environment-update command.
func runOrganizationsServersSitesEnvironmentUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "organizations.servers.sites.environment.update")
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesEnvironmentUpdateRequest](cmd, organizationsServersSitesEnvironmentUpdateCmdMeta, "Body", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd, "Oauth2")
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sites.OrganizationsServersSitesEnvironmentUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
