// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package scheduledjobs

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesScheduledJobsDestroyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
	{FlagName: "job", Shorthand: "j", FieldPath: "Job", Kind: flagutil.FlagKindInt64, Required: true, Description: "The job ID [required]"},
}

// initOrganizationsServersSitesScheduledJobsDestroyCmd initializes the organizations-servers-sites-scheduled-jobs-destroy command.
func initOrganizationsServersSitesScheduledJobsDestroyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-scheduled-jobs-destroy",
		Short:   "Delete site scheduled job",
		Long:    "Delete a specific scheduled job associated with the site.\n\nProcessing mode: <small><code>async</code></small>",
		Example: "  forge scheduled-jobs organizations-servers-sites-scheduled-jobs-destroy --organization <value> --server 340206 --site 705093 --job 262101",
		RunE:    runOrganizationsServersSitesScheduledJobsDestroyCmd,
		Aliases: []string{"osssjd"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesScheduledJobsDestroyCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesScheduledJobsDestroyRequest](organizationsServersSitesScheduledJobsDestroyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-scheduled-jobs-destroy: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesScheduledJobsDestroyCmd executes the organizations-servers-sites-scheduled-jobs-destroy command.
func runOrganizationsServersSitesScheduledJobsDestroyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersSitesScheduledJobsDestroyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersSitesScheduledJobsDestroyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesScheduledJobsDestroyRequest](cmd, organizationsServersSitesScheduledJobsDestroyCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.ScheduledJobs.OrganizationsServersSitesScheduledJobsDestroy(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
