// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package monitors

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersMonitorsShowCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", Shorthand: "s", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "monitor", Shorthand: "m", FieldPath: "Monitor", Kind: flagutil.FlagKindInt64, Required: true, Description: "The monitor ID [required]"},
}

// initOrganizationsServersMonitorsShowCmd initializes the organizations-servers-monitors-show command.
func initOrganizationsServersMonitorsShowCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-monitors-show",
		Short:   "Get server monitor",
		Long:    "Get a specific monitor associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge monitors organizations-servers-monitors-show --organization <value> --server 465626 --monitor 449178",
		RunE:    runOrganizationsServersMonitorsShowCmd,
		Aliases: []string{"osms"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersMonitorsShowCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersMonitorsShowRequest](organizationsServersMonitorsShowCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-monitors-show: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersMonitorsShowCmd executes the organizations-servers-monitors-show command.
func runOrganizationsServersMonitorsShowCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersMonitorsShowCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersMonitorsShowCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersMonitorsShowRequest](cmd, organizationsServersMonitorsShowCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Monitors.OrganizationsServersMonitorsShow(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
