// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package nginx

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersNginxTemplatesDestroyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", Shorthand: "s", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "nginx-template", Shorthand: "n", FieldPath: "NginxTemplate", Kind: flagutil.FlagKindInt64, Required: true, Description: "The nginx template ID [required]"},
}

// initOrganizationsServersNginxTemplatesDestroyCmd initializes the organizations-servers-nginx-templates-destroy command.
func initOrganizationsServersNginxTemplatesDestroyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-nginx-templates-destroy",
		Short:   "Delete Nginx template",
		Long:    "Delete the specified nginx template from the server.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge nginx organizations-servers-nginx-templates-destroy --organization <value> --server 251022 --nginx-template 63212",
		RunE:    runOrganizationsServersNginxTemplatesDestroyCmd,
		Aliases: []string{"osntd"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersNginxTemplatesDestroyCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersNginxTemplatesDestroyRequest](organizationsServersNginxTemplatesDestroyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-nginx-templates-destroy: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersNginxTemplatesDestroyCmd executes the organizations-servers-nginx-templates-destroy command.
func runOrganizationsServersNginxTemplatesDestroyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersNginxTemplatesDestroyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersNginxTemplatesDestroyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersNginxTemplatesDestroyRequest](cmd, organizationsServersNginxTemplatesDestroyCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Nginx.OrganizationsServersNginxTemplatesDestroy(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
