// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package nginx

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersNginxTemplatesUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server-param", Shorthand: "s", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "nginx-template", FieldPath: "NginxTemplate", Kind: flagutil.FlagKindInt64, Required: true, Description: "The nginx template ID [required]"},
	{FlagName: "name", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Required: true, Description: "The name of the nginx template. [required]"},
	{FlagName: "content", Shorthand: "c", FieldPath: "Body.Content", Kind: flagutil.FlagKindString, Required: true, Description: "The content of the nginx template. [required]"},
}

// initOrganizationsServersNginxTemplatesUpdateCmd initializes the organizations-servers-nginx-templates-update command.
func initOrganizationsServersNginxTemplatesUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-nginx-templates-update",
		Short:   "Update Nginx template",
		Long:    "Update the specified nginx template on the server.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge nginx organizations-servers-nginx-templates-update --organization <value> --server-param 910924 --nginx-template 825505 --name <value> --content <value>",
		Args:    cobra.NoArgs,
		RunE:    runOrganizationsServersNginxTemplatesUpdateCmd,
		Aliases: []string{"osntu"},
		Annotations: map[string]string{
			"speakeasy_operation": "organizations.servers.nginx.templates.update",
		},
	}
	flagutil.RegisterFlags(cmd, organizationsServersNginxTemplatesUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersNginxTemplatesUpdateRequest](organizationsServersNginxTemplatesUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-nginx-templates-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, organizationsServersNginxTemplatesUpdateCmdMeta, "Body", "body"); err != nil {
		return fmt.Errorf("annotate body fields for organizations-servers-nginx-templates-update: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersNginxTemplatesUpdateCmd executes the organizations-servers-nginx-templates-update command.
func runOrganizationsServersNginxTemplatesUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "organizations.servers.nginx.templates.update")
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersNginxTemplatesUpdateRequest](cmd, organizationsServersNginxTemplatesUpdateCmdMeta, "Body", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd, "Oauth2")
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Nginx.OrganizationsServersNginxTemplatesUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
