// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package nginx

import (
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitNginxRoot(parent *cobra.Command) error {
	var NginxCmd = &cobra.Command{
		Use:   "nginx",
		Short: "Operations for nginx",
		Long:  "Operations for nginx",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initOrganizationsServersNginxTemplatesIndexCmd(NginxCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersNginxTemplatesStoreCmd(NginxCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersNginxTemplatesShowCmd(NginxCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersNginxTemplatesUpdateCmd(NginxCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersNginxTemplatesDestroyCmd(NginxCmd); err != nil {
		return err
	}

	parent.AddCommand(NginxCmd)
	return nil
}
