// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/charmbracelet/huh"
	"github.com/charmbracelet/lipgloss"
	"github.com/mfullbrook/forge-cli/internal/config"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/spf13/cobra"
	"golang.org/x/term"
	"os"
)

// initAuthCmd registers the auth command group with login, whoami, and logout subcommands.
func initAuthCmd(parent *cobra.Command) error {
	var authCmd *cobra.Command
	for _, existing := range parent.Commands() {
		if existing.Name() == "auth" || existing.HasAlias("auth") {
			authCmd = existing
			break
		}
	}
	if authCmd == nil {
		authCmd = &cobra.Command{
			Use:   "auth",
			Short: "Manage authentication credentials",
			Long: `Manage authentication credentials for forge.

Subcommands:
  login   - Interactively configure credentials
  whoami  - Display current authentication status
  logout  - Clear all stored credentials`,
		}
		parent.AddCommand(authCmd)
	}

	addAuthSubcommand := func(sub *cobra.Command) {
		for _, existing := range authCmd.Commands() {
			if existing.Name() == sub.Name() || existing.HasAlias(sub.Name()) {
				return
			}
		}
		authCmd.AddCommand(sub)
	}

	addAuthSubcommand(&cobra.Command{
		Use:   "login",
		Short: "Interactively configure authentication credentials",
		Long: `Interactively configure authentication credentials for forge.
Secret credentials are stored in the OS keychain when available,
with a config file fallback.

All fields are optional — press Enter to skip any field you don't need.
Use the configure command for both authentication and global parameters.`,
		Args: cobra.NoArgs,
		RunE: runAuthLoginCmd,
	})

	addAuthSubcommand(&cobra.Command{
		Use:   "whoami",
		Short: "Display current authentication configuration",
		Long: `Display the currently configured settings and their sources.

Sources are shown as:
  [flag]    - Set via command line flag
  [env]     - Set via environment variable (FORGE_*)
  [keyring] - Set via OS keychain (stored by login/configure command)
  [config]  - Set via config file (~/.config/forge/config.yaml)
  [unset]   - Not configured

Credential values are masked for security.`,
		Args: cobra.NoArgs,
		RunE: runWhoamiCmd,
	})

	addAuthSubcommand(&cobra.Command{
		Use:   "logout",
		Short: "Clear all stored authentication credentials",
		Long: `Clear all stored authentication credentials from both the OS keychain and config file.

This removes all credentials previously set via auth login or configure.`,
		Args: cobra.NoArgs,
		RunE: runAuthLogoutCmd,
	})

	return nil
}

// runAuthLoginCmd executes the auth login command using huh forms.
func runAuthLoginCmd(cmd *cobra.Command, args []string) error {
	if dryRunLocalNoop(cmd, "auth login changes local credentials only (no API request); nothing was changed.") {
		return nil
	}
	cfg := config.GetConfig()
	if cfg == nil {
		cfg = &config.Config{}
	}

	keychainStored := false
	formMode := interactive.Resolve(cmd).FormMode()

	if formMode == interactive.FormOff {
		// Non-interactive: store any explicitly-set flags without prompting
		changed := false
		if f := cmd.Flags().Lookup("http"); f != nil && f.Changed {
			v, _ := cmd.Flags().GetString("http")
			if config.StoreSecret("http", v, &cfg.Security.Http) == nil {
				keychainStored = true
			}
			changed = true
		}
		if f := cmd.Flags().Lookup("oauth2"); f != nil && f.Changed {
			v, _ := cmd.Flags().GetString("oauth2")
			if config.StoreSecret("oauth2", v, &cfg.Security.Oauth2) == nil {
				keychainStored = true
			}
			changed = true
		}

		if !changed {
			return flagutil.WithCLIValidation(fmt.Errorf("no flags provided; use flags to store credentials in %s, or pass --interactive to open the form", config.GetConfigPath()))
		}
	} else {

		accessible := formMode == interactive.FormAccessible

		var selectedScheme string
		schemeSelect := huh.NewSelect[string]().
			Title("Authentication Method").
			Description("Choose which credentials to configure").
			Options(
				huh.NewOption("HTTP Bearer", "http"),
				huh.NewOption("OAuth2 Authorization", "oauth2"),
			).
			Value(&selectedScheme)

		if err := huh.NewForm(huh.NewGroup(schemeSelect)).WithAccessible(accessible).WithTheme(authFormTheme()).WithWidth(authFormWidth()).WithShowHelp(false).Run(); err != nil {
			return fmt.Errorf("auth login: %w", err)
		}

		switch selectedScheme {
		case "http":
			var authHttp string

			fields := []huh.Field{
				huh.NewInput().
					Title("HTTP Bearer").
					Description("--http").
					EchoMode(huh.EchoModePassword).
					Placeholder(maskSecret(config.GetStoredSecret("http", cfg.Security.Http))).
					Value(&authHttp),
			}

			form := huh.NewForm(huh.NewGroup(fields...)).
				WithAccessible(accessible).
				WithTheme(authFormTheme()).
				WithWidth(authFormWidth()).
				WithShowHelp(false)

			if err := form.Run(); err != nil {
				return fmt.Errorf("auth login: %w", err)
			}

			if authHttp != "" {
				if config.StoreSecret("http", authHttp, &cfg.Security.Http) == nil {
					keychainStored = true
				}
			}

		case "oauth2":
			var authOauth2 string

			fields := []huh.Field{
				huh.NewInput().
					Title("OAuth2 Authorization").
					Description("--oauth2").
					EchoMode(huh.EchoModePassword).
					Placeholder(maskSecret(config.GetStoredSecret("oauth2", cfg.Security.Oauth2))).
					Value(&authOauth2),
			}

			form := huh.NewForm(huh.NewGroup(fields...)).
				WithAccessible(accessible).
				WithTheme(authFormTheme()).
				WithWidth(authFormWidth()).
				WithShowHelp(false)

			if err := form.Run(); err != nil {
				return fmt.Errorf("auth login: %w", err)
			}

			if authOauth2 != "" {
				if config.StoreSecret("oauth2", authOauth2, &cfg.Security.Oauth2) == nil {
					keychainStored = true
				}
			}

		}

	}

	if err := config.SaveConfig(cfg); err != nil {
		return fmt.Errorf("failed to save configuration: %w", err)
	}

	out := cmd.OutOrStdout()
	if keychainStored {
		fmt.Fprintln(out, "Secret credentials stored in OS keychain")
	}
	fmt.Fprintf(out, "Configuration saved to %s\n", config.GetConfigPath())
	return nil
}

// runAuthLogoutCmd clears all stored authentication credentials.
func runAuthLogoutCmd(cmd *cobra.Command, args []string) error {
	if dryRunLocalNoop(cmd, "auth logout removes local credentials only (no API request); nothing was changed.") {
		return nil
	}
	cfg := config.GetConfig()
	if cfg == nil {
		cfg = &config.Config{}
	}

	if config.KeyringAvailable() {
		_ = config.DeleteKeyringValue("http")
	}
	cfg.Security.Http = ""
	if config.KeyringAvailable() {
		_ = config.DeleteKeyringValue("oauth2")
	}
	cfg.Security.Oauth2 = ""

	if err := config.SaveConfig(cfg); err != nil {
		return fmt.Errorf("failed to save configuration: %w", err)
	}

	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "All authentication credentials have been cleared.")
	fmt.Fprintf(out, "Configuration saved to %s\n", config.GetConfigPath())
	return nil
}

// authFormTheme builds the form theme for auth login.
func authFormTheme() *huh.Theme {
	t := *huh.ThemeBase()

	accent := lipgloss.Color("#38BDF8")
	dimmed := lipgloss.Color("#64748B")
	subtle := lipgloss.Color("#475569")
	errColor := lipgloss.Color("#F87171")
	greenColor := lipgloss.Color("#4ADE80")

	t.Focused.Base = t.Focused.Base.
		BorderLeft(true).
		BorderStyle(lipgloss.ThickBorder()).
		BorderForeground(accent).
		PaddingLeft(1)
	t.Focused.Title = t.Focused.Title.Foreground(accent).Bold(true)
	t.Focused.Description = t.Focused.Description.Foreground(dimmed).Italic(true)
	t.Focused.ErrorIndicator = t.Focused.ErrorIndicator.Foreground(errColor)
	t.Focused.ErrorMessage = t.Focused.ErrorMessage.Foreground(errColor)
	t.Focused.SelectSelector = t.Focused.SelectSelector.Foreground(accent).SetString("> ")
	t.Focused.SelectedOption = t.Focused.SelectedOption.Foreground(accent).Bold(true)
	t.Focused.SelectedPrefix = lipgloss.NewStyle().Foreground(greenColor).SetString("✓ ").Bold(true)
	t.Focused.UnselectedPrefix = lipgloss.NewStyle().SetString("  ")
	t.Focused.FocusedButton = t.Focused.FocusedButton.Background(accent).Foreground(lipgloss.Color("#FFFFFF"))
	t.Focused.BlurredButton = t.Focused.BlurredButton.Background(subtle)
	t.Focused.Next = t.Focused.FocusedButton

	t.Focused.TextInput.Cursor = t.Focused.TextInput.Cursor.Foreground(accent)
	t.Focused.TextInput.Placeholder = t.Focused.TextInput.Placeholder.Foreground(subtle).Italic(true)
	t.Focused.TextInput.Prompt = t.Focused.TextInput.Prompt.Foreground(accent)

	t.Blurred.Base = t.Blurred.Base.
		BorderLeft(true).
		BorderStyle(lipgloss.ThickBorder()).
		BorderForeground(subtle).
		PaddingLeft(1)
	t.Blurred.Title = t.Blurred.Title.Foreground(dimmed)
	t.Blurred.Description = t.Blurred.Description.Foreground(subtle).Italic(true)
	t.Blurred.TextInput.Text = t.Blurred.TextInput.Text.Foreground(dimmed)
	t.Blurred.TextInput.Placeholder = t.Blurred.TextInput.Placeholder.Foreground(subtle).Italic(true)
	t.Blurred.SelectedOption = t.Blurred.SelectedOption.Foreground(dimmed)
	t.Blurred.SelectSelector = t.Blurred.SelectSelector.Foreground(dimmed)
	t.Blurred.SelectedPrefix = lipgloss.NewStyle().Foreground(dimmed).SetString("✓ ")
	t.Blurred.UnselectedPrefix = lipgloss.NewStyle().SetString("  ")

	return &t
}

// authFormWidth returns the terminal width for sizing huh forms.
func authFormWidth() int {
	width, _, err := term.GetSize(int(os.Stdout.Fd()))
	if err != nil || width <= 0 {
		width = 80
	}
	return width
}
