// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package organizations

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServerCredentialsVpcsStoreCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "credential", Shorthand: "c", FieldPath: "Credential", Kind: flagutil.FlagKindInt64, Required: true, Description: "The credential ID [required]"},
	{FlagName: "region", Shorthand: "r", FieldPath: "Region", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initOrganizationsServerCredentialsVpcsStoreCmd initializes the organizations-server-credentials-vpcs-store command.
func initOrganizationsServerCredentialsVpcsStoreCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "server-credentials-vpcs-store",
		Short:   "Create a new VPC",
		Long:    "Create a private network for the provider.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge organizations server-credentials-vpcs-store --organization <value> --credential 822457 --region <value> --name <value>",
		RunE:    runOrganizationsServerCredentialsVpcsStoreCmd,
		Aliases: []string{"scvst"},
	}
	flagutil.RegisterFlags(cmd, organizationsServerCredentialsVpcsStoreCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServerCredentialsVpcsStoreRequest](organizationsServerCredentialsVpcsStoreCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-server-credentials-vpcs-store: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServerCredentialsVpcsStoreCmd executes the organizations-server-credentials-vpcs-store command.
func runOrganizationsServerCredentialsVpcsStoreCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServerCredentialsVpcsStoreCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServerCredentialsVpcsStoreCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServerCredentialsVpcsStoreRequest](cmd, organizationsServerCredentialsVpcsStoreCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Organizations.OrganizationsServerCredentialsVpcsStore(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
