// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package organizations

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsShowCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
}

// initOrganizationsShowCmd initializes the organizations-show command.
func initOrganizationsShowCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "show",
		Short:   "Get organization",
		Long:    "Show a specific organization for the user.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge organizations show --organization <value>",
		RunE:    runOrganizationsShowCmd,
	}
	flagutil.RegisterFlags(cmd, organizationsShowCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsShowRequest](organizationsShowCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-show: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsShowCmd executes the organizations-show command.
func runOrganizationsShowCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsShowCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsShowCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsShowRequest](cmd, organizationsShowCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Organizations.OrganizationsShow(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
