// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package organizations

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServerCredentialsVpcsIndexCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "credential", Shorthand: "c", FieldPath: "Credential", Kind: flagutil.FlagKindInt64, Required: true, Description: "The credential ID [required]"},
	{FlagName: "region", Shorthand: "r", FieldPath: "Region", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initOrganizationsServerCredentialsVpcsIndexCmd initializes the organizations-server-credentials-vpcs-index command.
func initOrganizationsServerCredentialsVpcsIndexCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "server-credentials-vpcs-index",
		Short:   "List VPCs",
		Long:    "List VPCs for the provider.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge organizations server-credentials-vpcs-index --organization <value> --credential 55726 --region <value>",
		RunE:    runOrganizationsServerCredentialsVpcsIndexCmd,
		Aliases: []string{"scvi"},
	}
	flagutil.RegisterFlags(cmd, organizationsServerCredentialsVpcsIndexCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServerCredentialsVpcsIndexRequest](organizationsServerCredentialsVpcsIndexCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-server-credentials-vpcs-index: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServerCredentialsVpcsIndexCmd executes the organizations-server-credentials-vpcs-index command.
func runOrganizationsServerCredentialsVpcsIndexCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServerCredentialsVpcsIndexCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServerCredentialsVpcsIndexCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServerCredentialsVpcsIndexRequest](cmd, organizationsServerCredentialsVpcsIndexCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Organizations.OrganizationsServerCredentialsVpcsIndex(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
