// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package servercredentials

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsTeamsServerCredentialsDestroyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "team", Shorthand: "t", FieldPath: "Team", Kind: flagutil.FlagKindInt64, Required: true, Description: "The team ID [required]"},
	{FlagName: "credential", Shorthand: "c", FieldPath: "Credential", Kind: flagutil.FlagKindInt64, Required: true, Description: "The credential ID [required]"},
}

// initOrganizationsTeamsServerCredentialsDestroyCmd initializes the organizations-teams-server-credentials-destroy command.
func initOrganizationsTeamsServerCredentialsDestroyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-teams-server-credentials-destroy",
		Short:   "Delete a server credential share",
		Long:    "Unshare a server credential with a team.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge server-credentials organizations-teams-server-credentials-destroy --organization <value> --team 543042 --credential 98202",
		RunE:    runOrganizationsTeamsServerCredentialsDestroyCmd,
		Aliases: []string{"otscd"},
	}
	flagutil.RegisterFlags(cmd, organizationsTeamsServerCredentialsDestroyCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsTeamsServerCredentialsDestroyRequest](organizationsTeamsServerCredentialsDestroyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-teams-server-credentials-destroy: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsTeamsServerCredentialsDestroyCmd executes the organizations-teams-server-credentials-destroy command.
func runOrganizationsTeamsServerCredentialsDestroyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsTeamsServerCredentialsDestroyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsTeamsServerCredentialsDestroyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsTeamsServerCredentialsDestroyRequest](cmd, organizationsTeamsServerCredentialsDestroyCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.ServerCredentials.OrganizationsTeamsServerCredentialsDestroy(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
