// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package integrations

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesIntegrationsLaravelSchedulerShowCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server-param", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
}

// initOrganizationsServersSitesIntegrationsLaravelSchedulerShowCmd initializes the organizations-servers-sites-integrations-laravel-scheduler-show command.
func initOrganizationsServersSitesIntegrationsLaravelSchedulerShowCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-integrations-laravel-scheduler-show",
		Short:   "Get Laravel Scheduler integration job",
		Long:    "Show whether Laravel Scheduler integration is enabled.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge integrations organizations-servers-sites-integrations-laravel-scheduler-show --organization <value> --server-param 402397 --site 685859",
		Args:    cobra.NoArgs,
		RunE:    runOrganizationsServersSitesIntegrationsLaravelSchedulerShowCmd,
		Aliases: []string{"ossilss"},
		Annotations: map[string]string{
			"speakeasy_operation": "organizations.servers.sites.integrations.laravel-scheduler.show",
		},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesIntegrationsLaravelSchedulerShowCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesIntegrationsLaravelSchedulerShowRequest](organizationsServersSitesIntegrationsLaravelSchedulerShowCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-integrations-laravel-scheduler-show: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesIntegrationsLaravelSchedulerShowCmd executes the organizations-servers-sites-integrations-laravel-scheduler-show command.
func runOrganizationsServersSitesIntegrationsLaravelSchedulerShowCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesIntegrationsLaravelSchedulerShowRequest](cmd, organizationsServersSitesIntegrationsLaravelSchedulerShowCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd, "Oauth2")
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Integrations.OrganizationsServersSitesIntegrationsLaravelSchedulerShow(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
