// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package integrations

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesIntegrationsOctaneShowCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
}

// initOrganizationsServersSitesIntegrationsOctaneShowCmd initializes the organizations-servers-sites-integrations-octane-show command.
func initOrganizationsServersSitesIntegrationsOctaneShowCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-integrations-octane-show",
		Short:   "Get Laravel Octane integration status",
		Long:    "Show whether Laravel Octane integration is enabled.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge integrations organizations-servers-sites-integrations-octane-show --organization <value> --server 744716 --site 737500",
		RunE:    runOrganizationsServersSitesIntegrationsOctaneShowCmd,
		Aliases: []string{"ossios"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesIntegrationsOctaneShowCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesIntegrationsOctaneShowRequest](organizationsServersSitesIntegrationsOctaneShowCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-integrations-octane-show: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesIntegrationsOctaneShowCmd executes the organizations-servers-sites-integrations-octane-show command.
func runOrganizationsServersSitesIntegrationsOctaneShowCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersSitesIntegrationsOctaneShowCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersSitesIntegrationsOctaneShowCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesIntegrationsOctaneShowRequest](cmd, organizationsServersSitesIntegrationsOctaneShowCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Integrations.OrganizationsServersSitesIntegrationsOctaneShow(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
