// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package integrations

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesIntegrationsLaravelMaintenanceDestroyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
}

// initOrganizationsServersSitesIntegrationsLaravelMaintenanceDestroyCmd initializes the organizations-servers-sites-integrations-laravel-maintenance-destroy command.
func initOrganizationsServersSitesIntegrationsLaravelMaintenanceDestroyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-integrations-laravel-maintenance-destroy",
		Short:   "Delete Laravel Maintenance integration",
		Long:    "Disable maintenance mode for the site.\n\nProcessing mode: <small><code>async</code></small>",
		Example: "  forge integrations organizations-servers-sites-integrations-laravel-maintenance-destroy --organization <value> --server 533223 --site 348988",
		RunE:    runOrganizationsServersSitesIntegrationsLaravelMaintenanceDestroyCmd,
		Aliases: []string{"ossilmd"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesIntegrationsLaravelMaintenanceDestroyCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesIntegrationsLaravelMaintenanceDestroyRequest](organizationsServersSitesIntegrationsLaravelMaintenanceDestroyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-integrations-laravel-maintenance-destroy: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesIntegrationsLaravelMaintenanceDestroyCmd executes the organizations-servers-sites-integrations-laravel-maintenance-destroy command.
func runOrganizationsServersSitesIntegrationsLaravelMaintenanceDestroyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersSitesIntegrationsLaravelMaintenanceDestroyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersSitesIntegrationsLaravelMaintenanceDestroyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesIntegrationsLaravelMaintenanceDestroyRequest](cmd, organizationsServersSitesIntegrationsLaravelMaintenanceDestroyCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Integrations.OrganizationsServersSitesIntegrationsLaravelMaintenanceDestroy(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
