// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package integrations

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesIntegrationsReverbStoreCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
	{FlagName: "host", FieldPath: "Body.Host", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "port", Shorthand: "p", FieldPath: "Body.Port", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "connections", Shorthand: "c", FieldPath: "Body.Connections", Kind: flagutil.FlagKindInt64, Required: true, Description: "[required]"},
}

// initOrganizationsServersSitesIntegrationsReverbStoreCmd initializes the organizations-servers-sites-integrations-reverb-store command.
func initOrganizationsServersSitesIntegrationsReverbStoreCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-integrations-reverb-store",
		Short:   "Create Laravel Reverb integration",
		Long:    "Processing mode: <small><code>async</code></small>",
		Example: "  forge integrations organizations-servers-sites-integrations-reverb-store --organization <value> --server 696562 --site 131111 --host trained-mentor.com --port <value>",
		RunE:    runOrganizationsServersSitesIntegrationsReverbStoreCmd,
		Aliases: []string{"ossirst"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesIntegrationsReverbStoreCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesIntegrationsReverbStoreRequest](organizationsServersSitesIntegrationsReverbStoreCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-integrations-reverb-store: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesIntegrationsReverbStoreCmd executes the organizations-servers-sites-integrations-reverb-store command.
func runOrganizationsServersSitesIntegrationsReverbStoreCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersSitesIntegrationsReverbStoreCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersSitesIntegrationsReverbStoreCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesIntegrationsReverbStoreRequest](cmd, organizationsServersSitesIntegrationsReverbStoreCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Integrations.OrganizationsServersSitesIntegrationsReverbStore(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
