workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Forge:
        inputs:
            - location: ./forge.openapi.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/kaira-ventures/dev/forge
targets:
    laravel-forge:
        target: cli
        source: Forge
