// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package backgroundprocesses

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersBackgroundProcessesStoreCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Required: true, Description: "The name of the background process. [required]"},
	{FlagName: "site-id", FieldPath: "Body.SiteID", Kind: flagutil.FlagKindInt64, Optional: true, Description: "The site to associate the background process with."},
	{FlagName: "command", Shorthand: "c", FieldPath: "Body.Command", Kind: flagutil.FlagKindString, Required: true, Description: "The command to run. [required]"},
	{FlagName: "user", Shorthand: "u", FieldPath: "Body.User", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"root", "forge"}, Description: "The user to run the background process as. (options: root, forge) [required]"},
	{FlagName: "directory", FieldPath: "Body.Directory", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"directory,omitempty"`, Description: "The directory to run the background process from."},
	{FlagName: "processes", Shorthand: "p", FieldPath: "Body.Processes", Kind: flagutil.FlagKindInt64, Required: true, Description: "The number of processes to run. [required]"},
	{FlagName: "startsecs", FieldPath: "Body.Startsecs", Kind: flagutil.FlagKindInt64, Optional: true, Description: "The number of seconds to wait before starting the process."},
	{FlagName: "stopwaitsecs", FieldPath: "Body.Stopwaitsecs", Kind: flagutil.FlagKindInt64, Optional: true, Description: "The number of seconds to wait before stopping the process."},
	{FlagName: "stopsignal", FieldPath: "Body.Stopsignal", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"stopsignal,omitempty"`, Description: "The signal to send to stop the process."},
}

// initOrganizationsServersBackgroundProcessesStoreCmd initializes the organizations-servers-background-processes-store command.
func initOrganizationsServersBackgroundProcessesStoreCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-background-processes-store",
		Short:   "Create background process",
		Long:    "Create a new background process from a template.\n\nProcessing mode: <small><code>async</code></small>",
		Example: "  forge background-processes organizations-servers-background-processes-store --organization <value> --server 627041 --name Custom command runner --command php artisan custom:command --user forge",
		RunE:    runOrganizationsServersBackgroundProcessesStoreCmd,
		Aliases: []string{"osbpst"},
	}
	flagutil.RegisterFlags(cmd, organizationsServersBackgroundProcessesStoreCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersBackgroundProcessesStoreRequest](organizationsServersBackgroundProcessesStoreCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-background-processes-store: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersBackgroundProcessesStoreCmd executes the organizations-servers-background-processes-store command.
func runOrganizationsServersBackgroundProcessesStoreCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsServersBackgroundProcessesStoreCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsServersBackgroundProcessesStoreCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersBackgroundProcessesStoreRequest](cmd, organizationsServersBackgroundProcessesStoreCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.BackgroundProcesses.OrganizationsServersBackgroundProcessesStore(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
