// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package securityrules

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsServersSitesSecurityRulesUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "server-param", FieldPath: "Server", Kind: flagutil.FlagKindInt64, Required: true, Description: "The server ID [required]"},
	{FlagName: "site", FieldPath: "Site", Kind: flagutil.FlagKindInt64, Required: true, Description: "The site ID [required]"},
	{FlagName: "security-rule", FieldPath: "SecurityRule", Kind: flagutil.FlagKindInt64, Required: true, Description: "The security rule ID [required]"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Required: true, Description: "The name of the security rule. [required]"},
	{FlagName: "path", Shorthand: "p", FieldPath: "Body.Path", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"path,omitempty"`, Description: "The path for the security rule."},
	{FlagName: "credentials", Shorthand: "c", FieldPath: "Body.Credentials", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"credentials"`, Description: "The credentials for the security rule. [required]"},
}

// initOrganizationsServersSitesSecurityRulesUpdateCmd initializes the organizations-servers-sites-security-rules-update command.
func initOrganizationsServersSitesSecurityRulesUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-servers-sites-security-rules-update",
		Short:   "Update site security rule",
		Long:    "Update an existing security rule for a site.\n\nProcessing mode: <small><code>async</code></small>",
		Example: "  forge security-rules organizations-servers-sites-security-rules-update --organization <value> --server-param 670665 --site 934399 --security-rule 830016 --name Restricted Access",
		Args:    cobra.NoArgs,
		RunE:    runOrganizationsServersSitesSecurityRulesUpdateCmd,
		Aliases: []string{"osssru"},
		Annotations: map[string]string{
			"speakeasy_operation": "organizations.servers.sites.security-rules.update",
		},
	}
	flagutil.RegisterFlags(cmd, organizationsServersSitesSecurityRulesUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsServersSitesSecurityRulesUpdateRequest](organizationsServersSitesSecurityRulesUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-servers-sites-security-rules-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, organizationsServersSitesSecurityRulesUpdateCmdMeta, "Body", "body"); err != nil {
		return fmt.Errorf("annotate body fields for organizations-servers-sites-security-rules-update: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsServersSitesSecurityRulesUpdateCmd executes the organizations-servers-sites-security-rules-update command.
func runOrganizationsServersSitesSecurityRulesUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "organizations.servers.sites.security-rules.update")
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsServersSitesSecurityRulesUpdateRequest](cmd, organizationsServersSitesSecurityRulesUpdateCmdMeta, "Body", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd, "Oauth2")
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.SecurityRules.OrganizationsServersSitesSecurityRulesUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
