// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package securityrules

import (
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitSecurityRulesRoot(parent *cobra.Command) error {
	var SecurityRulesCmd = &cobra.Command{
		Use:   "security-rules",
		Short: "Operations for security-rules",
		Long:  "Operations for security-rules",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"sr"},
	}

	if err := initOrganizationsServersSitesSecurityRulesIndexCmd(SecurityRulesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesSecurityRulesStoreCmd(SecurityRulesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesSecurityRulesShowCmd(SecurityRulesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesSecurityRulesUpdateCmd(SecurityRulesCmd); err != nil {
		return err
	}

	if err := initOrganizationsServersSitesSecurityRulesDestroyCmd(SecurityRulesCmd); err != nil {
		return err
	}

	parent.AddCommand(SecurityRulesCmd)
	return nil
}
