// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package teams

import (
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/client"
	"github.com/mfullbrook/forge-cli/internal/flagutil"
	"github.com/mfullbrook/forge-cli/internal/interactive"
	"github.com/mfullbrook/forge-cli/internal/output"
	"github.com/mfullbrook/forge-cli/internal/sdk"
	"github.com/mfullbrook/forge-cli/internal/sdk/models/operations"
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

var organizationsTeamsIndexCmdMeta = []flagutil.FlagMeta{
	{FlagName: "organization", FieldPath: "Organization", Kind: flagutil.FlagKindString, Required: true, Description: "The organization slug [required]"},
	{FlagName: "page-size", FieldPath: "PageSize", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 30, Description: "The number of results that will be returned per page."},
	{FlagName: "page-cursor", FieldPath: "PageCursor", Kind: flagutil.FlagKindString, Optional: true, Description: "The cursor to start the pagination from."},
}

// initOrganizationsTeamsIndexCmd initializes the organizations-teams-index command.
func initOrganizationsTeamsIndexCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "organizations-teams-index",
		Short:   "List teams",
		Long:    "Show all teams for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
		Example: "  forge teams organizations-teams-index --organization <value>",
		RunE:    runOrganizationsTeamsIndexCmd,
		Aliases: []string{"oti"},
	}
	flagutil.RegisterFlags(cmd, organizationsTeamsIndexCmdMeta)
	if err := flagutil.ValidateMeta[operations.OrganizationsTeamsIndexRequest](organizationsTeamsIndexCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for organizations-teams-index: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runOrganizationsTeamsIndexCmd executes the organizations-teams-index command.
func runOrganizationsTeamsIndexCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, organizationsTeamsIndexCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, organizationsTeamsIndexCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.OrganizationsTeamsIndexRequest](cmd, organizationsTeamsIndexCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Teams.OrganizationsTeamsIndex(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
