// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package teams

import (
	"github.com/mfullbrook/forge-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitTeamsRoot(parent *cobra.Command) error {
	var TeamsCmd = &cobra.Command{
		Use:   "teams",
		Short: "Operations for teams",
		Long:  "Operations for teams",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initOrganizationsTeamsIndexCmd(TeamsCmd); err != nil {
		return err
	}

	if err := initOrganizationsTeamsStoreCmd(TeamsCmd); err != nil {
		return err
	}

	if err := initOrganizationsTeamsShowCmd(TeamsCmd); err != nil {
		return err
	}

	if err := initOrganizationsTeamsUpdateCmd(TeamsCmd); err != nil {
		return err
	}

	if err := initOrganizationsTeamsDestroyCmd(TeamsCmd); err != nil {
		return err
	}

	if err := initOrganizationsTeamsMembersIndexCmd(TeamsCmd); err != nil {
		return err
	}

	if err := initOrganizationsTeamsMembersShowCmd(TeamsCmd); err != nil {
		return err
	}

	if err := initOrganizationsTeamsMembersDestroyCmd(TeamsCmd); err != nil {
		return err
	}

	if err := initOrganizationsTeamsMembersUpdateCmd(TeamsCmd); err != nil {
		return err
	}

	if err := initOrganizationsTeamsInvitesStoreCmd(TeamsCmd); err != nil {
		return err
	}

	if err := initOrganizationsTeamsInvitesIndexCmd(TeamsCmd); err != nil {
		return err
	}

	if err := initOrganizationsTeamsInvitesShowCmd(TeamsCmd); err != nil {
		return err
	}

	if err := initOrganizationsTeamsInvitesDestroyCmd(TeamsCmd); err != nil {
		return err
	}

	parent.AddCommand(TeamsCmd)
	return nil
}
