// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type ApplicationLogResourceType string

const (
	ApplicationLogResourceTypeApplicationLogs ApplicationLogResourceType = "applicationLogs"
)

func (e ApplicationLogResourceType) ToPointer() *ApplicationLogResourceType {
	return &e
}
func (e *ApplicationLogResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "applicationLogs":
		*e = ApplicationLogResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ApplicationLogResourceType: %v", v)
	}
}

type ApplicationLogResourceAttributes struct {
	// The content of the log.
	Content string `json:"content"`
}

func (a *ApplicationLogResourceAttributes) GetContent() string {
	if a == nil {
		return ""
	}
	return a.Content
}

type ApplicationLogResourceLinks struct {
	Self Link `json:"self"`
}

func (a *ApplicationLogResourceLinks) GetSelf() Link {
	if a == nil {
		return Link{}
	}
	return a.Self
}

type ApplicationLogResource struct {
	ID         string                            `json:"id"`
	Type       ApplicationLogResourceType        `json:"type"`
	Attributes *ApplicationLogResourceAttributes `json:"attributes,omitzero"`
	Links      ApplicationLogResourceLinks       `json:"links"`
}

func (a ApplicationLogResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ApplicationLogResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ApplicationLogResource) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *ApplicationLogResource) GetType() ApplicationLogResourceType {
	if a == nil {
		return ApplicationLogResourceType("")
	}
	return a.Type
}

func (a *ApplicationLogResource) GetAttributes() *ApplicationLogResourceAttributes {
	if a == nil {
		return nil
	}
	return a.Attributes
}

func (a *ApplicationLogResource) GetLinks() ApplicationLogResourceLinks {
	if a == nil {
		return ApplicationLogResourceLinks{}
	}
	return a.Links
}
