// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ArchiveRequest struct {
	ServerID int64 `json:"server_id"`
}

func (a *ArchiveRequest) GetServerID() int64 {
	if a == nil {
		return 0
	}
	return a.ServerID
}
