// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type BackgroundProcessLogResourceType string

const (
	BackgroundProcessLogResourceTypeBackgroundProcessLogs BackgroundProcessLogResourceType = "backgroundProcessLogs"
)

func (e BackgroundProcessLogResourceType) ToPointer() *BackgroundProcessLogResourceType {
	return &e
}
func (e *BackgroundProcessLogResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "backgroundProcessLogs":
		*e = BackgroundProcessLogResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BackgroundProcessLogResourceType: %v", v)
	}
}

type BackgroundProcessLogResourceAttributes struct {
	// The content of the log.
	Content string `json:"content"`
}

func (b *BackgroundProcessLogResourceAttributes) GetContent() string {
	if b == nil {
		return ""
	}
	return b.Content
}

type BackgroundProcessLogResourceLinks struct {
	Self Link `json:"self"`
}

func (b *BackgroundProcessLogResourceLinks) GetSelf() Link {
	if b == nil {
		return Link{}
	}
	return b.Self
}

type BackgroundProcessLogResource struct {
	ID         string                                  `json:"id"`
	Type       BackgroundProcessLogResourceType        `json:"type"`
	Attributes *BackgroundProcessLogResourceAttributes `json:"attributes,omitzero"`
	Links      BackgroundProcessLogResourceLinks       `json:"links"`
}

func (b BackgroundProcessLogResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BackgroundProcessLogResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BackgroundProcessLogResource) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BackgroundProcessLogResource) GetType() BackgroundProcessLogResourceType {
	if b == nil {
		return BackgroundProcessLogResourceType("")
	}
	return b.Type
}

func (b *BackgroundProcessLogResource) GetAttributes() *BackgroundProcessLogResourceAttributes {
	if b == nil {
		return nil
	}
	return b.Attributes
}

func (b *BackgroundProcessLogResource) GetLinks() BackgroundProcessLogResourceLinks {
	if b == nil {
		return BackgroundProcessLogResourceLinks{}
	}
	return b.Links
}
