// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CertificateType string

const (
	CertificateTypeLetsencrypt CertificateType = "letsencrypt"
	CertificateTypeCsr         CertificateType = "csr"
	CertificateTypeExisting    CertificateType = "existing"
)

func (e CertificateType) ToPointer() *CertificateType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CertificateType) IsExact() bool {
	if e != nil {
		switch *e {
		case "letsencrypt", "csr", "existing":
			return true
		}
	}
	return false
}
