// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
	"github.com/mfullbrook/forge-cli/internal/sdk/types"
	"time"
)

type CertificateResourceType string

const (
	CertificateResourceTypeCertificates CertificateResourceType = "certificates"
)

func (e CertificateResourceType) ToPointer() *CertificateResourceType {
	return &e
}
func (e *CertificateResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "certificates":
		*e = CertificateResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CertificateResourceType: %v", v)
	}
}

type CertificateResourceAttributes struct {
	Type               CertificateType                `json:"type"`
	VerificationMethod *CertificateVerificationMethod `json:"verification_method"`
	KeyType            *CertificateKeyType            `json:"key_type"`
	// The preferred chain for Let's Encrypt certificates.
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	preferredChain *string                  `const:"ISRG Root X1" json:"preferred_chain"`
	RequestStatus  CertificateRequestStatus `json:"request_status"`
	Status         ResourceState            `json:"status"`
	// Whether the certificate is currently active.
	Active bool `json:"active"`
	// The date and time the certificate was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time the certificate was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

func (c CertificateResourceAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CertificateResourceAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CertificateResourceAttributes) GetType() CertificateType {
	if c == nil {
		return CertificateType("")
	}
	return c.Type
}

func (c *CertificateResourceAttributes) GetVerificationMethod() *CertificateVerificationMethod {
	if c == nil {
		return nil
	}
	return c.VerificationMethod
}

func (c *CertificateResourceAttributes) GetKeyType() *CertificateKeyType {
	if c == nil {
		return nil
	}
	return c.KeyType
}

func (c *CertificateResourceAttributes) GetPreferredChain() *string {
	return types.Pointer("ISRG Root X1")
}

func (c *CertificateResourceAttributes) GetRequestStatus() CertificateRequestStatus {
	if c == nil {
		return CertificateRequestStatus("")
	}
	return c.RequestStatus
}

func (c *CertificateResourceAttributes) GetStatus() ResourceState {
	if c == nil {
		return ResourceState("")
	}
	return c.Status
}

func (c *CertificateResourceAttributes) GetActive() bool {
	if c == nil {
		return false
	}
	return c.Active
}

func (c *CertificateResourceAttributes) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CertificateResourceAttributes) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

type CertificateResource struct {
	ID         string                         `json:"id"`
	Type       CertificateResourceType        `json:"type"`
	Attributes *CertificateResourceAttributes `json:"attributes,omitzero"`
}

func (c CertificateResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CertificateResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CertificateResource) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CertificateResource) GetType() CertificateResourceType {
	if c == nil {
		return CertificateResourceType("")
	}
	return c.Type
}

func (c *CertificateResource) GetAttributes() *CertificateResourceAttributes {
	if c == nil {
		return nil
	}
	return c.Attributes
}
