// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type CreateRecipeRequestUser string

const (
	CreateRecipeRequestUserRoot  CreateRecipeRequestUser = "root"
	CreateRecipeRequestUserForge CreateRecipeRequestUser = "forge"
)

func (e CreateRecipeRequestUser) ToPointer() *CreateRecipeRequestUser {
	return &e
}
func (e *CreateRecipeRequestUser) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "root":
		fallthrough
	case "forge":
		*e = CreateRecipeRequestUser(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateRecipeRequestUser: %v", v)
	}
}

type CreateRecipeRequest struct {
	Name   string                  `json:"name"`
	User   CreateRecipeRequestUser `json:"user"`
	Script string                  `json:"script"`
	TeamID *int64                  `json:"team_id,omitzero"`
}

func (c *CreateRecipeRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateRecipeRequest) GetUser() CreateRecipeRequestUser {
	if c == nil {
		return CreateRecipeRequestUser("")
	}
	return c.User
}

func (c *CreateRecipeRequest) GetScript() string {
	if c == nil {
		return ""
	}
	return c.Script
}

func (c *CreateRecipeRequest) GetTeamID() *int64 {
	if c == nil {
		return nil
	}
	return c.TeamID
}
