// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/optionalnullable"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type CreateNpmCredentialRequest struct {
	Registry string                                      `json:"registry"`
	Token    string                                      `json:"token"`
	Scopes   optionalnullable.OptionalNullable[[]string] `json:"scopes,omitzero"`
}

func (c CreateNpmCredentialRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateNpmCredentialRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateNpmCredentialRequest) GetRegistry() string {
	if c == nil {
		return ""
	}
	return c.Registry
}

func (c *CreateNpmCredentialRequest) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}

func (c *CreateNpmCredentialRequest) GetScopes() optionalnullable.OptionalNullable[[]string] {
	if c == nil {
		return nil
	}
	return c.Scopes
}
