// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/optionalnullable"
)

type CreateDatabaseRequest struct {
	// The name of the database to create.
	Name string `json:"name"`
	// The name of the database user to create. Only needed if a new user should be created alongside the database.
	User optionalnullable.OptionalNullable[string] `json:"user,omitzero"`
	// The password for the database user. Only used if the user is provided.
	Password optionalnullable.OptionalNullable[string] `json:"password,omitzero"`
}

func (c *CreateDatabaseRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateDatabaseRequest) GetUser() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.User
}

func (c *CreateDatabaseRequest) GetPassword() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Password
}
