// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateComposerCredentialRequest struct {
	Repository string `json:"repository"`
	Username   string `json:"username"`
	Password   string `json:"password"`
}

func (c *CreateComposerCredentialRequest) GetRepository() string {
	if c == nil {
		return ""
	}
	return c.Repository
}

func (c *CreateComposerCredentialRequest) GetUsername() string {
	if c == nil {
		return ""
	}
	return c.Username
}

func (c *CreateComposerCredentialRequest) GetPassword() string {
	if c == nil {
		return ""
	}
	return c.Password
}
