// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/optionalnullable"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type CreateSSHKeyRequest struct {
	// The name of the SSH key.
	Name string `json:"name"`
	// The public SSH key.
	Key string `json:"key"`
	// The user associated with the SSH key.
	User optionalnullable.OptionalNullable[string] `default:"forge" json:"user"`
}

func (c CreateSSHKeyRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateSSHKeyRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateSSHKeyRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateSSHKeyRequest) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *CreateSSHKeyRequest) GetUser() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.User
}
