// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/optionalnullable"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

// CreateDomainCertificateRequestType - The type of certificate to create.
type CreateDomainCertificateRequestType string

const (
	CreateDomainCertificateRequestTypeLetsencrypt CreateDomainCertificateRequestType = "letsencrypt"
	CreateDomainCertificateRequestTypeCsr         CreateDomainCertificateRequestType = "csr"
	CreateDomainCertificateRequestTypeExisting    CreateDomainCertificateRequestType = "existing"
	CreateDomainCertificateRequestTypeClone       CreateDomainCertificateRequestType = "clone"
)

func (e CreateDomainCertificateRequestType) ToPointer() *CreateDomainCertificateRequestType {
	return &e
}
func (e *CreateDomainCertificateRequestType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "letsencrypt":
		fallthrough
	case "csr":
		fallthrough
	case "existing":
		fallthrough
	case "clone":
		*e = CreateDomainCertificateRequestType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateDomainCertificateRequestType: %v", v)
	}
}

// Letsencrypt - The configuration for a Let's Encrypt certificate.
type Letsencrypt struct {
	VerificationMethod *CertificateVerificationMethod `json:"verification_method,omitzero"`
	KeyType            *CertificateKeyType            `json:"key_type,omitzero"`
	// The preferred chain for the Let's Encrypt certificate.
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	preferredChain optionalnullable.OptionalNullable[string] `const:"ISRG Root X1" json:"preferred_chain,omitzero"`
}

func (l Letsencrypt) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *Letsencrypt) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *Letsencrypt) GetVerificationMethod() *CertificateVerificationMethod {
	if l == nil {
		return nil
	}
	return l.VerificationMethod
}

func (l *Letsencrypt) GetKeyType() *CertificateKeyType {
	if l == nil {
		return nil
	}
	return l.KeyType
}

func (l *Letsencrypt) GetPreferredChain() optionalnullable.OptionalNullable[string] {
	var tmp string = "ISRG Root X1"
	return optionalnullable.From[string](&tmp)
}

// Existing - The configuration for an existing certificate.
type Existing struct {
	// The private key for an existing certificate.
	Key *string `json:"key,omitzero"`
	// The certificate chain for an existing certificate.
	Certificate *string `json:"certificate,omitzero"`
}

func (e *Existing) GetKey() *string {
	if e == nil {
		return nil
	}
	return e.Key
}

func (e *Existing) GetCertificate() *string {
	if e == nil {
		return nil
	}
	return e.Certificate
}

// Csr - The configuration for a CSR (Certificate Signing Request).
type Csr struct {
	// The domain to generate a CSR for.
	Domain *string `json:"domain,omitzero"`
	// The SANs for the CSR, comma-separated.
	Sans optionalnullable.OptionalNullable[string] `json:"sans,omitzero"`
	// The country for the CSR.
	Country *string `json:"country,omitzero"`
	// The state for the CSR.
	State *string `json:"state,omitzero"`
	// The city for the CSR.
	City *string `json:"city,omitzero"`
	// The organization for the CSR.
	Organization *string `json:"organization,omitzero"`
	// The department for the CSR.
	Department *string `json:"department,omitzero"`
}

func (c *Csr) GetDomain() *string {
	if c == nil {
		return nil
	}
	return c.Domain
}

func (c *Csr) GetSans() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Sans
}

func (c *Csr) GetCountry() *string {
	if c == nil {
		return nil
	}
	return c.Country
}

func (c *Csr) GetState() *string {
	if c == nil {
		return nil
	}
	return c.State
}

func (c *Csr) GetCity() *string {
	if c == nil {
		return nil
	}
	return c.City
}

func (c *Csr) GetOrganization() *string {
	if c == nil {
		return nil
	}
	return c.Organization
}

func (c *Csr) GetDepartment() *string {
	if c == nil {
		return nil
	}
	return c.Department
}

type Clone struct {
	// The ID of the certificate to clone.
	CertificateID *int64 `json:"certificate_id,omitzero"`
}

func (c *Clone) GetCertificateID() *int64 {
	if c == nil {
		return nil
	}
	return c.CertificateID
}

type CreateDomainCertificateRequest struct {
	// Whether to enable the certificate upon installation.
	Enable *bool `json:"enable,omitzero"`
	// The type of certificate to create.
	Type CreateDomainCertificateRequestType `json:"type"`
	// The configuration for a Let's Encrypt certificate.
	Letsencrypt *Letsencrypt `json:"letsencrypt,omitzero"`
	// The configuration for an existing certificate.
	Existing *Existing `json:"existing,omitzero"`
	// The configuration for a CSR (Certificate Signing Request).
	Csr   *Csr   `json:"csr,omitzero"`
	Clone *Clone `json:"clone,omitzero"`
}

func (c CreateDomainCertificateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateDomainCertificateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateDomainCertificateRequest) GetEnable() *bool {
	if c == nil {
		return nil
	}
	return c.Enable
}

func (c *CreateDomainCertificateRequest) GetType() CreateDomainCertificateRequestType {
	if c == nil {
		return CreateDomainCertificateRequestType("")
	}
	return c.Type
}

func (c *CreateDomainCertificateRequest) GetLetsencrypt() *Letsencrypt {
	if c == nil {
		return nil
	}
	return c.Letsencrypt
}

func (c *CreateDomainCertificateRequest) GetExisting() *Existing {
	if c == nil {
		return nil
	}
	return c.Existing
}

func (c *CreateDomainCertificateRequest) GetCsr() *Csr {
	if c == nil {
		return nil
	}
	return c.Csr
}

func (c *CreateDomainCertificateRequest) GetClone() *Clone {
	if c == nil {
		return nil
	}
	return c.Clone
}
