// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateSecurityRuleRequestCredential struct {
	// The usernames for the credential.
	Username string `json:"username"`
	// The passwords for the credential.
	Password string `json:"password"`
}

func (c *CreateSecurityRuleRequestCredential) GetUsername() string {
	if c == nil {
		return ""
	}
	return c.Username
}

func (c *CreateSecurityRuleRequestCredential) GetPassword() string {
	if c == nil {
		return ""
	}
	return c.Password
}

type CreateSecurityRuleRequest struct {
	// The name of the security rule.
	Name string `json:"name"`
	// The path for the security rule.
	Path *string `json:"path,omitzero"`
	// The credentials for the security rule.
	Credentials []CreateSecurityRuleRequestCredential `json:"credentials"`
}

func (c *CreateSecurityRuleRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateSecurityRuleRequest) GetPath() *string {
	if c == nil {
		return nil
	}
	return c.Path
}

func (c *CreateSecurityRuleRequest) GetCredentials() []CreateSecurityRuleRequestCredential {
	if c == nil {
		return []CreateSecurityRuleRequestCredential{}
	}
	return c.Credentials
}
