// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type CustomRoleResourceType string

const (
	CustomRoleResourceTypeCustomRoles CustomRoleResourceType = "customRoles"
)

func (e CustomRoleResourceType) ToPointer() *CustomRoleResourceType {
	return &e
}
func (e *CustomRoleResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "customRoles":
		*e = CustomRoleResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomRoleResourceType: %v", v)
	}
}

type CustomRoleResourceAttributes struct {
	Name      string     `json:"name"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

func (c CustomRoleResourceAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomRoleResourceAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomRoleResourceAttributes) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomRoleResourceAttributes) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CustomRoleResourceAttributes) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

type CustomRoleResourcePermissions struct {
	Data []PermissionResourceIdentifier `json:"data"`
}

func (c *CustomRoleResourcePermissions) GetData() []PermissionResourceIdentifier {
	if c == nil {
		return []PermissionResourceIdentifier{}
	}
	return c.Data
}

type CustomRoleResourceRelationships struct {
	Permissions *CustomRoleResourcePermissions `json:"permissions,omitzero"`
}

func (c CustomRoleResourceRelationships) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomRoleResourceRelationships) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomRoleResourceRelationships) GetPermissions() *CustomRoleResourcePermissions {
	if c == nil {
		return nil
	}
	return c.Permissions
}

type CustomRoleResourceLinks struct {
	Self Link `json:"self"`
}

func (c *CustomRoleResourceLinks) GetSelf() Link {
	if c == nil {
		return Link{}
	}
	return c.Self
}

type CustomRoleResource struct {
	ID            string                           `json:"id"`
	Type          CustomRoleResourceType           `json:"type"`
	Attributes    *CustomRoleResourceAttributes    `json:"attributes,omitzero"`
	Relationships *CustomRoleResourceRelationships `json:"relationships,omitzero"`
	Links         CustomRoleResourceLinks          `json:"links"`
}

func (c CustomRoleResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomRoleResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomRoleResource) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CustomRoleResource) GetType() CustomRoleResourceType {
	if c == nil {
		return CustomRoleResourceType("")
	}
	return c.Type
}

func (c *CustomRoleResource) GetAttributes() *CustomRoleResourceAttributes {
	if c == nil {
		return nil
	}
	return c.Attributes
}

func (c *CustomRoleResource) GetRelationships() *CustomRoleResourceRelationships {
	if c == nil {
		return nil
	}
	return c.Relationships
}

func (c *CustomRoleResource) GetLinks() CustomRoleResourceLinks {
	if c == nil {
		return CustomRoleResourceLinks{}
	}
	return c.Links
}
