// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type DeployHookResourceType string

const (
	DeployHookResourceTypeDeploymentHooks DeployHookResourceType = "deploymentHooks"
)

func (e DeployHookResourceType) ToPointer() *DeployHookResourceType {
	return &e
}
func (e *DeployHookResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "deploymentHooks":
		*e = DeployHookResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeployHookResourceType: %v", v)
	}
}

type DeployHookResourceAttributes struct {
	// The URL to use for the deployment hook.
	URL string `json:"url"`
}

func (d *DeployHookResourceAttributes) GetURL() string {
	if d == nil {
		return ""
	}
	return d.URL
}

type DeployHookResourceLinks struct {
	Self Link `json:"self"`
}

func (d *DeployHookResourceLinks) GetSelf() Link {
	if d == nil {
		return Link{}
	}
	return d.Self
}

type DeployHookResource struct {
	ID         string                        `json:"id"`
	Type       DeployHookResourceType        `json:"type"`
	Attributes *DeployHookResourceAttributes `json:"attributes,omitzero"`
	Links      DeployHookResourceLinks       `json:"links"`
}

func (d DeployHookResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeployHookResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeployHookResource) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeployHookResource) GetType() DeployHookResourceType {
	if d == nil {
		return DeployHookResourceType("")
	}
	return d.Type
}

func (d *DeployHookResource) GetAttributes() *DeployHookResourceAttributes {
	if d == nil {
		return nil
	}
	return d.Attributes
}

func (d *DeployHookResource) GetLinks() DeployHookResourceLinks {
	if d == nil {
		return DeployHookResourceLinks{}
	}
	return d.Links
}
