// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type DeploymentResourceType string

const (
	DeploymentResourceTypeDeployments DeploymentResourceType = "deployments"
)

func (e DeploymentResourceType) ToPointer() *DeploymentResourceType {
	return &e
}
func (e *DeploymentResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "deployments":
		*e = DeploymentResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeploymentResourceType: %v", v)
	}
}

// Commit - The commit information for the deployment.
type Commit struct {
	// The commit hash.
	Hash *string `json:"hash"`
	// The commit author.
	Author *string `json:"author"`
	// The commit message.
	Message *string `json:"message"`
	// The commit branch.
	Branch *string `json:"branch"`
}

func (c Commit) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Commit) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Commit) GetHash() *string {
	if c == nil {
		return nil
	}
	return c.Hash
}

func (c *Commit) GetAuthor() *string {
	if c == nil {
		return nil
	}
	return c.Author
}

func (c *Commit) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *Commit) GetBranch() *string {
	if c == nil {
		return nil
	}
	return c.Branch
}

type DeploymentResourceAttributes struct {
	// The commit information for the deployment.
	Commit Commit           `json:"commit"`
	Type   string           `json:"type"`
	Status DeploymentStatus `json:"status"`
	// The date and time the deployment started.
	StartedAt time.Time `json:"started_at"`
	// The date and time the deployment ended.
	EndedAt time.Time `json:"ended_at"`
	// The date and time the deployment was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time the deployment was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

func (d DeploymentResourceAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeploymentResourceAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeploymentResourceAttributes) GetCommit() Commit {
	if d == nil {
		return Commit{}
	}
	return d.Commit
}

func (d *DeploymentResourceAttributes) GetType() string {
	if d == nil {
		return ""
	}
	return d.Type
}

func (d *DeploymentResourceAttributes) GetStatus() DeploymentStatus {
	if d == nil {
		return DeploymentStatus("")
	}
	return d.Status
}

func (d *DeploymentResourceAttributes) GetStartedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.StartedAt
}

func (d *DeploymentResourceAttributes) GetEndedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.EndedAt
}

func (d *DeploymentResourceAttributes) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}

func (d *DeploymentResourceAttributes) GetUpdatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.UpdatedAt
}

type DeploymentResource struct {
	ID         string                        `json:"id"`
	Type       DeploymentResourceType        `json:"type"`
	Attributes *DeploymentResourceAttributes `json:"attributes,omitzero"`
}

func (d DeploymentResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeploymentResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeploymentResource) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeploymentResource) GetType() DeploymentResourceType {
	if d == nil {
		return DeploymentResourceType("")
	}
	return d.Type
}

func (d *DeploymentResource) GetAttributes() *DeploymentResourceAttributes {
	if d == nil {
		return nil
	}
	return d.Attributes
}
