// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type DeploymentWebhookResourceType string

const (
	DeploymentWebhookResourceTypeDeploymentWebhooks DeploymentWebhookResourceType = "deploymentWebhooks"
)

func (e DeploymentWebhookResourceType) ToPointer() *DeploymentWebhookResourceType {
	return &e
}
func (e *DeploymentWebhookResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "deploymentWebhooks":
		*e = DeploymentWebhookResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeploymentWebhookResourceType: %v", v)
	}
}

type DeploymentWebhookResourceAttributes struct {
	// The URL of the deployment webhook.
	URL string `json:"url"`
	// The date and time the deployment webhook was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time the deployment webhook was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

func (d DeploymentWebhookResourceAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeploymentWebhookResourceAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeploymentWebhookResourceAttributes) GetURL() string {
	if d == nil {
		return ""
	}
	return d.URL
}

func (d *DeploymentWebhookResourceAttributes) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}

func (d *DeploymentWebhookResourceAttributes) GetUpdatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.UpdatedAt
}

type DeploymentWebhookResourceLinks struct {
	Self Link `json:"self"`
}

func (d *DeploymentWebhookResourceLinks) GetSelf() Link {
	if d == nil {
		return Link{}
	}
	return d.Self
}

type DeploymentWebhookResource struct {
	ID         string                               `json:"id"`
	Type       DeploymentWebhookResourceType        `json:"type"`
	Attributes *DeploymentWebhookResourceAttributes `json:"attributes,omitzero"`
	Links      DeploymentWebhookResourceLinks       `json:"links"`
}

func (d DeploymentWebhookResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeploymentWebhookResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeploymentWebhookResource) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeploymentWebhookResource) GetType() DeploymentWebhookResourceType {
	if d == nil {
		return DeploymentWebhookResourceType("")
	}
	return d.Type
}

func (d *DeploymentWebhookResource) GetAttributes() *DeploymentWebhookResourceAttributes {
	if d == nil {
		return nil
	}
	return d.Attributes
}

func (d *DeploymentWebhookResource) GetLinks() DeploymentWebhookResourceLinks {
	if d == nil {
		return DeploymentWebhookResourceLinks{}
	}
	return d.Links
}
