// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DomainActionRequest struct {
	Action DomainRecordAction `json:"action"`
}

func (d *DomainActionRequest) GetAction() DomainRecordAction {
	if d == nil {
		return DomainRecordAction("")
	}
	return d.Action
}
