// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DomainRecordAction string

const (
	DomainRecordActionEnable        DomainRecordAction = "enable"
	DomainRecordActionDisable       DomainRecordAction = "disable"
	DomainRecordActionMarkAsPrimary DomainRecordAction = "mark-as-primary"
)

func (e DomainRecordAction) ToPointer() *DomainRecordAction {
	return &e
}
func (e *DomainRecordAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "enable":
		fallthrough
	case "disable":
		fallthrough
	case "mark-as-primary":
		*e = DomainRecordAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DomainRecordAction: %v", v)
	}
}
