// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DomainCertificateActionRequest struct {
	Action DomainRecordCertificateAction `json:"action"`
}

func (d *DomainCertificateActionRequest) GetAction() DomainRecordCertificateAction {
	if d == nil {
		return DomainRecordCertificateAction("")
	}
	return d.Action
}
