// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

// DomainRecordConfigurationResourceType - The type of DNS record.
type DomainRecordConfigurationResourceType string

const (
	DomainRecordConfigurationResourceTypeA     DomainRecordConfigurationResourceType = "A"
	DomainRecordConfigurationResourceTypeCname DomainRecordConfigurationResourceType = "CNAME"
	DomainRecordConfigurationResourceTypeTxt   DomainRecordConfigurationResourceType = "TXT"
)

func (e DomainRecordConfigurationResourceType) ToPointer() *DomainRecordConfigurationResourceType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DomainRecordConfigurationResourceType) IsExact() bool {
	if e != nil {
		switch *e {
		case "A", "CNAME", "TXT":
			return true
		}
	}
	return false
}

type DomainRecordConfigurationResourceAttributes struct {
	// The type of DNS record.
	Type DomainRecordConfigurationResourceType `json:"type"`
	// The name of the DNS record.
	Name string `json:"name"`
	// The value (IP address, CNAME target, TXT value) of the DNS record.
	Value string `json:"value"`
	// The recommended TTL (Time to Live) for the DNS record, in seconds.
	TTL *int64 `json:"ttl"`
}

func (d *DomainRecordConfigurationResourceAttributes) GetType() DomainRecordConfigurationResourceType {
	if d == nil {
		return DomainRecordConfigurationResourceType("")
	}
	return d.Type
}

func (d *DomainRecordConfigurationResourceAttributes) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DomainRecordConfigurationResourceAttributes) GetValue() string {
	if d == nil {
		return ""
	}
	return d.Value
}

func (d *DomainRecordConfigurationResourceAttributes) GetTTL() *int64 {
	if d == nil {
		return nil
	}
	return d.TTL
}

type DomainRecordConfigurationResource struct {
	ID         string                                       `json:"id"`
	Type       string                                       `json:"type"`
	Attributes *DomainRecordConfigurationResourceAttributes `json:"attributes,omitzero"`
}

func (d DomainRecordConfigurationResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DomainRecordConfigurationResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DomainRecordConfigurationResource) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DomainRecordConfigurationResource) GetType() string {
	if d == nil {
		return ""
	}
	return d.Type
}

func (d *DomainRecordConfigurationResource) GetAttributes() *DomainRecordConfigurationResourceAttributes {
	if d == nil {
		return nil
	}
	return d.Attributes
}
