// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DomainRecordCertificateAction string

const (
	DomainRecordCertificateActionEnable  DomainRecordCertificateAction = "enable"
	DomainRecordCertificateActionDisable DomainRecordCertificateAction = "disable"
)

func (e DomainRecordCertificateAction) ToPointer() *DomainRecordCertificateAction {
	return &e
}
func (e *DomainRecordCertificateAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "enable":
		fallthrough
	case "disable":
		*e = DomainRecordCertificateAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DomainRecordCertificateAction: %v", v)
	}
}
