// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MonitorMetricType string

const (
	MonitorMetricTypeCPULoad    MonitorMetricType = "cpu_load"
	MonitorMetricTypeDisk       MonitorMetricType = "disk"
	MonitorMetricTypeFreeMemory MonitorMetricType = "free_memory"
	MonitorMetricTypeUsedMemory MonitorMetricType = "used_memory"
)

func (e MonitorMetricType) ToPointer() *MonitorMetricType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MonitorMetricType) IsExact() bool {
	if e != nil {
		switch *e {
		case "cpu_load", "disk", "free_memory", "used_memory":
			return true
		}
	}
	return false
}
