// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type NginxTemplateResourceType string

const (
	NginxTemplateResourceTypeNginxTemplates NginxTemplateResourceType = "nginxTemplates"
)

func (e NginxTemplateResourceType) ToPointer() *NginxTemplateResourceType {
	return &e
}
func (e *NginxTemplateResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "nginxTemplates":
		*e = NginxTemplateResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NginxTemplateResourceType: %v", v)
	}
}

type NginxTemplateResourceAttributes struct {
	Name      string     `json:"name"`
	Content   string     `json:"content"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

func (n NginxTemplateResourceAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NginxTemplateResourceAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NginxTemplateResourceAttributes) GetName() string {
	if n == nil {
		return ""
	}
	return n.Name
}

func (n *NginxTemplateResourceAttributes) GetContent() string {
	if n == nil {
		return ""
	}
	return n.Content
}

func (n *NginxTemplateResourceAttributes) GetCreatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.CreatedAt
}

func (n *NginxTemplateResourceAttributes) GetUpdatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.UpdatedAt
}

type NginxTemplateResourceLinks struct {
	Self Link `json:"self"`
}

func (n *NginxTemplateResourceLinks) GetSelf() Link {
	if n == nil {
		return Link{}
	}
	return n.Self
}

type NginxTemplateResource struct {
	ID         string                           `json:"id"`
	Type       NginxTemplateResourceType        `json:"type"`
	Attributes *NginxTemplateResourceAttributes `json:"attributes,omitzero"`
	Links      NginxTemplateResourceLinks       `json:"links"`
}

func (n NginxTemplateResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NginxTemplateResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NginxTemplateResource) GetID() string {
	if n == nil {
		return ""
	}
	return n.ID
}

func (n *NginxTemplateResource) GetType() NginxTemplateResourceType {
	if n == nil {
		return NginxTemplateResourceType("")
	}
	return n.Type
}

func (n *NginxTemplateResource) GetAttributes() *NginxTemplateResourceAttributes {
	if n == nil {
		return nil
	}
	return n.Attributes
}

func (n *NginxTemplateResource) GetLinks() NginxTemplateResourceLinks {
	if n == nil {
		return NginxTemplateResourceLinks{}
	}
	return n.Links
}
