// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type OrganizationResourceType string

const (
	OrganizationResourceTypeOrganizations OrganizationResourceType = "organizations"
)

func (e OrganizationResourceType) ToPointer() *OrganizationResourceType {
	return &e
}
func (e *OrganizationResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "organizations":
		*e = OrganizationResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OrganizationResourceType: %v", v)
	}
}

type OrganizationResourceAttributes struct {
	Name      string     `json:"name"`
	Slug      string     `json:"slug"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

func (o OrganizationResourceAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationResourceAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationResourceAttributes) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OrganizationResourceAttributes) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *OrganizationResourceAttributes) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *OrganizationResourceAttributes) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

type OrganizationResourceLinks struct {
	Self Link `json:"self"`
}

func (o OrganizationResourceLinks) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationResourceLinks) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationResourceLinks) GetSelf() Link {
	if o == nil {
		return Link{}
	}
	return o.Self
}

type OrganizationResource struct {
	ID         string                          `json:"id"`
	Type       OrganizationResourceType        `json:"type"`
	Attributes *OrganizationResourceAttributes `json:"attributes,omitzero"`
	Links      OrganizationResourceLinks       `json:"links"`
}

func (o OrganizationResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationResource) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OrganizationResource) GetType() OrganizationResourceType {
	if o == nil {
		return OrganizationResourceType("")
	}
	return o.Type
}

func (o *OrganizationResource) GetAttributes() *OrganizationResourceAttributes {
	if o == nil {
		return nil
	}
	return o.Attributes
}

func (o *OrganizationResource) GetLinks() OrganizationResourceLinks {
	if o == nil {
		return OrganizationResourceLinks{}
	}
	return o.Links
}
