// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type PermissionResourceType string

const (
	PermissionResourceTypePermissions PermissionResourceType = "permissions"
)

func (e PermissionResourceType) ToPointer() *PermissionResourceType {
	return &e
}
func (e *PermissionResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "permissions":
		*e = PermissionResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PermissionResourceType: %v", v)
	}
}

type PermissionResourceAttributes struct {
	Name string `json:"name"`
}

func (p PermissionResourceAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PermissionResourceAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PermissionResourceAttributes) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

type PermissionResourceLinks struct {
	Self Link `json:"self"`
}

func (p PermissionResourceLinks) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PermissionResourceLinks) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PermissionResourceLinks) GetSelf() Link {
	if p == nil {
		return Link{}
	}
	return p.Self
}

type PermissionResource struct {
	ID         string                        `json:"id"`
	Type       PermissionResourceType        `json:"type"`
	Attributes *PermissionResourceAttributes `json:"attributes,omitzero"`
	Links      PermissionResourceLinks       `json:"links"`
}

func (p PermissionResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PermissionResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PermissionResource) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PermissionResource) GetType() PermissionResourceType {
	if p == nil {
		return PermissionResourceType("")
	}
	return p.Type
}

func (p *PermissionResource) GetAttributes() *PermissionResourceAttributes {
	if p == nil {
		return nil
	}
	return p.Attributes
}

func (p *PermissionResource) GetLinks() PermissionResourceLinks {
	if p == nil {
		return PermissionResourceLinks{}
	}
	return p.Links
}
