// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// PhpAction - | |
// |---|
// | `reboot` <br/> Reboot PHP-FPM for a specific version |
type PhpAction string

const (
	PhpActionReboot PhpAction = "reboot"
)

func (e PhpAction) ToPointer() *PhpAction {
	return &e
}
func (e *PhpAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "reboot":
		*e = PhpAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PhpAction: %v", v)
	}
}
