// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type PhpCliConfigurationResourceType string

const (
	PhpCliConfigurationResourceTypePhpCliConfigurations PhpCliConfigurationResourceType = "phpCliConfigurations"
)

func (e PhpCliConfigurationResourceType) ToPointer() *PhpCliConfigurationResourceType {
	return &e
}
func (e *PhpCliConfigurationResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "phpCliConfigurations":
		*e = PhpCliConfigurationResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PhpCliConfigurationResourceType: %v", v)
	}
}

type PhpCliConfigurationResourceAttributes struct {
	Configuration string `json:"configuration"`
}

func (p *PhpCliConfigurationResourceAttributes) GetConfiguration() string {
	if p == nil {
		return ""
	}
	return p.Configuration
}

type PhpCliConfigurationResourceLinks struct {
	Self Link `json:"self"`
}

func (p *PhpCliConfigurationResourceLinks) GetSelf() Link {
	if p == nil {
		return Link{}
	}
	return p.Self
}

type PhpCliConfigurationResource struct {
	ID         string                                 `json:"id"`
	Type       PhpCliConfigurationResourceType        `json:"type"`
	Attributes *PhpCliConfigurationResourceAttributes `json:"attributes,omitzero"`
	Links      PhpCliConfigurationResourceLinks       `json:"links"`
}

func (p PhpCliConfigurationResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PhpCliConfigurationResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PhpCliConfigurationResource) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PhpCliConfigurationResource) GetType() PhpCliConfigurationResourceType {
	if p == nil {
		return PhpCliConfigurationResourceType("")
	}
	return p.Type
}

func (p *PhpCliConfigurationResource) GetAttributes() *PhpCliConfigurationResourceAttributes {
	if p == nil {
		return nil
	}
	return p.Attributes
}

func (p *PhpCliConfigurationResource) GetLinks() PhpCliConfigurationResourceLinks {
	if p == nil {
		return PhpCliConfigurationResourceLinks{}
	}
	return p.Links
}
