// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type PhpPoolConfigurationResourceType string

const (
	PhpPoolConfigurationResourceTypePhpPoolConfigurations PhpPoolConfigurationResourceType = "phpPoolConfigurations"
)

func (e PhpPoolConfigurationResourceType) ToPointer() *PhpPoolConfigurationResourceType {
	return &e
}
func (e *PhpPoolConfigurationResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "phpPoolConfigurations":
		*e = PhpPoolConfigurationResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PhpPoolConfigurationResourceType: %v", v)
	}
}

type PhpPoolConfigurationResourceAttributes struct {
	Configuration string `json:"configuration"`
}

func (p *PhpPoolConfigurationResourceAttributes) GetConfiguration() string {
	if p == nil {
		return ""
	}
	return p.Configuration
}

type PhpPoolConfigurationResourceLinks struct {
	Self Link `json:"self"`
}

func (p *PhpPoolConfigurationResourceLinks) GetSelf() Link {
	if p == nil {
		return Link{}
	}
	return p.Self
}

type PhpPoolConfigurationResource struct {
	ID         string                                  `json:"id"`
	Type       PhpPoolConfigurationResourceType        `json:"type"`
	Attributes *PhpPoolConfigurationResourceAttributes `json:"attributes,omitzero"`
	Links      PhpPoolConfigurationResourceLinks       `json:"links"`
}

func (p PhpPoolConfigurationResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PhpPoolConfigurationResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PhpPoolConfigurationResource) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PhpPoolConfigurationResource) GetType() PhpPoolConfigurationResourceType {
	if p == nil {
		return PhpPoolConfigurationResourceType("")
	}
	return p.Type
}

func (p *PhpPoolConfigurationResource) GetAttributes() *PhpPoolConfigurationResourceAttributes {
	if p == nil {
		return nil
	}
	return p.Attributes
}

func (p *PhpPoolConfigurationResource) GetLinks() PhpPoolConfigurationResourceLinks {
	if p == nil {
		return PhpPoolConfigurationResourceLinks{}
	}
	return p.Links
}
