// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PhpServiceActionRequest struct {
	// | |
	// |---|
	// | `reboot` <br/> Reboot PHP-FPM for a specific version |
	Action  PhpAction  `json:"action"`
	Version PhpVersion `json:"version"`
}

func (p *PhpServiceActionRequest) GetAction() PhpAction {
	if p == nil {
		return PhpAction("")
	}
	return p.Action
}

func (p *PhpServiceActionRequest) GetVersion() PhpVersion {
	if p == nil {
		return PhpVersion("")
	}
	return p.Version
}
