// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type PhpVersion string

const (
	PhpVersionPhp5     PhpVersion = "php5"
	PhpVersionPhp56Old PhpVersion = "php56-old"
	PhpVersionPhp56    PhpVersion = "php56"
	PhpVersionPhp70    PhpVersion = "php70"
	PhpVersionPhp71    PhpVersion = "php71"
	PhpVersionPhp72    PhpVersion = "php72"
	PhpVersionPhp73    PhpVersion = "php73"
	PhpVersionPhp74    PhpVersion = "php74"
	PhpVersionPhp80    PhpVersion = "php80"
	PhpVersionPhp81    PhpVersion = "php81"
	PhpVersionPhp82    PhpVersion = "php82"
	PhpVersionPhp83    PhpVersion = "php83"
	PhpVersionPhp84    PhpVersion = "php84"
	PhpVersionPhp85    PhpVersion = "php85"
)

func (e PhpVersion) ToPointer() *PhpVersion {
	return &e
}
func (e *PhpVersion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "php5":
		fallthrough
	case "php56-old":
		fallthrough
	case "php56":
		fallthrough
	case "php70":
		fallthrough
	case "php71":
		fallthrough
	case "php72":
		fallthrough
	case "php73":
		fallthrough
	case "php74":
		fallthrough
	case "php80":
		fallthrough
	case "php81":
		fallthrough
	case "php82":
		fallthrough
	case "php83":
		fallthrough
	case "php84":
		fallthrough
	case "php85":
		*e = PhpVersion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PhpVersion: %v", v)
	}
}
