// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type RecipeResourceType string

const (
	RecipeResourceTypeRecipes RecipeResourceType = "recipes"
)

func (e RecipeResourceType) ToPointer() *RecipeResourceType {
	return &e
}
func (e *RecipeResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "recipes":
		*e = RecipeResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RecipeResourceType: %v", v)
	}
}

type RecipeResourceAttributes struct {
	// The name of the Recipe.
	Name string `json:"name"`
	// The script that should be executed.
	Script string `json:"script"`
	// The user that the Recipe should be executed as.
	User string `json:"user"`
	// The date the Recipe was created.
	CreatedAt time.Time `json:"created_at"`
	// The date the Recipe was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

func (r RecipeResourceAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RecipeResourceAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RecipeResourceAttributes) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RecipeResourceAttributes) GetScript() string {
	if r == nil {
		return ""
	}
	return r.Script
}

func (r *RecipeResourceAttributes) GetUser() string {
	if r == nil {
		return ""
	}
	return r.User
}

func (r *RecipeResourceAttributes) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *RecipeResourceAttributes) GetUpdatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.UpdatedAt
}

type RecipeResourceLinks struct {
	Self Link `json:"self"`
}

func (r *RecipeResourceLinks) GetSelf() Link {
	if r == nil {
		return Link{}
	}
	return r.Self
}

type RecipeResource struct {
	ID         string                    `json:"id"`
	Type       RecipeResourceType        `json:"type"`
	Attributes *RecipeResourceAttributes `json:"attributes,omitzero"`
	Links      RecipeResourceLinks       `json:"links"`
}

func (r RecipeResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RecipeResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RecipeResource) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RecipeResource) GetType() RecipeResourceType {
	if r == nil {
		return RecipeResourceType("")
	}
	return r.Type
}

func (r *RecipeResource) GetAttributes() *RecipeResourceAttributes {
	if r == nil {
		return nil
	}
	return r.Attributes
}

func (r *RecipeResource) GetLinks() RecipeResourceLinks {
	if r == nil {
		return RecipeResourceLinks{}
	}
	return r.Links
}
