// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResourceState string

const (
	ResourceStateInstalling    ResourceState = "installing"
	ResourceStateInstalled     ResourceState = "installed"
	ResourceStateRemoving      ResourceState = "removing"
	ResourceStateRestarting    ResourceState = "restarting"
	ResourceStateStopping      ResourceState = "stopping"
	ResourceStateStopped       ResourceState = "stopped"
	ResourceStateStarting      ResourceState = "starting"
	ResourceStateSyncing       ResourceState = "syncing"
	ResourceStateUpdating      ResourceState = "updating"
	ResourceStateDisabling     ResourceState = "disabling"
	ResourceStateDisabled      ResourceState = "disabled"
	ResourceStateEnabling      ResourceState = "enabling"
	ResourceStateRunning       ResourceState = "running"
	ResourceStateRestoring     ResourceState = "restoring"
	ResourceStateDeleting      ResourceState = "deleting"
	ResourceStateFailed        ResourceState = "failed"
	ResourceStateSuccess       ResourceState = "success"
	ResourceStateFailedUnknown ResourceState = "failed-unknown"
	ResourceStateFailedRunner  ResourceState = "failed-runner"
	ResourceStateRenewing      ResourceState = "renewing"
)

func (e ResourceState) ToPointer() *ResourceState {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ResourceState) IsExact() bool {
	if e != nil {
		switch *e {
		case "installing", "installed", "removing", "restarting", "stopping", "stopped", "starting", "syncing", "updating", "disabling", "disabled", "enabling", "running", "restoring", "deleting", "failed", "success", "failed-unknown", "failed-runner", "renewing":
			return true
		}
	}
	return false
}
