// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type SecurityRuleResourceIdentifierType string

const (
	SecurityRuleResourceIdentifierTypeSecurityRules SecurityRuleResourceIdentifierType = "securityRules"
)

func (e SecurityRuleResourceIdentifierType) ToPointer() *SecurityRuleResourceIdentifierType {
	return &e
}
func (e *SecurityRuleResourceIdentifierType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "securityRules":
		*e = SecurityRuleResourceIdentifierType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SecurityRuleResourceIdentifierType: %v", v)
	}
}

type SecurityRuleResourceIdentifier struct {
	Type SecurityRuleResourceIdentifierType `json:"type"`
	ID   string                             `json:"id"`
}

func (s *SecurityRuleResourceIdentifier) GetType() SecurityRuleResourceIdentifierType {
	if s == nil {
		return SecurityRuleResourceIdentifierType("")
	}
	return s.Type
}

func (s *SecurityRuleResourceIdentifier) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}
