// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ServerResourceIdentifierType string

const (
	ServerResourceIdentifierTypeServers ServerResourceIdentifierType = "servers"
)

func (e ServerResourceIdentifierType) ToPointer() *ServerResourceIdentifierType {
	return &e
}
func (e *ServerResourceIdentifierType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "servers":
		*e = ServerResourceIdentifierType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ServerResourceIdentifierType: %v", v)
	}
}

type ServerResourceIdentifier struct {
	Type ServerResourceIdentifierType `json:"type"`
	ID   string                       `json:"id"`
}

func (s *ServerResourceIdentifier) GetType() ServerResourceIdentifierType {
	if s == nil {
		return ServerResourceIdentifierType("")
	}
	return s.Type
}

func (s *ServerResourceIdentifier) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}
