// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ServerActionRequest struct {
	// | |
	// |---|
	// | `reboot` <br/> Reboot the server. |
	// | `power-cycle` <br/> Power-cycle the server. |
	Action ServerAction `json:"action"`
}

func (s *ServerActionRequest) GetAction() ServerAction {
	if s == nil {
		return ServerAction("")
	}
	return s.Action
}
