// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type StorageProviderResourceType string

const (
	StorageProviderResourceTypeStorageProviders StorageProviderResourceType = "storageProviders"
)

func (e StorageProviderResourceType) ToPointer() *StorageProviderResourceType {
	return &e
}
func (e *StorageProviderResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "storageProviders":
		*e = StorageProviderResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StorageProviderResourceType: %v", v)
	}
}

type ProviderName string

const (
	ProviderNameAmazonS3           ProviderName = "Amazon S3"
	ProviderNameDigitalOceanSpaces ProviderName = "DigitalOcean Spaces"
	ProviderNameHetzner            ProviderName = "Hetzner"
	ProviderNameOvh                ProviderName = "OVH"
	ProviderNameScaleway           ProviderName = "Scaleway"
	ProviderNameCustomS3Compatible ProviderName = "Custom (S3 Compatible)"
)

func (e ProviderName) ToPointer() *ProviderName {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProviderName) IsExact() bool {
	if e != nil {
		switch *e {
		case "Amazon S3", "DigitalOcean Spaces", "Hetzner", "OVH", "Scaleway", "Custom (S3 Compatible)":
			return true
		}
	}
	return false
}

type StorageProviderResourceAttributes struct {
	Name         string         `json:"name"`
	Provider     BackupProvider `json:"provider"`
	ProviderName ProviderName   `json:"provider_name"`
	Region       *string        `json:"region"`
	Bucket       *string        `json:"bucket"`
	Directory    *string        `json:"directory"`
	Endpoint     *string        `json:"endpoint"`
	AssumeRole   *bool          `json:"assume_role"`
	InUse        bool           `json:"in_use"`
	CreatedAt    *time.Time     `json:"created_at"`
	UpdatedAt    *time.Time     `json:"updated_at"`
}

func (s StorageProviderResourceAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StorageProviderResourceAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StorageProviderResourceAttributes) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StorageProviderResourceAttributes) GetProvider() BackupProvider {
	if s == nil {
		return BackupProvider("")
	}
	return s.Provider
}

func (s *StorageProviderResourceAttributes) GetProviderName() ProviderName {
	if s == nil {
		return ProviderName("")
	}
	return s.ProviderName
}

func (s *StorageProviderResourceAttributes) GetRegion() *string {
	if s == nil {
		return nil
	}
	return s.Region
}

func (s *StorageProviderResourceAttributes) GetBucket() *string {
	if s == nil {
		return nil
	}
	return s.Bucket
}

func (s *StorageProviderResourceAttributes) GetDirectory() *string {
	if s == nil {
		return nil
	}
	return s.Directory
}

func (s *StorageProviderResourceAttributes) GetEndpoint() *string {
	if s == nil {
		return nil
	}
	return s.Endpoint
}

func (s *StorageProviderResourceAttributes) GetAssumeRole() *bool {
	if s == nil {
		return nil
	}
	return s.AssumeRole
}

func (s *StorageProviderResourceAttributes) GetInUse() bool {
	if s == nil {
		return false
	}
	return s.InUse
}

func (s *StorageProviderResourceAttributes) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *StorageProviderResourceAttributes) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

type StorageProviderResourceLinks struct {
	Self Link `json:"self"`
}

func (s *StorageProviderResourceLinks) GetSelf() Link {
	if s == nil {
		return Link{}
	}
	return s.Self
}

type StorageProviderResource struct {
	ID         string                             `json:"id"`
	Type       StorageProviderResourceType        `json:"type"`
	Attributes *StorageProviderResourceAttributes `json:"attributes,omitzero"`
	Links      StorageProviderResourceLinks       `json:"links"`
}

func (s StorageProviderResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StorageProviderResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StorageProviderResource) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *StorageProviderResource) GetType() StorageProviderResourceType {
	if s == nil {
		return StorageProviderResourceType("")
	}
	return s.Type
}

func (s *StorageProviderResource) GetAttributes() *StorageProviderResourceAttributes {
	if s == nil {
		return nil
	}
	return s.Attributes
}

func (s *StorageProviderResource) GetLinks() StorageProviderResourceLinks {
	if s == nil {
		return StorageProviderResourceLinks{}
	}
	return s.Links
}
