// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type TeamResourceType string

const (
	TeamResourceTypeTeams TeamResourceType = "teams"
)

func (e TeamResourceType) ToPointer() *TeamResourceType {
	return &e
}
func (e *TeamResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "teams":
		*e = TeamResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TeamResourceType: %v", v)
	}
}

type TeamResourceAttributes struct {
	Name      string     `json:"name"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

func (t TeamResourceAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TeamResourceAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TeamResourceAttributes) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TeamResourceAttributes) GetCreatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.CreatedAt
}

func (t *TeamResourceAttributes) GetUpdatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.UpdatedAt
}

type TeamResourceLinks struct {
	Self Link `json:"self"`
}

func (t TeamResourceLinks) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TeamResourceLinks) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TeamResourceLinks) GetSelf() Link {
	if t == nil {
		return Link{}
	}
	return t.Self
}

type TeamResource struct {
	ID         string                  `json:"id"`
	Type       TeamResourceType        `json:"type"`
	Attributes *TeamResourceAttributes `json:"attributes,omitzero"`
	Links      TeamResourceLinks       `json:"links"`
}

func (t TeamResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TeamResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TeamResource) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TeamResource) GetType() TeamResourceType {
	if t == nil {
		return TeamResourceType("")
	}
	return t.Type
}

func (t *TeamResource) GetAttributes() *TeamResourceAttributes {
	if t == nil {
		return nil
	}
	return t.Attributes
}

func (t *TeamResource) GetLinks() TeamResourceLinks {
	if t == nil {
		return TeamResourceLinks{}
	}
	return t.Links
}
