// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/optionalnullable"
)

type UpdateDeploymentScriptRequest struct {
	Content    string                                  `json:"content"`
	AutoSource optionalnullable.OptionalNullable[bool] `json:"auto_source,omitzero"`
}

func (u *UpdateDeploymentScriptRequest) GetContent() string {
	if u == nil {
		return ""
	}
	return u.Content
}

func (u *UpdateDeploymentScriptRequest) GetAutoSource() optionalnullable.OptionalNullable[bool] {
	if u == nil {
		return nil
	}
	return u.AutoSource
}
