// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/optionalnullable"
)

type UpdateHealthcheckEndpointRequest struct {
	// The endpoint / URL that should be used to perform healthchecks.
	HealthcheckEndpoint optionalnullable.OptionalNullable[string] `json:"healthcheck_endpoint,omitzero"`
}

func (u *UpdateHealthcheckEndpointRequest) GetHealthcheckEndpoint() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.HealthcheckEndpoint
}
