// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/optionalnullable"
)

type UpdatePhpSettingsRequest struct {
	MaxUploadSize    optionalnullable.OptionalNullable[int64] `json:"max_upload_size,omitzero"`
	MaxExecutionTime optionalnullable.OptionalNullable[int64] `json:"max_execution_time,omitzero"`
	Opcache          optionalnullable.OptionalNullable[bool]  `json:"opcache,omitzero"`
}

func (u *UpdatePhpSettingsRequest) GetMaxUploadSize() optionalnullable.OptionalNullable[int64] {
	if u == nil {
		return nil
	}
	return u.MaxUploadSize
}

func (u *UpdatePhpSettingsRequest) GetMaxExecutionTime() optionalnullable.OptionalNullable[int64] {
	if u == nil {
		return nil
	}
	return u.MaxExecutionTime
}

func (u *UpdatePhpSettingsRequest) GetOpcache() optionalnullable.OptionalNullable[bool] {
	if u == nil {
		return nil
	}
	return u.Opcache
}
