// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/optionalnullable"
)

type UpdateDomainRequest struct {
	WwwRedirectType WwwRedirectType `json:"www_redirect_type"`
	// Whether to allow wildcard subdomains for the domain.
	AllowWildcardSubdomains optionalnullable.OptionalNullable[bool] `json:"allow_wildcard_subdomains,omitzero"`
}

func (u *UpdateDomainRequest) GetWwwRedirectType() WwwRedirectType {
	if u == nil {
		return WwwRedirectType("")
	}
	return u.WwwRedirectType
}

func (u *UpdateDomainRequest) GetAllowWildcardSubdomains() optionalnullable.OptionalNullable[bool] {
	if u == nil {
		return nil
	}
	return u.AllowWildcardSubdomains
}
