// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type UpdateServerRequest struct {
	// The name of the server.
	Name *string `json:"name,omitzero"`
	// The IP address of the server.
	IPAddress *string `json:"ip_address,omitzero"`
	// The private IP address of the server.
	PrivateIPAddress *string `json:"private_ip_address,omitzero"`
	// The timezone of the server.
	Timezone *string `json:"timezone,omitzero"`
	// The tags of the server.
	Tags []string `json:"tags,omitzero"`
}

func (u UpdateServerRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateServerRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateServerRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateServerRequest) GetIPAddress() *string {
	if u == nil {
		return nil
	}
	return u.IPAddress
}

func (u *UpdateServerRequest) GetPrivateIPAddress() *string {
	if u == nil {
		return nil
	}
	return u.PrivateIPAddress
}

func (u *UpdateServerRequest) GetTimezone() *string {
	if u == nil {
		return nil
	}
	return u.Timezone
}

func (u *UpdateServerRequest) GetTags() []string {
	if u == nil {
		return nil
	}
	return u.Tags
}
