// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type UpdateTeamRequestRole struct {
	ID int64 `json:"id"`
}

func (u *UpdateTeamRequestRole) GetID() int64 {
	if u == nil {
		return 0
	}
	return u.ID
}

type UpdateTeamRequestUser struct {
	ID   int64                  `json:"id"`
	Role *UpdateTeamRequestRole `json:"role,omitzero"`
}

func (u UpdateTeamRequestUser) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateTeamRequestUser) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateTeamRequestUser) GetID() int64 {
	if u == nil {
		return 0
	}
	return u.ID
}

func (u *UpdateTeamRequestUser) GetRole() *UpdateTeamRequestRole {
	if u == nil {
		return nil
	}
	return u.Role
}

type UpdateTeamRequest struct {
	Name  string                  `json:"name"`
	Users []UpdateTeamRequestUser `json:"users,omitzero"`
}

func (u UpdateTeamRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateTeamRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateTeamRequest) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateTeamRequest) GetUsers() []UpdateTeamRequestUser {
	if u == nil {
		return nil
	}
	return u.Users
}
