// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/mfullbrook/forge-cli/internal/sdk/optionalnullable"
)

type UpdateBackupConfigurationRequestDay string

const (
	UpdateBackupConfigurationRequestDayZero  UpdateBackupConfigurationRequestDay = "0"
	UpdateBackupConfigurationRequestDayOne   UpdateBackupConfigurationRequestDay = "1"
	UpdateBackupConfigurationRequestDayTwo   UpdateBackupConfigurationRequestDay = "2"
	UpdateBackupConfigurationRequestDayThree UpdateBackupConfigurationRequestDay = "3"
	UpdateBackupConfigurationRequestDayFour  UpdateBackupConfigurationRequestDay = "4"
	UpdateBackupConfigurationRequestDayFive  UpdateBackupConfigurationRequestDay = "5"
	UpdateBackupConfigurationRequestDaySix   UpdateBackupConfigurationRequestDay = "6"
)

func (e UpdateBackupConfigurationRequestDay) ToPointer() *UpdateBackupConfigurationRequestDay {
	return &e
}
func (e *UpdateBackupConfigurationRequestDay) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "0":
		fallthrough
	case "1":
		fallthrough
	case "2":
		fallthrough
	case "3":
		fallthrough
	case "4":
		fallthrough
	case "5":
		fallthrough
	case "6":
		*e = UpdateBackupConfigurationRequestDay(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateBackupConfigurationRequestDay: %v", v)
	}
}

type UpdateBackupConfigurationRequestTime string

const (
	UpdateBackupConfigurationRequestTimeZero                             UpdateBackupConfigurationRequestTime = "00:00"
	UpdateBackupConfigurationRequestTimeThirty                           UpdateBackupConfigurationRequestTime = "00:30"
	UpdateBackupConfigurationRequestTimeOneHundred                       UpdateBackupConfigurationRequestTime = "01:00"
	UpdateBackupConfigurationRequestTimeOneHundredAndThirty              UpdateBackupConfigurationRequestTime = "01:30"
	UpdateBackupConfigurationRequestTimeTwoHundred                       UpdateBackupConfigurationRequestTime = "02:00"
	UpdateBackupConfigurationRequestTimeTwoHundredAndThirty              UpdateBackupConfigurationRequestTime = "02:30"
	UpdateBackupConfigurationRequestTimeThreeHundred                     UpdateBackupConfigurationRequestTime = "03:00"
	UpdateBackupConfigurationRequestTimeThreeHundredAndThirty            UpdateBackupConfigurationRequestTime = "03:30"
	UpdateBackupConfigurationRequestTimeFourHundred                      UpdateBackupConfigurationRequestTime = "04:00"
	UpdateBackupConfigurationRequestTimeFourHundredAndThirty             UpdateBackupConfigurationRequestTime = "04:30"
	UpdateBackupConfigurationRequestTimeFiveHundred                      UpdateBackupConfigurationRequestTime = "05:00"
	UpdateBackupConfigurationRequestTimeFiveHundredAndThirty             UpdateBackupConfigurationRequestTime = "05:30"
	UpdateBackupConfigurationRequestTimeSixHundred                       UpdateBackupConfigurationRequestTime = "06:00"
	UpdateBackupConfigurationRequestTimeSixHundredAndThirty              UpdateBackupConfigurationRequestTime = "06:30"
	UpdateBackupConfigurationRequestTimeSevenHundred                     UpdateBackupConfigurationRequestTime = "07:00"
	UpdateBackupConfigurationRequestTimeSevenHundredAndThirty            UpdateBackupConfigurationRequestTime = "07:30"
	UpdateBackupConfigurationRequestTimeEightHundred                     UpdateBackupConfigurationRequestTime = "08:00"
	UpdateBackupConfigurationRequestTimeEightHundredAndThirty            UpdateBackupConfigurationRequestTime = "08:30"
	UpdateBackupConfigurationRequestTimeNineHundred                      UpdateBackupConfigurationRequestTime = "09:00"
	UpdateBackupConfigurationRequestTimeNineHundredAndThirty             UpdateBackupConfigurationRequestTime = "09:30"
	UpdateBackupConfigurationRequestTimeOneThousand                      UpdateBackupConfigurationRequestTime = "10:00"
	UpdateBackupConfigurationRequestTimeOneThousandAndThirty             UpdateBackupConfigurationRequestTime = "10:30"
	UpdateBackupConfigurationRequestTimeOneThousandOneHundred            UpdateBackupConfigurationRequestTime = "11:00"
	UpdateBackupConfigurationRequestTimeOneThousandOneHundredAndThirty   UpdateBackupConfigurationRequestTime = "11:30"
	UpdateBackupConfigurationRequestTimeOneThousandTwoHundred            UpdateBackupConfigurationRequestTime = "12:00"
	UpdateBackupConfigurationRequestTimeOneThousandTwoHundredAndThirty   UpdateBackupConfigurationRequestTime = "12:30"
	UpdateBackupConfigurationRequestTimeOneThousandThreeHundred          UpdateBackupConfigurationRequestTime = "13:00"
	UpdateBackupConfigurationRequestTimeOneThousandThreeHundredAndThirty UpdateBackupConfigurationRequestTime = "13:30"
	UpdateBackupConfigurationRequestTimeOneThousandFourHundred           UpdateBackupConfigurationRequestTime = "14:00"
	UpdateBackupConfigurationRequestTimeOneThousandFourHundredAndThirty  UpdateBackupConfigurationRequestTime = "14:30"
	UpdateBackupConfigurationRequestTimeOneThousandFiveHundred           UpdateBackupConfigurationRequestTime = "15:00"
	UpdateBackupConfigurationRequestTimeOneThousandFiveHundredAndThirty  UpdateBackupConfigurationRequestTime = "15:30"
	UpdateBackupConfigurationRequestTimeOneThousandSixHundred            UpdateBackupConfigurationRequestTime = "16:00"
	UpdateBackupConfigurationRequestTimeOneThousandSixHundredAndThirty   UpdateBackupConfigurationRequestTime = "16:30"
	UpdateBackupConfigurationRequestTimeOneThousandSevenHundred          UpdateBackupConfigurationRequestTime = "17:00"
	UpdateBackupConfigurationRequestTimeOneThousandSevenHundredAndThirty UpdateBackupConfigurationRequestTime = "17:30"
	UpdateBackupConfigurationRequestTimeOneThousandEightHundred          UpdateBackupConfigurationRequestTime = "18:00"
	UpdateBackupConfigurationRequestTimeOneThousandEightHundredAndThirty UpdateBackupConfigurationRequestTime = "18:30"
	UpdateBackupConfigurationRequestTimeOneThousandNineHundred           UpdateBackupConfigurationRequestTime = "19:00"
	UpdateBackupConfigurationRequestTimeOneThousandNineHundredAndThirty  UpdateBackupConfigurationRequestTime = "19:30"
	UpdateBackupConfigurationRequestTimeTwoThousand                      UpdateBackupConfigurationRequestTime = "20:00"
	UpdateBackupConfigurationRequestTimeTwoThousandAndThirty             UpdateBackupConfigurationRequestTime = "20:30"
	UpdateBackupConfigurationRequestTimeTwoThousandOneHundred            UpdateBackupConfigurationRequestTime = "21:00"
	UpdateBackupConfigurationRequestTimeTwoThousandOneHundredAndThirty   UpdateBackupConfigurationRequestTime = "21:30"
	UpdateBackupConfigurationRequestTimeTwoThousandTwoHundred            UpdateBackupConfigurationRequestTime = "22:00"
	UpdateBackupConfigurationRequestTimeTwoThousandTwoHundredAndThirty   UpdateBackupConfigurationRequestTime = "22:30"
	UpdateBackupConfigurationRequestTimeTwoThousandThreeHundred          UpdateBackupConfigurationRequestTime = "23:00"
	UpdateBackupConfigurationRequestTimeTwoThousandThreeHundredAndThirty UpdateBackupConfigurationRequestTime = "23:30"
)

func (e UpdateBackupConfigurationRequestTime) ToPointer() *UpdateBackupConfigurationRequestTime {
	return &e
}
func (e *UpdateBackupConfigurationRequestTime) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "00:00":
		fallthrough
	case "00:30":
		fallthrough
	case "01:00":
		fallthrough
	case "01:30":
		fallthrough
	case "02:00":
		fallthrough
	case "02:30":
		fallthrough
	case "03:00":
		fallthrough
	case "03:30":
		fallthrough
	case "04:00":
		fallthrough
	case "04:30":
		fallthrough
	case "05:00":
		fallthrough
	case "05:30":
		fallthrough
	case "06:00":
		fallthrough
	case "06:30":
		fallthrough
	case "07:00":
		fallthrough
	case "07:30":
		fallthrough
	case "08:00":
		fallthrough
	case "08:30":
		fallthrough
	case "09:00":
		fallthrough
	case "09:30":
		fallthrough
	case "10:00":
		fallthrough
	case "10:30":
		fallthrough
	case "11:00":
		fallthrough
	case "11:30":
		fallthrough
	case "12:00":
		fallthrough
	case "12:30":
		fallthrough
	case "13:00":
		fallthrough
	case "13:30":
		fallthrough
	case "14:00":
		fallthrough
	case "14:30":
		fallthrough
	case "15:00":
		fallthrough
	case "15:30":
		fallthrough
	case "16:00":
		fallthrough
	case "16:30":
		fallthrough
	case "17:00":
		fallthrough
	case "17:30":
		fallthrough
	case "18:00":
		fallthrough
	case "18:30":
		fallthrough
	case "19:00":
		fallthrough
	case "19:30":
		fallthrough
	case "20:00":
		fallthrough
	case "20:30":
		fallthrough
	case "21:00":
		fallthrough
	case "21:30":
		fallthrough
	case "22:00":
		fallthrough
	case "22:30":
		fallthrough
	case "23:00":
		fallthrough
	case "23:30":
		*e = UpdateBackupConfigurationRequestTime(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateBackupConfigurationRequestTime: %v", v)
	}
}

type UpdateBackupConfigurationRequest struct {
	StorageProviderID int64                                     `json:"storage_provider_id"`
	Name              optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	Bucket            optionalnullable.OptionalNullable[string] `json:"bucket,omitzero"`
	Directory         optionalnullable.OptionalNullable[string] `json:"directory,omitzero"`
	Frequency         BackupFrequency                           `json:"frequency"`
	Day               *UpdateBackupConfigurationRequestDay      `json:"day,omitzero"`
	Time              *UpdateBackupConfigurationRequestTime     `json:"time,omitzero"`
	Cron              *string                                   `json:"cron,omitzero"`
	Retention         int64                                     `json:"retention"`
	NotificationEmail optionalnullable.OptionalNullable[string] `json:"notification_email,omitzero"`
	DatabaseIds       []int64                                   `json:"database_ids"`
}

func (u *UpdateBackupConfigurationRequest) GetStorageProviderID() int64 {
	if u == nil {
		return 0
	}
	return u.StorageProviderID
}

func (u *UpdateBackupConfigurationRequest) GetName() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateBackupConfigurationRequest) GetBucket() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Bucket
}

func (u *UpdateBackupConfigurationRequest) GetDirectory() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Directory
}

func (u *UpdateBackupConfigurationRequest) GetFrequency() BackupFrequency {
	if u == nil {
		return BackupFrequency("")
	}
	return u.Frequency
}

func (u *UpdateBackupConfigurationRequest) GetDay() *UpdateBackupConfigurationRequestDay {
	if u == nil {
		return nil
	}
	return u.Day
}

func (u *UpdateBackupConfigurationRequest) GetTime() *UpdateBackupConfigurationRequestTime {
	if u == nil {
		return nil
	}
	return u.Time
}

func (u *UpdateBackupConfigurationRequest) GetCron() *string {
	if u == nil {
		return nil
	}
	return u.Cron
}

func (u *UpdateBackupConfigurationRequest) GetRetention() int64 {
	if u == nil {
		return 0
	}
	return u.Retention
}

func (u *UpdateBackupConfigurationRequest) GetNotificationEmail() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.NotificationEmail
}

func (u *UpdateBackupConfigurationRequest) GetDatabaseIds() []int64 {
	if u == nil {
		return []int64{}
	}
	return u.DatabaseIds
}
