// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateNginxConfigurationRequest struct {
	Config string `json:"config"`
}

func (u *UpdateNginxConfigurationRequest) GetConfig() string {
	if u == nil {
		return ""
	}
	return u.Config
}
