// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/optionalnullable"
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type UpdateNpmCredentialRequest struct {
	Registry string                                      `json:"registry"`
	Token    string                                      `json:"token"`
	Scopes   optionalnullable.OptionalNullable[[]string] `json:"scopes,omitzero"`
}

func (u UpdateNpmCredentialRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateNpmCredentialRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateNpmCredentialRequest) GetRegistry() string {
	if u == nil {
		return ""
	}
	return u.Registry
}

func (u *UpdateNpmCredentialRequest) GetToken() string {
	if u == nil {
		return ""
	}
	return u.Token
}

func (u *UpdateNpmCredentialRequest) GetScopes() optionalnullable.OptionalNullable[[]string] {
	if u == nil {
		return nil
	}
	return u.Scopes
}
