// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/mfullbrook/forge-cli/internal/sdk/sdkinternal/utils"
)

type Subnet struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CidrBlock string `json:"cidrBlock"`
}

func (s *Subnet) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Subnet) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *Subnet) GetCidrBlock() string {
	if s == nil {
		return ""
	}
	return s.CidrBlock
}

type VpcResourceAttributes struct {
	// The name of the vpc
	Name      string   `json:"name"`
	CidrBlock string   `json:"cidrBlock"`
	Subnets   []Subnet `json:"subnets"`
	Region    string   `json:"region"`
}

func (v *VpcResourceAttributes) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *VpcResourceAttributes) GetCidrBlock() string {
	if v == nil {
		return ""
	}
	return v.CidrBlock
}

func (v *VpcResourceAttributes) GetSubnets() []Subnet {
	if v == nil {
		return []Subnet{}
	}
	return v.Subnets
}

func (v *VpcResourceAttributes) GetRegion() string {
	if v == nil {
		return ""
	}
	return v.Region
}

type VpcResourceLinks struct {
	Self Link `json:"self"`
}

func (v *VpcResourceLinks) GetSelf() Link {
	if v == nil {
		return Link{}
	}
	return v.Self
}

type VpcResource struct {
	ID         string                 `json:"id"`
	Type       string                 `json:"type"`
	Attributes *VpcResourceAttributes `json:"attributes,omitzero"`
	Links      VpcResourceLinks       `json:"links"`
}

func (v VpcResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VpcResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VpcResource) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *VpcResource) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

func (v *VpcResource) GetAttributes() *VpcResourceAttributes {
	if v == nil {
		return nil
	}
	return v.Attributes
}

func (v *VpcResource) GetLinks() VpcResourceLinks {
	if v == nil {
		return VpcResourceLinks{}
	}
	return v.Links
}
